/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author DucQuang
 */
public class FormXacNhanTinhTrangGiaoHang extends javax.swing.JFrame {

    /**
     * Creates new form FormXacNhanTinhTrangGiaoHang
     */
    public FormXacNhanTinhTrangGiaoHang() {
        initComponents();
        setLocationRelativeTo(null);
        
        jPanel10.setBackground(new Color(0,0,0,80));
        
        jPnTracuuHDchuagiao.setBackground(new Color(0,204,204,150));
        jPnDSHDchuagiao.setBackground(new Color(0,204,204,150));
        jPnTracuuHDdagiao.setBackground(new Color(0,204,204,150));
        jPnDSHDdagiao.setBackground(new Color(0,204,204,150));
        jPnThongtinHD.setBackground(new Color(0,204,204,150));
        
        jPanel1.setBackground(new Color(236,236,236,190));
        jPanel2.setBackground(new Color(236,236,236,190));
        jPanel4.setBackground(new Color(236,236,236,190));
        jPanel9.setBackground(new Color(236,236,236,190));
        jPanel3.setBackground(new Color(236,236,236,190));
        
        jBtnBack.setBackground(new Color(153,153,153,180));
        jBtnTimKiemHDchuagiao.setBackground(new Color(153,153,153,180));
        jBtnLamMoichuagiao.setBackground(new Color(153,153,153,180));
        jBtnTimKiemHDdagiao.setBackground(new Color(153,153,153,180));
        jBtnLamMoidagiao.setBackground(new Color(153,153,153,180));
        jBtnXemchitiet.setBackground(new Color(153,153,153,180));
        jBtnXacnhangiao.setBackground(new Color(153,153,153,180));
        
        
        jScrDSHDchuagiao.setOpaque(false);
        jScrDSHDchuagiao.getViewport().setOpaque(false);
        jTbDSHDchuagiao.setShowGrid(true);
        ((DefaultTableCellRenderer)jTbDSHDchuagiao.getDefaultRenderer(Object.class)).setBackground(new Color(236,236,236,190));
        ((DefaultTableCellRenderer)jTbDSHDchuagiao.getDefaultRenderer(Object.class)).setOpaque(false);
        ((DefaultTableCellRenderer)jTbDSHDchuagiao.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
        jScrDSHDdagiao.setOpaque(false);
        jScrDSHDdagiao.getViewport().setOpaque(false);
        jTbDSHDdagiao.setShowGrid(true);
        ((DefaultTableCellRenderer)jTbDSHDdagiao.getDefaultRenderer(Object.class)).setBackground(new Color(236,236,236,190));
        ((DefaultTableCellRenderer)jTbDSHDdagiao.getDefaultRenderer(Object.class)).setOpaque(false);
        ((DefaultTableCellRenderer)jTbDSHDdagiao.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jBtnBack = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jBtnLamMoichuagiao = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jBtnTimKiemHDchuagiao = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jBtnLamMoidagiao = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jBtnTimKiemHDdagiao = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jBtnXemchitiet = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jBtnXacnhangiao = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrDSHDchuagiao = new javax.swing.JScrollPane();
        jTbDSHDchuagiao = new javax.swing.JTable();
        jPnDSHDchuagiao = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPnDSHDdagiao = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrDSHDdagiao = new javax.swing.JScrollPane();
        jTbDSHDdagiao = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPnThongtinHD = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPnTracuuHDdagiao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPnTracuuHDchuagiao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đơn chưa giao"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đã giao"));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBackMouseReleased(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBackLayout = new javax.swing.GroupLayout(jBtnBack);
        jBtnBack.setLayout(jBtnBackLayout);
        jBtnBackLayout.setHorizontalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBackLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBtnBackLayout.setVerticalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jBtnLamMoichuagiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLamMoichuagiao.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnLamMoichuagiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLamMoichuagiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLamMoichuagiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLamMoichuagiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLamMoichuagiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLamMoichuagiaoMouseReleased(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Refresh_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLamMoichuagiaoLayout = new javax.swing.GroupLayout(jBtnLamMoichuagiao);
        jBtnLamMoichuagiao.setLayout(jBtnLamMoichuagiaoLayout);
        jBtnLamMoichuagiaoLayout.setHorizontalGroup(
            jBtnLamMoichuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnLamMoichuagiaoLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(37, 37, 37))
        );
        jBtnLamMoichuagiaoLayout.setVerticalGroup(
            jBtnLamMoichuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnLamMoichuagiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 120, 65));

        jBtnTimKiemHDchuagiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTimKiemHDchuagiao.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnTimKiemHDchuagiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDchuagiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDchuagiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDchuagiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDchuagiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDchuagiaoMouseReleased(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnTimKiemHDchuagiaoLayout = new javax.swing.GroupLayout(jBtnTimKiemHDchuagiao);
        jBtnTimKiemHDchuagiao.setLayout(jBtnTimKiemHDchuagiaoLayout);
        jBtnTimKiemHDchuagiaoLayout.setHorizontalGroup(
            jBtnTimKiemHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTimKiemHDchuagiaoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jBtnTimKiemHDchuagiaoLayout.setVerticalGroup(
            jBtnTimKiemHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnTimKiemHDchuagiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 120, 65));

        jBtnLamMoidagiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLamMoidagiao.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnLamMoidagiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLamMoidagiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLamMoidagiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLamMoidagiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLamMoidagiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLamMoidagiaoMouseReleased(evt);
            }
        });

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Refresh_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLamMoidagiaoLayout = new javax.swing.GroupLayout(jBtnLamMoidagiao);
        jBtnLamMoidagiao.setLayout(jBtnLamMoidagiaoLayout);
        jBtnLamMoidagiaoLayout.setHorizontalGroup(
            jBtnLamMoidagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnLamMoidagiaoLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(37, 37, 37))
        );
        jBtnLamMoidagiaoLayout.setVerticalGroup(
            jBtnLamMoidagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnLamMoidagiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 190, 120, 65));

        jBtnTimKiemHDdagiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTimKiemHDdagiao.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnTimKiemHDdagiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDdagiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDdagiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDdagiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDdagiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDdagiaoMouseReleased(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnTimKiemHDdagiaoLayout = new javax.swing.GroupLayout(jBtnTimKiemHDdagiao);
        jBtnTimKiemHDdagiao.setLayout(jBtnTimKiemHDdagiaoLayout);
        jBtnTimKiemHDdagiaoLayout.setHorizontalGroup(
            jBtnTimKiemHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTimKiemHDdagiaoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jBtnTimKiemHDdagiaoLayout.setVerticalGroup(
            jBtnTimKiemHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnTimKiemHDdagiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 120, 65));

        jBtnXemchitiet.setBackground(new java.awt.Color(153, 153, 153));
        jBtnXemchitiet.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXemchitiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXemchitietMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXemchitietMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXemchitietMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXemchitietMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXemchitietMouseReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_View_Details_55px_1.png"))); // NOI18N
        jLabel22.setText("Xem chi tiết");

        javax.swing.GroupLayout jBtnXemchitietLayout = new javax.swing.GroupLayout(jBtnXemchitiet);
        jBtnXemchitiet.setLayout(jBtnXemchitietLayout);
        jBtnXemchitietLayout.setHorizontalGroup(
            jBtnXemchitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jBtnXemchitietLayout.setVerticalGroup(
            jBtnXemchitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnXemchitietLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jBtnXemchitiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 642, 190, 65));

        jBtnXacnhangiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnXacnhangiao.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnXacnhangiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXacnhangiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXacnhangiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXacnhangiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXacnhangiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXacnhangiaoMouseReleased(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Tick_Box_40px.png"))); // NOI18N
        jLabel23.setText("Xác nhận đã giao");

        javax.swing.GroupLayout jBtnXacnhangiaoLayout = new javax.swing.GroupLayout(jBtnXacnhangiao);
        jBtnXacnhangiao.setLayout(jBtnXacnhangiaoLayout);
        jBtnXacnhangiaoLayout.setHorizontalGroup(
            jBtnXacnhangiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jBtnXacnhangiaoLayout.setVerticalGroup(
            jBtnXacnhangiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnXacnhangiaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addContainerGap())
        );

        getContentPane().add(jBtnXacnhangiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 642, 190, 65));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTbDSHDchuagiao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrDSHDchuagiao.setViewportView(jTbDSHDchuagiao);

        jPnDSHDchuagiao.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Danh sách hóa đơn chưa giao:");

        javax.swing.GroupLayout jPnDSHDchuagiaoLayout = new javax.swing.GroupLayout(jPnDSHDchuagiao);
        jPnDSHDchuagiao.setLayout(jPnDSHDchuagiaoLayout);
        jPnDSHDchuagiaoLayout.setHorizontalGroup(
            jPnDSHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSHDchuagiaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPnDSHDchuagiaoLayout.setVerticalGroup(
            jPnDSHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnDSHDchuagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrDSHDchuagiao, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrDSHDchuagiao, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPnDSHDchuagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 280, 430, 427));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPnDSHDdagiao.setBackground(new java.awt.Color(0, 204, 204));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Danh sách hóa đơn chưa giao:");

        javax.swing.GroupLayout jPnDSHDdagiaoLayout = new javax.swing.GroupLayout(jPnDSHDdagiao);
        jPnDSHDdagiao.setLayout(jPnDSHDdagiaoLayout);
        jPnDSHDdagiaoLayout.setHorizontalGroup(
            jPnDSHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSHDdagiaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPnDSHDdagiaoLayout.setVerticalGroup(
            jPnDSHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jTbDSHDdagiao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrDSHDdagiao.setViewportView(jTbDSHDdagiao);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrDSHDdagiao, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPnDSHDdagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnDSHDdagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrDSHDdagiao, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 280, 430, 427));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Số hóa đơn:");

        jLabel7.setText("Tên khách hàng:");

        jLabel8.setText("Mã khách hàng:");

        jLabel9.setText("Địa chỉ:");

        jLabel10.setText("Số điện thoại:");

        jLabel11.setText("Ngày đặt:");

        jLabel12.setText("Tình trạng giao hàng:");

        jLabel13.setText("Ngày giao dự kiến:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPnThongtinHD.setBackground(new java.awt.Color(0, 204, 204));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Thông tin hóa đơn:");

        javax.swing.GroupLayout jPnThongtinHDLayout = new javax.swing.GroupLayout(jPnThongtinHD);
        jPnThongtinHD.setLayout(jPnThongtinHDLayout);
        jPnThongtinHDLayout.setHorizontalGroup(
            jPnThongtinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongtinHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPnThongtinHDLayout.setVerticalGroup(
            jPnThongtinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(46, 46, 46)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField4)
                                        .addComponent(jTextField3)
                                        .addComponent(jTextField5)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPnThongtinHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPnThongtinHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(167, 167, 167))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 400, 580));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPnTracuuHDdagiao.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tra cứu hóa đơn đã giao:");

        javax.swing.GroupLayout jPnTracuuHDdagiaoLayout = new javax.swing.GroupLayout(jPnTracuuHDdagiao);
        jPnTracuuHDdagiao.setLayout(jPnTracuuHDdagiaoLayout);
        jPnTracuuHDdagiaoLayout.setHorizontalGroup(
            jPnTracuuHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTracuuHDdagiaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPnTracuuHDdagiaoLayout.setVerticalGroup(
            jPnTracuuHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jLabel15.setText("Tên khách hàng :");

        jLabel16.setText("Số hóa đơn:");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField11)
                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPnTracuuHDdagiao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPnTracuuHDdagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 50, 430, 220));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Số hóa đơn:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPnTracuuHDchuagiao.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tra cứu hóa đơn chưa giao :");

        javax.swing.GroupLayout jPnTracuuHDchuagiaoLayout = new javax.swing.GroupLayout(jPnTracuuHDchuagiao);
        jPnTracuuHDchuagiao.setLayout(jPnTracuuHDchuagiaoLayout);
        jPnTracuuHDchuagiaoLayout.setHorizontalGroup(
            jPnTracuuHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTracuuHDchuagiaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPnTracuuHDchuagiaoLayout.setVerticalGroup(
            jPnTracuuHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel5.setText("Tên khách hàng :");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPnTracuuHDchuagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPnTracuuHDchuagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 50, 430, 220));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 720));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo 1234.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setPreferredSize(new java.awt.Dimension(1320, 720));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseEntered

    private void jBtnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseExited

    private void jBtnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMousePressed

    private void jBtnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseReleased

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jBtnTimKiemHDchuagiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDchuagiaoMouseClicked

    }//GEN-LAST:event_jBtnTimKiemHDchuagiaoMouseClicked

    private void jBtnTimKiemHDchuagiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDchuagiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTimKiemHDchuagiao);
    }//GEN-LAST:event_jBtnTimKiemHDchuagiaoMouseEntered

    private void jBtnTimKiemHDchuagiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDchuagiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTimKiemHDchuagiao);
    }//GEN-LAST:event_jBtnTimKiemHDchuagiaoMouseExited

    private void jBtnTimKiemHDchuagiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDchuagiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTimKiemHDchuagiao);
    }//GEN-LAST:event_jBtnTimKiemHDchuagiaoMousePressed

    private void jBtnTimKiemHDchuagiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDchuagiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTimKiemHDchuagiao);
    }//GEN-LAST:event_jBtnTimKiemHDchuagiaoMouseReleased

    private void jBtnLamMoichuagiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoichuagiaoMouseClicked
        // TODO add your handling code here:
        //        try {
            //            // TODO add your handling code here:
            //            ResultSet rs =BSP.searchByPropertiesWithFulltext(jtxtTimKiemMaSP.getText(),jtxtTimKiemTenSP.getText(),jCbbLoaiSP.getSelectedItem().toString());
            //            if(rs.getRow()==0){
                //                rs =BSP.searchByPropertiesNormal(jtxtTimKiemMaSP.getText(),jtxtTimKiemTenSP.getText(),jCbbLoaiSP.getSelectedItem().toString());
                //            }
            //            displayData(rs);
            //            Binding();
            //        } catch (SQLException ex) {
            //            Logger.getLogger(FrmQuanLiSanPham.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_jBtnLamMoichuagiaoMouseClicked

    private void jBtnLamMoichuagiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoichuagiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLamMoichuagiao);
    }//GEN-LAST:event_jBtnLamMoichuagiaoMouseEntered

    private void jBtnLamMoichuagiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoichuagiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLamMoichuagiao);
    }//GEN-LAST:event_jBtnLamMoichuagiaoMouseExited

    private void jBtnLamMoichuagiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoichuagiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLamMoichuagiao);
    }//GEN-LAST:event_jBtnLamMoichuagiaoMousePressed

    private void jBtnLamMoichuagiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoichuagiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLamMoichuagiao);
    }//GEN-LAST:event_jBtnLamMoichuagiaoMouseReleased

    private void jBtnTimKiemHDdagiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDdagiaoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBtnTimKiemHDdagiaoMouseClicked

    private void jBtnTimKiemHDdagiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDdagiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTimKiemHDdagiao);
    }//GEN-LAST:event_jBtnTimKiemHDdagiaoMouseEntered

    private void jBtnTimKiemHDdagiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDdagiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTimKiemHDdagiao);
    }//GEN-LAST:event_jBtnTimKiemHDdagiaoMouseExited

    private void jBtnTimKiemHDdagiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDdagiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTimKiemHDdagiao);
    }//GEN-LAST:event_jBtnTimKiemHDdagiaoMousePressed

    private void jBtnTimKiemHDdagiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDdagiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTimKiemHDdagiao);
    }//GEN-LAST:event_jBtnTimKiemHDdagiaoMouseReleased

    private void jBtnLamMoidagiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoidagiaoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBtnLamMoidagiaoMouseClicked

    private void jBtnLamMoidagiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoidagiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLamMoidagiao);
    }//GEN-LAST:event_jBtnLamMoidagiaoMouseEntered

    private void jBtnLamMoidagiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoidagiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLamMoidagiao);
    }//GEN-LAST:event_jBtnLamMoidagiaoMouseExited

    private void jBtnLamMoidagiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoidagiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLamMoidagiao);
    }//GEN-LAST:event_jBtnLamMoidagiaoMousePressed

    private void jBtnLamMoidagiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoidagiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLamMoidagiao);
    }//GEN-LAST:event_jBtnLamMoidagiaoMouseReleased

    private void jBtnXemchitietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemchitietMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBtnXemchitietMouseClicked

    private void jBtnXemchitietMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemchitietMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXemchitiet);
    }//GEN-LAST:event_jBtnXemchitietMouseEntered

    private void jBtnXemchitietMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemchitietMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXemchitiet);
    }//GEN-LAST:event_jBtnXemchitietMouseExited

    private void jBtnXemchitietMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemchitietMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXemchitiet);
    }//GEN-LAST:event_jBtnXemchitietMousePressed

    private void jBtnXemchitietMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemchitietMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXemchitiet);
    }//GEN-LAST:event_jBtnXemchitietMouseReleased

    private void jBtnXacnhangiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacnhangiaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXacnhangiaoMouseClicked

    private void jBtnXacnhangiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacnhangiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXacnhangiao);
    }//GEN-LAST:event_jBtnXacnhangiaoMouseEntered

    private void jBtnXacnhangiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacnhangiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXacnhangiao);
    }//GEN-LAST:event_jBtnXacnhangiaoMouseExited

    private void jBtnXacnhangiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacnhangiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXacnhangiao);
    }//GEN-LAST:event_jBtnXacnhangiaoMousePressed

    private void jBtnXacnhangiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacnhangiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXacnhangiao);
    }//GEN-LAST:event_jBtnXacnhangiaoMouseReleased

    public void setColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()+1, pn.getHeight()+1);
        pn.setBackground(new Color(60,209,127,50));
        }
    }
    public void resetColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()-1, pn.getHeight()-1);
        pn.setBackground(new Color(153,153,153,180));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormXacNhanTinhTrangGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormXacNhanTinhTrangGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormXacNhanTinhTrangGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormXacNhanTinhTrangGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormXacNhanTinhTrangGiaoHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack;
    private javax.swing.JPanel jBtnLamMoichuagiao;
    private javax.swing.JPanel jBtnLamMoidagiao;
    private javax.swing.JPanel jBtnTimKiemHDchuagiao;
    private javax.swing.JPanel jBtnTimKiemHDdagiao;
    private javax.swing.JPanel jBtnXacnhangiao;
    private javax.swing.JPanel jBtnXemchitiet;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPnDSHDchuagiao;
    private javax.swing.JPanel jPnDSHDdagiao;
    private javax.swing.JPanel jPnThongtinHD;
    private javax.swing.JPanel jPnTracuuHDchuagiao;
    private javax.swing.JPanel jPnTracuuHDdagiao;
    private javax.swing.JScrollPane jScrDSHDchuagiao;
    private javax.swing.JScrollPane jScrDSHDdagiao;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTbDSHDchuagiao;
    private javax.swing.JTable jTbDSHDdagiao;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
