/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.CtrlQuanLiNguoiDung;
import Edit.Edit;
import Model.ModTaiKhoan;
import Object.ObjTaiKhoan;
import com.sun.prism.j2d.J2DPipeline;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ThaiNguyen
 */
public class FormQuanLiUser extends javax.swing.JFrame {

    /**
     * Creates new form FormQuanLiUser
     */
    Edit editFrm=new Edit();
    int xx,yy;
    ArrayList<ObjTaiKhoan> ListUser = new ArrayList<>();
    CtrlQuanLiNguoiDung ctrlQLND = new CtrlQuanLiNguoiDung();
    ModTaiKhoan modTK = new ModTaiKhoan();
    public FormQuanLiUser() {
        initComponents();
        setLocationRelativeTo(null);
        JPanel ListPanel[]=new JPanel[]{jPanel1};
        editFrm.MakeTransparentPanel(ListPanel);
        JPanel ListTitle[]=new JPanel[]{jPnDSNguoiDung};
        editFrm.MakeTransparentTitle(ListTitle);
        JPanel ListButton[]=new JPanel[]{jBtnBack1,jBtnCapNhat,jBtnXoa};
        editFrm.MakeTransparentButton(ListButton);
        editFrm.MakeTransparentTable(jScrDSNguoiDung, jtbDSNguoiDung);


        JCheckBox check = new JCheckBox();
        JComboBox com = new JComboBox();
        JButton button = new JButton();
        com.addItem("Quản lý");
        com.addItem("Quản lý bán hàng");
        com.addItem("Quản lý kho");
        com.addItem("Quản lý kế toán");
        com.setFocusable(false);
        com.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try{
                DefaultTableModel model = (DefaultTableModel) jtbDSNguoiDung.getModel();
                int viewRow = jtbDSNguoiDung.getSelectedRow();
                int modelRow = jtbDSNguoiDung.convertRowIndexToModel(viewRow);
                if (com.getSelectedIndex() >= 0) {
                    if (!model.getValueAt(modelRow,2).equals(ListUser.get(modelRow).getPhanLoai())) {
                        int dialogButton=JOptionPane.showConfirmDialog(null,"Xác nhận thay đổi phân quyền?", "Xác nhận", JOptionPane.YES_NO_OPTION);
                        if (dialogButton == JOptionPane.YES_OPTION) {
                            ListUser.get(modelRow).setPhanLoai(model.getValueAt(modelRow,2).toString());
                            if(modTK.UpdatePhanQuyen(ListUser.get(modelRow)))
                                JOptionPane.showMessageDialog(null,"Đã thay đổi","", JOptionPane.INFORMATION_MESSAGE);
                            else JOptionPane.showMessageDialog(null,"Thay đổi thất bại","", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else model.setValueAt(ListUser.get(modelRow).getPhanLoai(), modelRow, 2);
                    }
                }
                }
                catch(Exception ex){
                    System.out.println("Ngoại lệ tại FormQuanLiUser.com.addActionListener:"+ex.getMessage());
                }
            }
        });
        DefaultCellEditor de = new DefaultCellEditor(check);
        DefaultCellEditor de2 = new DefaultCellEditor(com);
        jtbDSNguoiDung.getColumnModel().getColumn(2).setCellEditor(de2);
        HienThiDanhSachNguoiDung(ctrlQLND.LayDanhSachNguoiDung());
    }

    public void HienThiDanhSachNguoiDung(ResultSet rs){
        ListUser.clear();
        DefaultTableModel model = (DefaultTableModel) jtbDSNguoiDung.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            while (rs.next()) {
                ObjTaiKhoan itemTK = new ObjTaiKhoan(rs.getString("TenDangNhap"),rs.getString("Ten"),rs.getString("PhanLoai"));
                ListUser.add(itemTK);
                model.addRow(new Object[]{itemTK.getTen(),itemTK.getTenDangNhap(),itemTK.getPhanLoai()});
            }
        } catch (Exception ex) {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnCapNhat = new javax.swing.JPanel();
        jlbLuu = new javax.swing.JLabel();
        jBtnXoa = new javax.swing.JPanel();
        jlbIn1 = new javax.swing.JLabel();
        jBtnBack1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrDSNguoiDung = new javax.swing.JScrollPane();
        jtbDSNguoiDung = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPnDSNguoiDung = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnCapNhat.setBackground(new java.awt.Color(102, 102, 102));
        jBtnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCapNhatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnCapNhatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnCapNhatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnCapNhatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnCapNhatMouseReleased(evt);
            }
        });
        jBtnCapNhat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbLuu.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbLuu.setForeground(new java.awt.Color(255, 255, 255));
        jlbLuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLuu.setText("Thêm người dùng");
        jBtnCapNhat.add(jlbLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        getContentPane().add(jBtnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 165, 60));

        jBtnXoa.setBackground(new java.awt.Color(102, 102, 102));
        jBtnXoa.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXoaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseReleased(evt);
            }
        });
        jBtnXoa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIn1.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbIn1.setForeground(new java.awt.Color(255, 255, 255));
        jlbIn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIn1.setText("Xóa người dùng");
        jBtnXoa.add(jlbIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 40));

        getContentPane().add(jBtnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 480, 165, 60));

        jBtnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBack1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseReleased(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBack1Layout = new javax.swing.GroupLayout(jBtnBack1);
        jBtnBack1.setLayout(jBtnBack1Layout);
        jBtnBack1Layout.setHorizontalGroup(
            jBtnBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBack1Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBtnBack1Layout.setVerticalGroup(
            jBtnBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBack1Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jtbDSNguoiDung.setAutoCreateRowSorter(true);
        jtbDSNguoiDung.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jtbDSNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên người dùng", "Tên đăng nhập", "Chức vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDSNguoiDung.setFocusable(false);
        jtbDSNguoiDung.setRowHeight(25);
        jtbDSNguoiDung.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jtbDSNguoiDung.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrDSNguoiDung.setViewportView(jtbDSNguoiDung);

        getContentPane().add(jScrDSNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 95, 780, 370));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnDSNguoiDung.setBackground(new java.awt.Color(0, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Danh sách người dùng :");

        javax.swing.GroupLayout jPnDSNguoiDungLayout = new javax.swing.GroupLayout(jPnDSNguoiDung);
        jPnDSNguoiDung.setLayout(jPnDSNguoiDungLayout);
        jPnDSNguoiDungLayout.setHorizontalGroup(
            jPnDSNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSNguoiDungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(633, Short.MAX_VALUE))
        );
        jPnDSNguoiDungLayout.setVerticalGroup(
            jPnDSNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPnDSNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 790, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo-530024.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnBack1MouseClicked

    private void jBtnBack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MouseEntered

    private void jBtnBack1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MouseExited

    private void jBtnBack1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MousePressed

    private void jBtnBack1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MouseReleased

    private void jBtnCapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCapNhatMouseClicked
        // TODO add your handling code here:
        FormDangKi frmDK = new FormDangKi();
        frmDK.flag=1;
        frmDK.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jBtnCapNhatMouseClicked

    private void jBtnCapNhatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCapNhatMouseEntered
        // TODO add your handling code here:
        setColor(jBtnCapNhat);
    }//GEN-LAST:event_jBtnCapNhatMouseEntered

    private void jBtnCapNhatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCapNhatMouseExited
        // TODO add your handling code here:
        resetColor(jBtnCapNhat);
    }//GEN-LAST:event_jBtnCapNhatMouseExited

    private void jBtnCapNhatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCapNhatMousePressed
        // TODO add your handling code here:
        resetColor(jBtnCapNhat);
    }//GEN-LAST:event_jBtnCapNhatMousePressed

    private void jBtnCapNhatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCapNhatMouseReleased
        // TODO add your handling code here:
        setColor(jBtnCapNhat);
    }//GEN-LAST:event_jBtnCapNhatMouseReleased

    private void jBtnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseClicked
        // TODO add your handling code here:
        try{
        DefaultTableModel model = (DefaultTableModel) jtbDSNguoiDung.getModel();
        int viewRow = jtbDSNguoiDung.getSelectedRow();
        int modelRow = jtbDSNguoiDung.convertRowIndexToModel(viewRow);
        int dialogButton = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            if (modTK.Delete(ListUser.get(modelRow).getTenDangNhap())) {
                JOptionPane.showMessageDialog(this, "Đã xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                HienThiDanhSachNguoiDung(ctrlQLND.LayDanhSachNguoiDung());
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        }
        catch(Exception ex){
            System.out.println("Ngoại lệ tại FormQuanLiUser.jBtnXoaMouseClicked:"+ex.getMessage());
        }
    }//GEN-LAST:event_jBtnXoaMouseClicked

    private void jBtnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseEntered

    private void jBtnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseExited

    private void jBtnXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMousePressed

    private void jBtnXoaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseReleased

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jLabel1MouseDragged

    public void setColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()+1, pn.getHeight()+1);
        pn.setBackground(new Color(60,209,127,50));
        }
    }
    public void resetColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()-1, pn.getHeight()-1);
        pn.setBackground(new Color(153,153,153,180));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLiUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack1;
    private javax.swing.JPanel jBtnCapNhat;
    private javax.swing.JPanel jBtnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnDSNguoiDung;
    private javax.swing.JScrollPane jScrDSNguoiDung;
    private javax.swing.JLabel jlbIn1;
    private javax.swing.JLabel jlbLuu;
    private javax.swing.JTable jtbDSNguoiDung;
    // End of variables declaration//GEN-END:variables
}
