/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Object.ObjTaiKhoan;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ThaiNguyen
 */
public class FormQuanLiKho extends javax.swing.JFrame {
    
    int xx,yy;
    /**
     * Creates new form MainForm
     */
    private ObjTaiKhoan User = new ObjTaiKhoan("15520783","123456");
    
    public FormQuanLiKho(ObjTaiKhoan objTK) {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0,0,0,80));
        jBtnTTGH.setBackground(new Color(236,236,236,50));
        jBtnNH.setBackground(new Color(236,236,236,50));  
        jBtnDH.setBackground(new Color(236,236,236,50));  
        jBtnSP.setBackground(new Color(236,236,236,50));  
        jBtnLSP.setBackground(new Color(236,236,236,50));  
        jBtnNCC.setBackground(new Color(236,236,236,50));  
        jBtnBack.setBackground(new Color(236,236,236,50));
        
        User=new ObjTaiKhoan(objTK.getTenDangNhap(), objTK.getMatKhau(), objTK.getTen(), objTK.getPhanLoai());
    }

    private FormQuanLiKho() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0,0,0,80));
        jBtnTTGH.setBackground(new Color(236,236,236,50));
        jBtnNH.setBackground(new Color(236,236,236,50));  
        jBtnDH.setBackground(new Color(236,236,236,50));  
        jBtnSP.setBackground(new Color(236,236,236,50));  
        jBtnLSP.setBackground(new Color(236,236,236,50));  
        jBtnNCC.setBackground(new Color(236,236,236,50));  
        jBtnBack.setBackground(new Color(236,236,236,50)); 
    }
    
    public void setColor(JPanel pn){
        pn.setSize(pn.getWidth()+1, pn.getHeight()+1);
        pn.setBackground(new Color(60,209,127,50));
    }
    public void resetColor(JPanel pn){   
        pn.setSize(pn.getWidth()-1, pn.getHeight()-1);
        pn.setBackground(new Color(236,236,236,50));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnClose = new javax.swing.JLabel();
        jBtnSP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBtnLSP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jBtnNCC = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jBtnBack = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jBtnDH = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jBtnNH = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jBtnTTGH = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnClose.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jBtnClose.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClose.setText("X");
        jBtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 20, 30));

        jBtnSP.setBackground(new java.awt.Color(153, 153, 153));
        jBtnSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnSPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnSPMouseReleased(evt);
            }
        });
        jBtnSP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Product_70px.png"))); // NOI18N
        jBtnSP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 60));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Quản lí sản phẩm");
        jBtnSP.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, 120));

        jBtnLSP.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLSPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLSPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLSPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLSPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLSPMouseReleased(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Trolley_70px.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Quản lí loại sản phẩm");

        javax.swing.GroupLayout jBtnLSPLayout = new javax.swing.GroupLayout(jBtnLSP);
        jBtnLSP.setLayout(jBtnLSPLayout);
        jBtnLSPLayout.setHorizontalGroup(
            jBtnLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLSPLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnLSPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(27, 27, 27))
        );
        jBtnLSPLayout.setVerticalGroup(
            jBtnLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLSPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnLSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, 120));

        jBtnNCC.setBackground(new java.awt.Color(153, 153, 153));
        jBtnNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnNCCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnNCCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnNCCMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnNCCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnNCCMouseReleased(evt);
            }
        });
        jBtnNCC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Supplier_70px.png"))); // NOI18N
        jBtnNCC.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 83, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Nhà cung cấp");
        jBtnNCC.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 92, 90, -1));

        getContentPane().add(jBtnNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 180, 120));

        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBackMouseReleased(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBackLayout = new javax.swing.GroupLayout(jBtnBack);
        jBtnBack.setLayout(jBtnBackLayout);
        jBtnBackLayout.setHorizontalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jBtnBackLayout.setVerticalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jBtnDH.setBackground(new java.awt.Color(153, 153, 153));
        jBtnDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDHMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnDHMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnDHMouseReleased(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Deliver_Food_70px.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Quản lí đặt hàng");

        javax.swing.GroupLayout jBtnDHLayout = new javax.swing.GroupLayout(jBtnDH);
        jBtnDH.setLayout(jBtnDHLayout);
        jBtnDHLayout.setHorizontalGroup(
            jBtnDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDHLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnDHLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jBtnDHLayout.setVerticalGroup(
            jBtnDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jBtnDH, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, 120));

        jBtnNH.setBackground(new java.awt.Color(153, 153, 153));
        jBtnNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnNHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnNHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnNHMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnNHMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnNHMouseReleased(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delivered_67px.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Quản lí nhập hàng");

        javax.swing.GroupLayout jBtnNHLayout = new javax.swing.GroupLayout(jBtnNH);
        jBtnNH.setLayout(jBtnNHLayout);
        jBtnNHLayout.setHorizontalGroup(
            jBtnNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnNHLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jBtnNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnNHLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnNHLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        jBtnNHLayout.setVerticalGroup(
            jBtnNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnNHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jBtnNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, 120));

        jBtnTTGH.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTTGH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTTGHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTTGHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTTGHMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTTGHMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTTGHMouseReleased(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Customs_Officer_67px.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Tình trạng giao hàng");

        javax.swing.GroupLayout jBtnTTGHLayout = new javax.swing.GroupLayout(jBtnTTGH);
        jBtnTTGH.setLayout(jBtnTTGHLayout);
        jBtnTTGHLayout.setHorizontalGroup(
            jBtnTTGHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnTTGHLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jBtnTTGHLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jBtnTTGHLayout.setVerticalGroup(
            jBtnTTGHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTTGHLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jBtnTTGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/navigation.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 80));

        jLabel14.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Get Managed");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Support Management");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Quản lí kho hàng");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 190, 40));

        jLabel20.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Design, Create By Closer Group");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 200, 10));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSPMouseEntered
        // TODO add your handling code here:
        setColor(jBtnSP);
    }//GEN-LAST:event_jBtnSPMouseEntered

    private void jBtnSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSPMouseExited
        // TODO add your handling code here:
        resetColor(jBtnSP);
    }//GEN-LAST:event_jBtnSPMouseExited

    private void jBtnLSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLSPMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLSP);
    }//GEN-LAST:event_jBtnLSPMouseEntered

    private void jBtnLSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLSPMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLSP);
        
    }//GEN-LAST:event_jBtnLSPMouseExited

    private void jBtnNCCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNCCMouseEntered
        // TODO add your handling code here:
        setColor(jBtnNCC);
    }//GEN-LAST:event_jBtnNCCMouseEntered

    private void jBtnNCCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNCCMouseExited
        // TODO add your handling code here:
        resetColor(jBtnNCC);
    }//GEN-LAST:event_jBtnNCCMouseExited

    private void jBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtnCloseMouseClicked

    private void jBtnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseEntered

    private void jBtnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseExited

    private void jBtnSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSPMousePressed
        // TODO add your handling code here:
        resetColor(jBtnSP);
    }//GEN-LAST:event_jBtnSPMousePressed

    private void jBtnSPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSPMouseReleased
        // TODO add your handling code here:
        if(jBtnSP.getBackground().equals(new Color(236,236,236,50))){
        setColor(jBtnSP);
        }
    }//GEN-LAST:event_jBtnSPMouseReleased

    private void jBtnLSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLSPMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLSP);
    }//GEN-LAST:event_jBtnLSPMousePressed

    private void jBtnLSPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLSPMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLSP);
    }//GEN-LAST:event_jBtnLSPMouseReleased

    private void jBtnNCCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNCCMousePressed
        // TODO add your handling code here:
        resetColor(jBtnNCC);
    }//GEN-LAST:event_jBtnNCCMousePressed

    private void jBtnNCCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNCCMouseReleased
        // TODO add your handling code here:
        setColor(jBtnNCC);
    }//GEN-LAST:event_jBtnNCCMouseReleased

    private void jBtnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMousePressed

    private void jBtnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseReleased

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jBtnDHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDHMouseEntered
        // TODO add your handling code here:
        setColor(jBtnDH);
    }//GEN-LAST:event_jBtnDHMouseEntered

    private void jBtnDHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDHMouseExited
        // TODO add your handling code here:
        resetColor(jBtnDH);
    }//GEN-LAST:event_jBtnDHMouseExited

    private void jBtnDHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDHMousePressed
        // TODO add your handling code here:
        resetColor(jBtnDH);
    }//GEN-LAST:event_jBtnDHMousePressed

    private void jBtnDHMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDHMouseReleased
        // TODO add your handling code here:
        setColor(jBtnDH);
    }//GEN-LAST:event_jBtnDHMouseReleased

    private void jBtnNHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNHMouseEntered
        // TODO add your handling code here:
        setColor(jBtnNH);
    }//GEN-LAST:event_jBtnNHMouseEntered

    private void jBtnNHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNHMouseExited
        // TODO add your handling code here:
        resetColor(jBtnNH);
    }//GEN-LAST:event_jBtnNHMouseExited

    private void jBtnNHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNHMousePressed
        // TODO add your handling code here:
        resetColor(jBtnNH);
    }//GEN-LAST:event_jBtnNHMousePressed

    private void jBtnNHMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNHMouseReleased
        // TODO add your handling code here:
        setColor(jBtnNH);
    }//GEN-LAST:event_jBtnNHMouseReleased

    private void jBtnTTGHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTTGHMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTTGH);
    }//GEN-LAST:event_jBtnTTGHMouseEntered

    private void jBtnTTGHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTTGHMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTTGH);
    }//GEN-LAST:event_jBtnTTGHMouseExited

    private void jBtnTTGHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTTGHMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTTGH);
    }//GEN-LAST:event_jBtnTTGHMousePressed

    private void jBtnTTGHMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTTGHMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTTGH);
    }//GEN-LAST:event_jBtnTTGHMouseReleased

    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        // TODO add your handling code here:
        new MainForm((User)).setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLSPMouseClicked
        FormQuanLiLoaiSanPham frmQLLSP = new FormQuanLiLoaiSanPham();
        frmQLLSP.setVisible(true);
    }//GEN-LAST:event_jBtnLSPMouseClicked

    private void jBtnSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSPMouseClicked
        FormQuanLiSanPham frmQLSP = new FormQuanLiSanPham();
        frmQLSP.setVisible(true);
    }//GEN-LAST:event_jBtnSPMouseClicked

    private void jBtnDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDHMouseClicked
        FormQuanLiDonDatHang frmQLDDH = new FormQuanLiDonDatHang();
        frmQLDDH.setVisible(true);
    }//GEN-LAST:event_jBtnDHMouseClicked

    private void jBtnNHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNHMouseClicked
        FormQuanLiPhieuNhap frmQLNH=new FormQuanLiPhieuNhap();
        frmQLNH.setVisible(true);
    }//GEN-LAST:event_jBtnNHMouseClicked

    private void jBtnNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNCCMouseClicked
        FormQuanLiNhaCungCap frmQLNCC = new FormQuanLiNhaCungCap();
        frmQLNCC.setVisible(true);
    }//GEN-LAST:event_jBtnNCCMouseClicked

    private void jBtnTTGHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTTGHMouseClicked
        FormXacNhanTinhTrangGiaoHang frmXNTTGH = new FormXacNhanTinhTrangGiaoHang();
        frmXNTTGH.setVisible(true);
    }//GEN-LAST:event_jBtnTTGHMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLiKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack;
    private javax.swing.JLabel jBtnClose;
    private javax.swing.JPanel jBtnDH;
    private javax.swing.JPanel jBtnLSP;
    private javax.swing.JPanel jBtnNCC;
    private javax.swing.JPanel jBtnNH;
    private javax.swing.JPanel jBtnSP;
    private javax.swing.JPanel jBtnTTGH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
