/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Control.CtrlPhieuChi;
import Control.CtrlQuanLiNhaCungCap;
import Edit.Edit;
import Model.ModPhieuChi;
import Object.ObjNhaCungCap;
import Object.ObjPhieuChi;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Thanh
 */
public class FormQuanLiPhieuChi extends javax.swing.JFrame {

    Edit editFrm=new Edit();
    ArrayList<ObjPhieuChi> listPC = new ArrayList<>();
    ArrayList<ObjNhaCungCap> listNCC =new ArrayList<>();
    ArrayList<String> listCbb=new ArrayList<>();
    CtrlPhieuChi CtrlPC = new CtrlPhieuChi();
    ModPhieuChi modPC=new ModPhieuChi();
    ObjPhieuChi objPC=new ObjPhieuChi();
    ObjNhaCungCap objNCC=new ObjNhaCungCap();
    CtrlQuanLiNhaCungCap CtrlNCC =new CtrlQuanLiNhaCungCap();
    private int flag=0;
    /**
     * Creates new form frmQuanLiPhieuChi
     */
    public FormQuanLiPhieuChi() {
        initComponents();
        setLocationRelativeTo(null);
        
        jPanel9.setBackground(new Color(0,0,0,0));
        
        JPanel ListPanel[]=new JPanel[]{jPanel1,jPanel4,jPanel5,jPanel6,jPanel8};
        editFrm.MakeTransparentPanel(ListPanel);
                
        JPanel ListTitle[]=new JPanel[]{jPnDSNCC,jPnDSPC,jPnThongtinNCC,jPnThongtinPC,jPnTracuuPC};
        editFrm.MakeTransparentTitle(ListTitle);
        
        JPanel ListButton[] = new JPanel[]{jBtnBack,jBtnHuy,jBtnLamMoiNCC,jBtnLamMoiPC,jBtnLuu,jBtnSua,jBtnThem,jBtnTimKiemNCC,jBtnTimKiemPC,jBtnXemPhieuIn,jBtnXoa};
        editFrm.MakeTransparentButton(ListButton);
 
        editFrm.MakeTransparentTable(jScrDSPC, jTbDSPC);
        editFrm.MakeTransparentTable(jScrDSNCC, jTbDSNCC);
        LoadForm();
    }
    public FormQuanLiPhieuChi(String MaPC, String TenNCC, Date NgayChi){
        initComponents();
        setLocationRelativeTo(null);
        
        jPanel9.setBackground(new Color(0,0,0,0));
        
        JPanel ListPanel[]=new JPanel[]{jPanel1,jPanel4,jPanel5,jPanel6,jPanel8};
        editFrm.MakeTransparentPanel(ListPanel);
                
        JPanel ListTitle[]=new JPanel[]{jPnDSNCC,jPnDSPC,jPnThongtinNCC,jPnThongtinPC,jPnTracuuPC};
        editFrm.MakeTransparentTitle(ListTitle);
        
        JPanel ListButton[] = new JPanel[]{jBtnBack,jBtnHuy,jBtnLamMoiNCC,jBtnLamMoiPC,jBtnLuu,jBtnSua,jBtnThem,jBtnTimKiemNCC,jBtnTimKiemPC,jBtnXemPhieuIn,jBtnXoa};
        editFrm.MakeTransparentButton(ListButton);
 
        editFrm.MakeTransparentTable(jScrDSPC, jTbDSPC);
        editFrm.MakeTransparentTable(jScrDSNCC, jTbDSNCC);
        LoadForm();
        jDCNgayChi.setDate(NgayChi);
        try{
            DefaultTableModel Model = (DefaultTableModel) jTbDSPC.getModel();
            for(int i =0; i<listPC.size();i++){
                this.listPC.add(listPC.get(i));
                Vector v = new Vector();
                v.add(listPC.get(i).getNgayChi());
                v.add(listPC.get(i).getMaPC());
                v.add(listPC.get(i).getMaNCC());
                Model.addRow(v);
            } 
        }catch(Exception ex){
            System.out.println("Ngoại lệ tại FormPhieuChi():"+ex.getMessage());
        }
        
        try{
            DefaultTableModel Model = (DefaultTableModel) jTbDSNCC.getModel();
            for(int i =0; i<listNCC.size();i++){
                this.listNCC.add(listNCC.get(i));
                Vector v = new Vector();
                v.add(listNCC.get(i).getMaNCC());
                v.add(listNCC.get(i).getTenNCC());
                Model.addRow(v);
            } 
        }catch(Exception ex){
            System.out.println("Ngoại lệ tại FormPhieuChi():"+ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnBack = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jBtnTimKiemPC = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jBtnLamMoiPC = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jBtnXoa = new javax.swing.JPanel();
        jlblXoa = new javax.swing.JLabel();
        jBtnLuu = new javax.swing.JPanel();
        jlblLuu = new javax.swing.JLabel();
        jBtnThem = new javax.swing.JPanel();
        jlblThem = new javax.swing.JLabel();
        jBtnHuy = new javax.swing.JPanel();
        jlblHuy = new javax.swing.JLabel();
        jBtnXemPhieuIn = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jBtnSua = new javax.swing.JPanel();
        jlblSua = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDCTuNgay = new com.toedter.calendar.JDateChooser();
        jDCDenNgay = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jcbbTimTheo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jtxtTimKiem = new javax.swing.JTextField();
        jPnTracuuPC = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxtMaPC = new javax.swing.JTextField();
        jtxtTongTienChi = new javax.swing.JTextField();
        jDCNgayChi = new com.toedter.calendar.JDateChooser();
        jtxtMaNCC2 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtxtLyDoChi = new javax.swing.JTextArea();
        jPnThongtinPC = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtMaNCC = new javax.swing.JTextField();
        jtxtSDT = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jtxtTienNoNCC = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtxtTenNCC = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtxtDiaChi = new javax.swing.JTextArea();
        jPnThongtinNCC = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrDSNCC = new javax.swing.JScrollPane();
        jTbDSNCC = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jtxtTimNCC = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPnDSNCC = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtnLamMoiNCC = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jBtnTimKiemNCC = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCB1 = new javax.swing.JCheckBox();
        jScrDSPC = new javax.swing.JScrollPane();
        jTbDSPC = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPnDSPC = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBackMouseReleased(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBackLayout = new javax.swing.GroupLayout(jBtnBack);
        jBtnBack.setLayout(jBtnBackLayout);
        jBtnBackLayout.setHorizontalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBackLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBtnBackLayout.setVerticalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jBtnTimKiemPC.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTimKiemPC.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnTimKiemPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTimKiemPCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTimKiemPCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTimKiemPCMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTimKiemPCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTimKiemPCMouseReleased(evt);
            }
        });

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_27px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnTimKiemPCLayout = new javax.swing.GroupLayout(jBtnTimKiemPC);
        jBtnTimKiemPC.setLayout(jBtnTimKiemPCLayout);
        jBtnTimKiemPCLayout.setHorizontalGroup(
            jBtnTimKiemPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTimKiemPCLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jBtnTimKiemPCLayout.setVerticalGroup(
            jBtnTimKiemPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnTimKiemPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 250, 120, 30));

        jBtnLamMoiPC.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLamMoiPC.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnLamMoiPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLamMoiPCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLamMoiPCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLamMoiPCMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLamMoiPCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLamMoiPCMouseReleased(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Refresh_27px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLamMoiPCLayout = new javax.swing.GroupLayout(jBtnLamMoiPC);
        jBtnLamMoiPC.setLayout(jBtnLamMoiPCLayout);
        jBtnLamMoiPCLayout.setHorizontalGroup(
            jBtnLamMoiPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLamMoiPCLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jBtnLamMoiPCLayout.setVerticalGroup(
            jBtnLamMoiPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnLamMoiPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 250, 120, 30));

        jBtnXoa.setBackground(new java.awt.Color(204, 204, 204));
        jBtnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXoaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseReleased(evt);
            }
        });

        jlblXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Subtract_55px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnXoaLayout = new javax.swing.GroupLayout(jBtnXoa);
        jBtnXoa.setLayout(jBtnXoaLayout);
        jBtnXoaLayout.setHorizontalGroup(
            jBtnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlblXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnXoaLayout.setVerticalGroup(
            jBtnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoaLayout.createSequentialGroup()
                .addComponent(jlblXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 650, 120, -1));

        jBtnLuu.setBackground(new java.awt.Color(204, 204, 204));
        jBtnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLuuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseReleased(evt);
            }
        });

        jlblLuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Save_55px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLuuLayout = new javax.swing.GroupLayout(jBtnLuu);
        jBtnLuu.setLayout(jBtnLuuLayout);
        jBtnLuuLayout.setHorizontalGroup(
            jBtnLuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLuuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlblLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnLuuLayout.setVerticalGroup(
            jBtnLuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLuuLayout.createSequentialGroup()
                .addComponent(jlblLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 650, 120, -1));

        jBtnThem.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThemMouseReleased(evt);
            }
        });

        jlblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Plus_Math_55px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnThemLayout = new javax.swing.GroupLayout(jBtnThem);
        jBtnThem.setLayout(jBtnThemLayout);
        jBtnThemLayout.setHorizontalGroup(
            jBtnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThemLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlblThem, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jBtnThemLayout.setVerticalGroup(
            jBtnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblThem, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 650, 120, 70));

        jBtnHuy.setBackground(new java.awt.Color(204, 204, 204));
        jBtnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnHuyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseReleased(evt);
            }
        });

        jlblHuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reply_Arrow_64px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnHuyLayout = new javax.swing.GroupLayout(jBtnHuy);
        jBtnHuy.setLayout(jBtnHuyLayout);
        jBtnHuyLayout.setHorizontalGroup(
            jBtnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuyLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlblHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jBtnHuyLayout.setVerticalGroup(
            jBtnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuyLayout.createSequentialGroup()
                .addComponent(jlblHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 650, 120, -1));

        jBtnXemPhieuIn.setBackground(new java.awt.Color(204, 204, 204));
        jBtnXemPhieuIn.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXemPhieuIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuInMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuInMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXemPhieuInMouseReleased(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Print_60px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnXemPhieuInLayout = new javax.swing.GroupLayout(jBtnXemPhieuIn);
        jBtnXemPhieuIn.setLayout(jBtnXemPhieuInLayout);
        jBtnXemPhieuInLayout.setHorizontalGroup(
            jBtnXemPhieuInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXemPhieuInLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnXemPhieuInLayout.setVerticalGroup(
            jBtnXemPhieuInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnXemPhieuIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 650, 120, 70));

        jBtnSua.setBackground(new java.awt.Color(204, 204, 204));
        jBtnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnSuaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseReleased(evt);
            }
        });

        jlblSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Edit_48px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnSuaLayout = new javax.swing.GroupLayout(jBtnSua);
        jBtnSua.setLayout(jBtnSuaLayout);
        jBtnSuaLayout.setHorizontalGroup(
            jBtnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnSuaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlblSua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jBtnSuaLayout.setVerticalGroup(
            jBtnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnSuaLayout.createSequentialGroup()
                .addComponent(jlblSua, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 650, 120, -1));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setText("Từ ngày :");

        jLabel8.setText("Đến ngày :");

        jLabel9.setText("Tìm theo :");

        jcbbTimTheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã phiếu chi", "Mã nhà cung cấp", "Tìm theo ngày" }));
        jcbbTimTheo.setFocusable(false);

        jLabel10.setText("Từ khóa :");

        jPnTracuuPC.setBackground(new java.awt.Color(0, 204, 204));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Tra cứu phiếu chi:");

        javax.swing.GroupLayout jPnTracuuPCLayout = new javax.swing.GroupLayout(jPnTracuuPC);
        jPnTracuuPC.setLayout(jPnTracuuPCLayout);
        jPnTracuuPCLayout.setHorizontalGroup(
            jPnTracuuPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTracuuPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPnTracuuPCLayout.setVerticalGroup(
            jPnTracuuPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbbTimTheo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDCTuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDCDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPnTracuuPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPnTracuuPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDCTuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDCDenNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcbbTimTheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 400, -1));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setText("Mã phiếu chi :");

        jLabel12.setText("Tổng tiền chi :");

        jLabel13.setText("Ngày chi :");

        jLabel14.setText("Mã NCC :");

        jLabel15.setText("Lý do :");

        jtxtLyDoChi.setColumns(20);
        jtxtLyDoChi.setRows(5);
        jScrollPane8.setViewportView(jtxtLyDoChi);

        jPnThongtinPC.setBackground(new java.awt.Color(0, 204, 204));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Thông tin phiếu chi:");

        javax.swing.GroupLayout jPnThongtinPCLayout = new javax.swing.GroupLayout(jPnThongtinPC);
        jPnThongtinPC.setLayout(jPnThongtinPCLayout);
        jPnThongtinPCLayout.setHorizontalGroup(
            jPnThongtinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongtinPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPnThongtinPCLayout.setVerticalGroup(
            jPnThongtinPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(20, 20, 20)
                        .addComponent(jtxtMaPC, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtTongTienChi))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDCNgayChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtMaNCC2)
                            .addComponent(jScrollPane8)))))
            .addComponent(jPnThongtinPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPnThongtinPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtMaPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(jtxtTongTienChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCNgayChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtxtMaNCC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 400, 340));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Mã nhà cung cấp : ");

        jLabel3.setText("Tên nhà cung cấp :");

        jLabel4.setText("Số điện thoại :");

        jLabel5.setText("Địa chỉ :");

        jLabel6.setText("Tiền nợ NCC :");

        jScrollPane3.setViewportView(jTextPane1);

        jtxtTienNoNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTienNoNCCActionPerformed(evt);
            }
        });

        jtxtTenNCC.setColumns(20);
        jtxtTenNCC.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jtxtTenNCC.setRows(5);
        jScrollPane6.setViewportView(jtxtTenNCC);

        jtxtDiaChi.setColumns(20);
        jtxtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jtxtDiaChi.setRows(5);
        jScrollPane7.setViewportView(jtxtDiaChi);

        jPnThongtinNCC.setBackground(new java.awt.Color(0, 204, 204));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Thông tin nhà cung cấp:");

        javax.swing.GroupLayout jPnThongtinNCCLayout = new javax.swing.GroupLayout(jPnThongtinNCC);
        jPnThongtinNCC.setLayout(jPnThongtinNCCLayout);
        jPnThongtinNCCLayout.setHorizontalGroup(
            jPnThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongtinNCCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPnThongtinNCCLayout.setVerticalGroup(
            jPnThongtinNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnThongtinNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtMaNCC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTienNoNCC)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPnThongtinNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTienNoNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 440, 500, -1));

        jTbDSNCC.setAutoCreateRowSorter(true);
        jTbDSNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NCC", "Tên NCC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbDSNCC.setFocusable(false);
        jTbDSNCC.setRowHeight(25);
        jTbDSNCC.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTbDSNCC.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTbDSNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbDSNCCMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTbDSNCCMousePressed(evt);
            }
        });
        jScrDSNCC.setViewportView(jTbDSNCC);
        if (jTbDSNCC.getColumnModel().getColumnCount() > 0) {
            jTbDSNCC.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTbDSNCC.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        getContentPane().add(jScrDSNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 215, 490, 210));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jtxtTimNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 290, 30));

        jLabel18.setText("Từ khóa :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 49, -1));

        jPnDSNCC.setBackground(new java.awt.Color(0, 204, 204));
        jPnDSNCC.setPreferredSize(new java.awt.Dimension(500, 34));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Danh sách nhà cung cấp:");

        javax.swing.GroupLayout jPnDSNCCLayout = new javax.swing.GroupLayout(jPnDSNCC);
        jPnDSNCC.setLayout(jPnDSNCCLayout);
        jPnDSNCCLayout.setHorizontalGroup(
            jPnDSNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSNCCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        jPnDSNCCLayout.setVerticalGroup(
            jPnDSNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPnDSNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jBtnLamMoiNCC.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLamMoiNCC.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnLamMoiNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLamMoiNCCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLamMoiNCCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLamMoiNCCMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLamMoiNCCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLamMoiNCCMouseReleased(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Refresh_27px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLamMoiNCCLayout = new javax.swing.GroupLayout(jBtnLamMoiNCC);
        jBtnLamMoiNCC.setLayout(jBtnLamMoiNCCLayout);
        jBtnLamMoiNCCLayout.setHorizontalGroup(
            jBtnLamMoiNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLamMoiNCCLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jBtnLamMoiNCCLayout.setVerticalGroup(
            jBtnLamMoiNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jBtnLamMoiNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 120, 30));

        jBtnTimKiemNCC.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTimKiemNCC.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnTimKiemNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTimKiemNCCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTimKiemNCCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTimKiemNCCMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTimKiemNCCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTimKiemNCCMouseReleased(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_27px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnTimKiemNCCLayout = new javax.swing.GroupLayout(jBtnTimKiemNCC);
        jBtnTimKiemNCC.setLayout(jBtnTimKiemNCCLayout);
        jBtnTimKiemNCCLayout.setHorizontalGroup(
            jBtnTimKiemNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTimKiemNCCLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jBtnTimKiemNCCLayout.setVerticalGroup(
            jBtnTimKiemNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jBtnTimKiemNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, 30));

        jButton1.setText("Chọn");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jCB1.setText("Tìm theo Mã NCC");
        jPanel1.add(jCB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, 500, 370));

        jTbDSPC.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jTbDSPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày chi", "Mã phiếu chi", "Mã NCC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbDSPC.setFocusable(false);
        jTbDSPC.setRowHeight(25);
        jTbDSPC.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTbDSPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbDSPCMouseClicked(evt);
            }
        });
        jScrDSPC.setViewportView(jTbDSPC);

        getContentPane().add(jScrDSPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(945, 100, 400, 535));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnDSPC.setBackground(new java.awt.Color(0, 204, 204));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Danh sách phiếu chi:");

        javax.swing.GroupLayout jPnDSPCLayout = new javax.swing.GroupLayout(jPnDSPC);
        jPnDSPC.setLayout(jPnDSPCLayout);
        jPnDSPCLayout.setHorizontalGroup(
            jPnDSPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnDSPCLayout.setVerticalGroup(
            jPnDSPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel8.add(jPnDSPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 410, 580));

        jPanel9.setFocusable(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 728));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo-530024.jpeg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jLabel16.setPreferredSize(new java.awt.Dimension(1410, 728));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 728));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void LoadForm(){
        HienThiDanhSachPhieuChi(CtrlPC.LayDanhSachPC());
        HienThiDanhSachNCC(CtrlNCC.LayDSNhaCungCap());
        Binding1();
        Binding2();
        jDCNgayChi.setDate(new Date());
        jDCTuNgay.setDate(new Date());
        jDCDenNgay.setDate(new Date());
        CtrlPC.CloseConnection();
        EnableComponent(true);
    }
    
    public void HienThiDanhSachPhieuChi(ResultSet rs){
        listPC.clear();
        DefaultTableModel model;
        Calendar cal = Calendar.getInstance();

        model=(DefaultTableModel) jTbDSPC.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            while(rs.next()){
                ObjPhieuChi itemPC;
                itemPC=new ObjPhieuChi(rs.getDate("NgayChi"),rs.getString("MaPC"), rs.getString("MaNCC"),rs.getInt("TongTienChi"),rs.getString("LyDoChi"));
                listPC.add(itemPC);
                Vector v =new Vector();
                v.add(itemPC.getNgayChi());
                v.add(itemPC.getMaPC());
                v.add(itemPC.getMaNCC());
                model.addRow(v);
            }
        }catch (SQLException ex){
            System.out.println("Ngoại lệ tại FormPhieuChi.HienThiDanhSachPhieuChi: "+ex.getMessage());
        }
        finally{
            CtrlPC.CloseConnection();
        }
        jTbDSPC.changeSelection(0, 0, false, false);
    }
    
    public void HienThiDanhSachNCC(ResultSet rs){
        listNCC.clear();
        DefaultTableModel model;
        Calendar cal = Calendar.getInstance();

        model=(DefaultTableModel) jTbDSNCC.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            while(rs.next()){
                ObjNhaCungCap itemNCC;
                itemNCC=new ObjNhaCungCap(rs.getString("MaNCC"), rs.getString("TenNCC"),rs.getString("SDT"), rs.getString("DiaChi"), rs.getString("Email"), rs.getInt("NoCuaDaiLy"));
                listNCC.add(itemNCC);
                Vector v =new Vector();
                v.add(itemNCC.getMaNCC());
                v.add(itemNCC.getTenNCC());
                model.addRow(v);
            }
        }catch (SQLException ex){
            System.out.println("Ngoại lệ tại FormPhieuChi.HienThiDanhSachNCC: "+ex.getMessage());
        }
        finally{
            CtrlNCC.CloseConnection();
        }
        jTbDSNCC.changeSelection(0, 0, false, false);
    }
    
    public void ReloadForm(){
        HienThiDanhSachPhieuChi(CtrlPC.LayDanhSachPC());
        HienThiDanhSachNCC(CtrlNCC.LayDSNhaCungCap());;
        listPC.clear();
        listNCC.clear();
        jtxtTimKiem.setText("");
        jTbDSPC.removeAll();
        jTbDSNCC.removeAll();
        jtxtMaPC.setText(CtrlPC.TaoMaPC());
        jDCNgayChi.setDate(new Date());
        DefaultTableModel model1,model2;
        model1=(DefaultTableModel) jTbDSPC.getModel();
        model2=(DefaultTableModel) jTbDSNCC.getModel();
        model1.getDataVector().removeAllElements(); 
        model1.fireTableDataChanged();
        model2.getDataVector().removeAllElements(); 
        model2.fireTableDataChanged();
    }
    
    public void Binding1(){
        TableModel model = jTbDSPC.getModel();
        try {
            int viewRow = jTbDSPC.getSelectedRow();
            int modelRow = jTbDSPC.convertRowIndexToModel(viewRow);
            jtxtMaPC.setText(listPC.get(modelRow).getMaPC());
            jDCNgayChi.setDate(listPC.get(modelRow).getNgayChi());
            jtxtTongTienChi.setText(String.format("%,d", listPC.get(modelRow).getTongTienChi()));
            jtxtMaNCC2.setText(listPC.get(modelRow).getMaNCC());
            jtxtLyDoChi.setText(listPC.get(modelRow).getLyDoChi());
            
        }catch (Exception ex) {
            System.out.println("Ngoại lệ tại FormPhieuChi.Binding: " + ex.getMessage());
        }
        
    }
    public void Binding2(){
        TableModel model2 = jTbDSNCC.getModel();
        try{
            int viewRow = jTbDSNCC.getSelectedRow();
            int modelRow = jTbDSNCC.convertRowIndexToModel(viewRow);
            jtxtMaNCC.setText(listNCC.get(modelRow).getMaNCC());
            jtxtTenNCC.setText(listNCC.get(modelRow).getTenNCC());
            jtxtDiaChi.setText(listNCC.get(modelRow).getDiaChi());
            jtxtSDT.setText(listNCC.get(modelRow).getSDT());
            jtxtTienNoNCC.setText(String.valueOf(listNCC.get(modelRow).getNoCuaDaiLy()));
            
        }catch (Exception ex) {
            System.out.println("Ngoại lệ tại FormPhieuChi.Binding: " + ex.getMessage());
        }
    }
    
    private void EnableComponent(boolean Active) {
        jBtnLuu.setEnabled(!Active);
        jlblLuu.setEnabled(!Active);
        jBtnHuy.setEnabled(!Active);
        jlblHuy.setEnabled(!Active);
        jtxtMaNCC2.setEnabled(!Active);
        jtxtTongTienChi.setEnabled(!Active);
        jDCNgayChi.setEnabled(!Active);
        jtxtMaPC.setEnabled(!Active);
        jtxtLyDoChi.setEnabled(!Active);
        jtxtMaNCC.setEnabled(!Active);
        jtxtTenNCC.setEnabled(!Active);
        jtxtSDT.setEnabled(!Active);
        jtxtDiaChi.setEnabled(!Active);
        jtxtTienNoNCC.setEnabled(!Active);
        
        jBtnThem.setEnabled(Active);
        jlblThem.setEnabled(Active);
        jBtnXoa.setEnabled(Active);
        jlblXoa.setEnabled(Active);
        jBtnSua.setEnabled(Active);
        jlblSua.setEnabled(Active);
    }
    
    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseEntered

    private void jBtnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseExited

    private void jBtnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMousePressed

    private void jBtnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseReleased

    private void jBtnTimKiemNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemNCCMouseClicked
        try{
            listNCC.clear();
            DefaultTableModel model = (DefaultTableModel) jTbDSNCC.getModel();
            model.getDataVector().removeAllElements();
            Vector v = new Vector();
                    v.add("");
                    v.add("");
            model.addRow(v);
            Resetfield();
            
            if(jCB1.isSelected()){
                HienThiDanhSachNCC(CtrlNCC.SearchNCCByID(jtxtTimNCC.getText()));
            }
            else HienThiDanhSachNCC(CtrlNCC.SearchNCCByName(jtxtTimNCC.getText()));
            
        }catch(Exception e){
            System.out.println("Ngoại lệ tại FormPhieuChi.TimKiem: "+e.getMessage());
        }
    }//GEN-LAST:event_jBtnTimKiemNCCMouseClicked

        

    public void Resetfield() { //reset các trường dữ liệu có trên form
        jtxtMaNCC.setText("");
        jtxtTenNCC.setText("");
        jtxtSDT.setText("");
        jtxtDiaChi.setText("");
        jtxtTienNoNCC.setText("");
    }
        
    private void jBtnTimKiemNCCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemNCCMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTimKiemNCC);
    }//GEN-LAST:event_jBtnTimKiemNCCMouseEntered

    private void jBtnTimKiemNCCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemNCCMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTimKiemNCC);
    }//GEN-LAST:event_jBtnTimKiemNCCMouseExited

    private void jBtnTimKiemNCCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemNCCMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTimKiemNCC);
    }//GEN-LAST:event_jBtnTimKiemNCCMousePressed

    private void jBtnTimKiemNCCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemNCCMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTimKiemNCC);
    }//GEN-LAST:event_jBtnTimKiemNCCMouseReleased

    private void jBtnLamMoiNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiNCCMouseClicked
        // TODO add your handling code here:
        HienThiDanhSachNCC(CtrlNCC.LayDSNhaCungCap());
        jtxtTimNCC.setText("");       
        Binding2();
    }//GEN-LAST:event_jBtnLamMoiNCCMouseClicked

    private void jBtnLamMoiNCCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiNCCMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLamMoiNCC);
    }//GEN-LAST:event_jBtnLamMoiNCCMouseEntered

    private void jBtnLamMoiNCCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiNCCMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLamMoiNCC);
    }//GEN-LAST:event_jBtnLamMoiNCCMouseExited

    private void jBtnLamMoiNCCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiNCCMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLamMoiNCC);
    }//GEN-LAST:event_jBtnLamMoiNCCMousePressed

    private void jBtnLamMoiNCCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiNCCMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLamMoiNCC);
    }//GEN-LAST:event_jBtnLamMoiNCCMouseReleased

    private void jtxtTienNoNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTienNoNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTienNoNCCActionPerformed

    private void jBtnTimKiemPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemPCMouseClicked
        // TODO add your handling code here:
        try{
            listPC.clear();
            DefaultTableModel model = (DefaultTableModel) jTbDSPC.getModel();
            model.getDataVector().removeAllElements();
            Vector v = new Vector();
                    v.add("");
                    v.add("");
                    v.add("");
                    v.add("");
            model.addRow(v);
            Resetfield();
           
            if (jcbbTimTheo.getSelectedItem().toString() == "Mã phiếu chi") {
                HienThiDanhSachPhieuChi(CtrlPC.SearchPhieuChiByID(jtxtTimKiem.getText()));
                Binding1();
            }
            else if(jcbbTimTheo.getSelectedItem().toString() == "Mã nhà cung cấp")
            {
                HienThiDanhSachPhieuChi(CtrlPC.SearchPhieuChiByIDNCC(jtxtTimKiem.getText()));
                Binding1();
            }
            else{
                HienThiDanhSachPhieuChi(CtrlPC.SearchTheoNgay(jDCTuNgay.getDate(),jDCDenNgay.getDate()));
                Binding1();
            }
        }catch(Exception e){
            System.out.println("Ngoại lệ tại FormPhieuThu.TimKiem: "+e.getMessage());
        }
        
    }//GEN-LAST:event_jBtnTimKiemPCMouseClicked

    private void jBtnTimKiemPCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemPCMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTimKiemPC);
    }//GEN-LAST:event_jBtnTimKiemPCMouseEntered

    private void jBtnTimKiemPCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemPCMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTimKiemPC);
    }//GEN-LAST:event_jBtnTimKiemPCMouseExited

    private void jBtnTimKiemPCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemPCMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTimKiemPC);
    }//GEN-LAST:event_jBtnTimKiemPCMousePressed

    private void jBtnTimKiemPCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemPCMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTimKiemPC);
    }//GEN-LAST:event_jBtnTimKiemPCMouseReleased

    private void jBtnLamMoiPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiPCMouseClicked
        // TODO add your handling code here:
        HienThiDanhSachPhieuChi(CtrlPC.LayDanhSachPC());
        
        jtxtTimKiem.setText("");
        
        jDCTuNgay.setDate(null);
        jDCDenNgay.setDate(null);
        Binding1();
    }//GEN-LAST:event_jBtnLamMoiPCMouseClicked

    private void jBtnLamMoiPCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiPCMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLamMoiPC);
    }//GEN-LAST:event_jBtnLamMoiPCMouseEntered

    private void jBtnLamMoiPCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiPCMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLamMoiPC);
    }//GEN-LAST:event_jBtnLamMoiPCMouseExited

    private void jBtnLamMoiPCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiPCMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLamMoiPC);
    }//GEN-LAST:event_jBtnLamMoiPCMousePressed

    private void jBtnLamMoiPCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiPCMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLamMoiPC);
    }//GEN-LAST:event_jBtnLamMoiPCMouseReleased

    private void jBtnXemPhieuInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuInMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemPhieuInMouseClicked

    private void jBtnXemPhieuInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuInMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXemPhieuIn);
    }//GEN-LAST:event_jBtnXemPhieuInMouseEntered

    private void jBtnXemPhieuInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuInMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXemPhieuIn);
    }//GEN-LAST:event_jBtnXemPhieuInMouseExited

    private void jBtnXemPhieuInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuInMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXemPhieuIn);
    }//GEN-LAST:event_jBtnXemPhieuInMousePressed

    private void jBtnXemPhieuInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhieuInMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXemPhieuIn);
    }//GEN-LAST:event_jBtnXemPhieuInMouseReleased

    private void jBtnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMouseEntered

    private void jBtnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMouseExited

    private void jBtnThemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMousePressed

    private void jBtnThemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThem);
    }//GEN-LAST:event_jBtnThemMouseReleased

    private void jBtnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseEntered

    private void jBtnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseExited

    private void jBtnXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMousePressed

    private void jBtnXoaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseReleased

    private void jBtnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseEntered
        // TODO add your handling code here:
        setColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMouseEntered

    private void jBtnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseExited
        // TODO add your handling code here:
        resetColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMouseExited

    private void jBtnSuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMousePressed
        // TODO add your handling code here:
        resetColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMousePressed

    private void jBtnSuaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseReleased
        // TODO add your handling code here:
        setColor(jBtnSua);
    }//GEN-LAST:event_jBtnSuaMouseReleased

    private void jBtnLuuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMouseEntered

    private void jBtnLuuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMouseExited

    private void jBtnLuuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMousePressed

    private void jBtnLuuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLuu);
    }//GEN-LAST:event_jBtnLuuMouseReleased

    private void jBtnHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseEntered
        // TODO add your handling code here:
        setColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseEntered

    private void jBtnHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseExited
        // TODO add your handling code here:
        resetColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseExited

    private void jBtnHuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMousePressed
        // TODO add your handling code here:
        resetColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMousePressed

    private void jBtnHuyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseReleased
        // TODO add your handling code here:
        setColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseReleased

    private void jTbDSNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbDSNCCMouseClicked
        // TODO add your handling code here:
        if(jTbDSNCC.getSelectedRow()>=0)
            Binding2();
    }//GEN-LAST:event_jTbDSNCCMouseClicked

    private void jTbDSNCCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbDSNCCMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTbDSNCCMousePressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        TableModel model2 = jTbDSNCC.getModel();
        try{
            int viewRow = jTbDSNCC.getSelectedRow();
            int modelRow = jTbDSNCC.convertRowIndexToModel(viewRow);
            jtxtMaNCC2.setText(listNCC.get(modelRow).getMaNCC());
        }catch (Exception ex) {
            System.out.println("Ngoại lệ tại FormPhieuChi.Binding: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTbDSPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbDSPCMouseClicked
        // TODO add your handling code here:
        if(jTbDSPC.getSelectedRow()>=0)
            Binding1();
    }//GEN-LAST:event_jTbDSPCMouseClicked

    private void jBtnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThemMouseClicked
        // TODO add your handling code here:
        if(jBtnThem.isEnabled()){
            EnableComponent(false);
           jtxtMaPC.setText(CtrlPC.TaoMaPC());
           jDCNgayChi.setDate(new Date());
           jtxtTongTienChi.setText("");
           jtxtLyDoChi.setText("");
           jtxtMaNCC2.setText("");
           flag=1;
        }
    }//GEN-LAST:event_jBtnThemMouseClicked

    private void jBtnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseClicked
        // TODO add your handling code here:
        if(jBtnHuy.isEnabled()){
           jtxtMaPC.setText("");
           jDCNgayChi.setDate(new Date());
           jtxtTongTienChi.setText("");
           jtxtLyDoChi.setText("");
           EnableComponent(true);
           flag=1;
        }
    }//GEN-LAST:event_jBtnHuyMouseClicked

    private void jBtnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseClicked
        // TODO add your handling code here:
        if(jBtnSua.isEnabled()){
            EnableComponent(false);
            flag=2;
        }
    }//GEN-LAST:event_jBtnSuaMouseClicked

    private void jBtnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseClicked
        // TODO add your handling code here:
        if(jBtnXoa.isEnabled()){
            objPC=new ObjPhieuChi(jtxtMaPC.getText());
            int i= JOptionPane.showConfirmDialog(this, "Bạn muốn xóa phiếu chi \""+ objPC.getMaPC()+ "\"", "Xác nhận", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(i==0){
                try{
                    if(modPC.Delete(objPC.getMaPC()))
                    {
                        EnableComponent(false);
                        JOptionPane.showMessageDialog(this, "Xóa phiếu chi \"" + objPC.getMaPC()+ "\" thành công." , "Thông báo", JOptionPane.INFORMATION_MESSAGE );
                        HienThiDanhSachPhieuChi(CtrlPC.LayDanhSachPC());
                    }
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this, "Xóa phiếu chi \"" + objPC.getMaPC()+ "\" thất bại. Mã lỗi: " + ex.getMessage(), "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jBtnXoaMouseClicked

    private void jBtnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseClicked
        // TODO add your handling code here:
        if(jBtnLuu.isEnabled()){
            if(flag==1){
                int i=Integer.parseInt(jtxtTongTienChi.getText().replace(",",""));
                objPC=new ObjPhieuChi(jDCNgayChi.getDate(),jtxtMaPC.getText(),jtxtMaNCC2.getText(),i, jtxtLyDoChi.getText());
                if(!objPC.getMaPC().equals("")){
                    if(!objPC.getMaNCC().equals("")){
                        try{
                            if(modPC.Insert(objPC)){
                                EnableComponent(false);
                                JOptionPane.showMessageDialog(this, "Thêm phiếu chi \"" + objPC.getMaPC()+ "\" thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                HienThiDanhSachPhieuChi(CtrlPC.LayDanhSachPC());
                            }
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(this, "Thêm phiếu chi\"" + objPC.getMaPC()+ "\" thất bại. Mã: " + e.getMessage(), "Thông báo ", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                flag=0;
            }
            else if(flag==2){
                int i=Integer.parseInt(jtxtTongTienChi.getText().replace(",",""));
                objPC=new ObjPhieuChi(jDCNgayChi.getDate(),jtxtMaPC.getText(),jtxtMaNCC2.getText(),i, jtxtLyDoChi.getText());
                if(!objPC.getMaPC().equals("")){
                    if(!objPC.getMaNCC().equals("")){
                        try{
                            if(modPC.Update(objPC)){
                                EnableComponent(false);
                                JOptionPane.showMessageDialog(this, "Sửa phiếu chi \"" + objPC.getMaPC()+ "\" thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                HienThiDanhSachPhieuChi(CtrlPC.LayDanhSachPC());
                            }
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(this, "Sửa phiếu chi\"" + objPC.getMaPC()+ "\" thất bại. Mã: " + e.getMessage(), "Thông báo ", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                flag=0;
            }
        }
    }//GEN-LAST:event_jBtnLuuMouseClicked

    public void setColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()+1, pn.getHeight()+1);
        pn.setBackground(new Color(60,209,127,50));
        }
    }
    public void resetColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()-1, pn.getHeight()-1);
        pn.setBackground(new Color(153,153,153,180));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiPhieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiPhieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiPhieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiPhieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLiPhieuChi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack;
    private javax.swing.JPanel jBtnHuy;
    private javax.swing.JPanel jBtnLamMoiNCC;
    private javax.swing.JPanel jBtnLamMoiPC;
    private javax.swing.JPanel jBtnLuu;
    private javax.swing.JPanel jBtnSua;
    private javax.swing.JPanel jBtnThem;
    private javax.swing.JPanel jBtnTimKiemNCC;
    private javax.swing.JPanel jBtnTimKiemPC;
    private javax.swing.JPanel jBtnXemPhieuIn;
    private javax.swing.JPanel jBtnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCB1;
    private com.toedter.calendar.JDateChooser jDCDenNgay;
    private com.toedter.calendar.JDateChooser jDCNgayChi;
    private com.toedter.calendar.JDateChooser jDCTuNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPnDSNCC;
    private javax.swing.JPanel jPnDSPC;
    private javax.swing.JPanel jPnThongtinNCC;
    private javax.swing.JPanel jPnThongtinPC;
    private javax.swing.JPanel jPnTracuuPC;
    private javax.swing.JScrollPane jScrDSNCC;
    private javax.swing.JScrollPane jScrDSPC;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTbDSNCC;
    private javax.swing.JTable jTbDSPC;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox<String> jcbbTimTheo;
    private javax.swing.JLabel jlblHuy;
    private javax.swing.JLabel jlblLuu;
    private javax.swing.JLabel jlblSua;
    private javax.swing.JLabel jlblThem;
    private javax.swing.JLabel jlblXoa;
    private javax.swing.JTextArea jtxtDiaChi;
    private javax.swing.JTextArea jtxtLyDoChi;
    private javax.swing.JTextField jtxtMaNCC;
    private javax.swing.JTextField jtxtMaNCC2;
    private javax.swing.JTextField jtxtMaPC;
    private javax.swing.JTextField jtxtSDT;
    private javax.swing.JTextArea jtxtTenNCC;
    private javax.swing.JTextField jtxtTienNoNCC;
    private javax.swing.JTextField jtxtTimKiem;
    private javax.swing.JTextField jtxtTimNCC;
    private javax.swing.JTextField jtxtTongTienChi;
    // End of variables declaration//GEN-END:variables
}
