/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.CtrlLapDonDatHang;
import Edit.Edit;
import Model.ModChiTietDDH;
import Model.ModDonDatHang;
import Object.ObjChiTietDDH;
import Object.ObjDonDatHang;
import Object.ObjSanPham;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JPanel;
import java.awt.Color;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Coldblood
 */
public class FormLapDonDatHang extends javax.swing.JFrame {

    boolean ChinhSua=false;
    Edit editFrm = new Edit();
    
    ArrayList<String>listComboboxNCC=new ArrayList<>();
    ArrayList<ObjSanPham>listSanPhamNCC = new ArrayList<>();
    ArrayList<ObjChiTietDDH>listCTDDH = new ArrayList<>();
    CtrlLapDonDatHang CtrlLapDDH = new CtrlLapDonDatHang();
    ModDonDatHang modDDH = new ModDonDatHang();
    ModChiTietDDH modCTDDH = new ModChiTietDDH();
    /**
     * Creates new form FormLapDonDatHang
     */ 
    public FormLapDonDatHang() {
        initComponents();
        setLocationRelativeTo(null);
        
        JPanel ListPn[]=new JPanel[]{jPanel3,jPanel4,jPanel5,jPanel6,jPanel7};
        editFrm.MakeTransparentPanel(ListPn);
        
        JPanel ListTitle[]=new JPanel[]{jPnDSDH,jPnDSSP,jPnThongTinCTNH,jPnThongtinDDH,jPnTimKiem};
        editFrm.MakeTransparentTitle(ListTitle);
        
        JPanel ListButton[] = new JPanel[]{jBtnBack,jBtnDathang,jBtnHuy,jBtnLamMoi,jBtnTimKiem,jBtnXoa,jbtnDuyetDonHang,jBtnChinhSua,jBtnIn};
        editFrm.MakeTransparentButton(ListButton);
        
        editFrm.MakeTransparentTable(jScrDSSP, jtbDSSP);
        editFrm.MakeTransparentTable(jScrDSDH, jTbDSDH); 
        
        LoadForm();
    }

    public FormLapDonDatHang(ObjDonDatHang objDDH,ArrayList<ObjChiTietDDH> CTDDH) {
        initComponents();
        setLocationRelativeTo(null);
        
        JPanel ListPn[]=new JPanel[]{jPanel3,jPanel4,jPanel5,jPanel6,jPanel7};
        editFrm.MakeTransparentPanel(ListPn);
        
        JPanel ListTitle[]=new JPanel[]{jPnDSDH,jPnDSSP,jPnThongTinCTNH,jPnThongtinDDH,jPnTimKiem};
        editFrm.MakeTransparentTitle(ListTitle);
        
        JPanel ListButton[] = new JPanel[]{jBtnBack,jBtnDathang,jBtnHuy,jBtnLamMoi,jBtnTimKiem,jBtnXoa,jbtnDuyetDonHang,jBtnChinhSua,jBtnIn};
        editFrm.MakeTransparentButton(ListButton);
        
        editFrm.MakeTransparentTable(jScrDSSP, jtbDSSP);
        editFrm.MakeTransparentTable(jScrDSDH, jTbDSDH); 
        
        LoadForm();
        jtxtMaDDH.setText(objDDH.getMaDDH());
        jcbbNhaCungCap.setSelectedItem(objDDH.getTenNCC());
        jtxtMaNCC.setText(objDDH.getMaNCC());
        jDateNgayDat.setDate(objDDH.getNgayDatHang());
        jcbbNhaCungCap.setEnabled(false);
        jBtnHuy.setVisible(false);
        
        try{        
            DefaultTableModel Model = (DefaultTableModel) jTbDSDH.getModel();
            for(int i = 0;i<CTDDH.size();i++){
                 listCTDDH.add(CTDDH.get(i));
                 Vector v = new Vector();
                 v.add(listCTDDH.get(i).getMaSP());
                 v.add(listCTDDH.get(i).getTenSP());
                 v.add(listCTDDH.get(i).getDVT());
                 v.add(listCTDDH.get(i).getSoLuong());
                 Model.addRow(v);    
            }
       }
       catch(Exception ex){
           System.out.println("Ngoại lệ tại FormLapHoaDonSi():"+ex.getMessage());
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnBack = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jbtnDuyetDonHang = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jBtnIn = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jBtnHuy = new javax.swing.JPanel();
        jlbHuyDDH = new javax.swing.JLabel();
        jBtnHuy1 = new javax.swing.JPanel();
        jlbHuyDDH1 = new javax.swing.JLabel();
        jBtnDathang = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jBtnXoa = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jBtnTimKiem = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jBtnLamMoi = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jBtnChinhSua = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jcbbTimtheo = new javax.swing.JComboBox<>();
        jtxtTimkiem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPnTimKiem = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrDSDH = new javax.swing.JScrollPane();
        jTbDSDH = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPnDSDH = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxtTenSP = new javax.swing.JTextField();
        jSpSoLuong = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jPnThongTinCTNH = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtxtLoaiSP = new javax.swing.JTextField();
        jScrDSSP = new javax.swing.JScrollPane();
        jtbDSSP = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPnDSSP = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbbNhaCungCap = new javax.swing.JComboBox<>();
        jtxtMaDDH = new javax.swing.JTextField();
        jDateNgayDat = new com.toedter.calendar.JDateChooser();
        jPnThongtinDDH = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxtMaNCC = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBackMouseReleased(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBackLayout = new javax.swing.GroupLayout(jBtnBack);
        jBtnBack.setLayout(jBtnBackLayout);
        jBtnBackLayout.setHorizontalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBackLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBtnBackLayout.setVerticalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBackLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jbtnDuyetDonHang.setBackground(new java.awt.Color(153, 153, 153));
        jbtnDuyetDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnDuyetDonHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnDuyetDonHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnDuyetDonHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnDuyetDonHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbtnDuyetDonHangMouseReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Tick_Box_40px.png"))); // NOI18N
        jLabel22.setText("Duyệt đơn hàng");

        javax.swing.GroupLayout jbtnDuyetDonHangLayout = new javax.swing.GroupLayout(jbtnDuyetDonHang);
        jbtnDuyetDonHang.setLayout(jbtnDuyetDonHangLayout);
        jbtnDuyetDonHangLayout.setHorizontalGroup(
            jbtnDuyetDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbtnDuyetDonHangLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jbtnDuyetDonHangLayout.setVerticalGroup(
            jbtnDuyetDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jbtnDuyetDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 665, 190, 50));

        jBtnIn.setBackground(new java.awt.Color(153, 153, 153));
        jBtnIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnInMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnInMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnInMouseReleased(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Print_45px.png"))); // NOI18N
        jLabel23.setText("Xem phiếu in");

        javax.swing.GroupLayout jBtnInLayout = new javax.swing.GroupLayout(jBtnIn);
        jBtnIn.setLayout(jBtnInLayout);
        jBtnInLayout.setHorizontalGroup(
            jBtnInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnInLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jBtnInLayout.setVerticalGroup(
            jBtnInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 665, 190, 50));

        jBtnHuy.setBackground(new java.awt.Color(153, 153, 153));
        jBtnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnHuyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnHuyMouseReleased(evt);
            }
        });

        jlbHuyDDH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbHuyDDH.setForeground(new java.awt.Color(255, 255, 255));
        jlbHuyDDH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbHuyDDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Close_Window_40px.png"))); // NOI18N
        jlbHuyDDH.setText("Hủy đơn hàng");

        javax.swing.GroupLayout jBtnHuyLayout = new javax.swing.GroupLayout(jBtnHuy);
        jBtnHuy.setLayout(jBtnHuyLayout);
        jBtnHuyLayout.setHorizontalGroup(
            jBtnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuyLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlbHuyDDH, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnHuyLayout.setVerticalGroup(
            jBtnHuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHuyDDH, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 665, 190, 50));

        jBtnHuy1.setBackground(new java.awt.Color(153, 153, 153));
        jBtnHuy1.setOpaque(false);
        jBtnHuy1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnHuy1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnHuy1MouseReleased(evt);
            }
        });

        jlbHuyDDH1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbHuyDDH1.setForeground(new java.awt.Color(255, 255, 255));
        jlbHuyDDH1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbHuyDDH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Close_Window_40px.png"))); // NOI18N
        jlbHuyDDH1.setText("Hủy đơn hàng");
        jlbHuyDDH1.setEnabled(false);

        javax.swing.GroupLayout jBtnHuy1Layout = new javax.swing.GroupLayout(jBtnHuy1);
        jBtnHuy1.setLayout(jBtnHuy1Layout);
        jBtnHuy1Layout.setHorizontalGroup(
            jBtnHuy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnHuy1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlbHuyDDH1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jBtnHuy1Layout.setVerticalGroup(
            jBtnHuy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHuyDDH1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnHuy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 665, 190, 50));

        jBtnDathang.setBackground(new java.awt.Color(153, 153, 153));
        jBtnDathang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDathangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDathangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDathangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnDathangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnDathangMouseReleased(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Add_Shopping_Cart_40px.png"))); // NOI18N
        jLabel24.setText("Đặt hàng");

        javax.swing.GroupLayout jBtnDathangLayout = new javax.swing.GroupLayout(jBtnDathang);
        jBtnDathang.setLayout(jBtnDathangLayout);
        jBtnDathangLayout.setHorizontalGroup(
            jBtnDathangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDathangLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jBtnDathangLayout.setVerticalGroup(
            jBtnDathangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnDathang, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 665, 190, 50));

        jBtnXoa.setBackground(new java.awt.Color(153, 153, 153));
        jBtnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXoaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXoaMouseReleased(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Clear_Shopping_Cart_40px.png"))); // NOI18N
        jLabel26.setText("  Xóa");

        javax.swing.GroupLayout jBtnXoaLayout = new javax.swing.GroupLayout(jBtnXoa);
        jBtnXoa.setLayout(jBtnXoaLayout);
        jBtnXoaLayout.setHorizontalGroup(
            jBtnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnXoaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jBtnXoaLayout.setVerticalGroup(
            jBtnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 665, 190, 50));

        jBtnTimKiem.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTimKiem.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMouseReleased(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnTimKiemLayout = new javax.swing.GroupLayout(jBtnTimKiem);
        jBtnTimKiem.setLayout(jBtnTimKiemLayout);
        jBtnTimKiemLayout.setHorizontalGroup(
            jBtnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTimKiemLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jBtnTimKiemLayout.setVerticalGroup(
            jBtnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 175, 165, 65));

        jBtnLamMoi.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLamMoi.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLamMoiMouseReleased(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Refresh_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLamMoiLayout = new javax.swing.GroupLayout(jBtnLamMoi);
        jBtnLamMoi.setLayout(jBtnLamMoiLayout);
        jBtnLamMoiLayout.setHorizontalGroup(
            jBtnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLamMoiLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jBtnLamMoiLayout.setVerticalGroup(
            jBtnLamMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1034, 175, 165, 65));

        jBtnChinhSua.setBackground(new java.awt.Color(204, 204, 204));
        jBtnChinhSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnChinhSuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnChinhSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnChinhSuaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnChinhSuaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnChinhSuaMouseReleased(evt);
            }
        });

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Edit_20px_1.png"))); // NOI18N

        javax.swing.GroupLayout jBtnChinhSuaLayout = new javax.swing.GroupLayout(jBtnChinhSua);
        jBtnChinhSua.setLayout(jBtnChinhSuaLayout);
        jBtnChinhSuaLayout.setHorizontalGroup(
            jBtnChinhSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnChinhSuaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jBtnChinhSuaLayout.setVerticalGroup(
            jBtnChinhSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Tìm theo :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 51, -1, -1));

        jcbbTimtheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên sản phẩm", "Mã sản phẩm" }));
        jcbbTimtheo.setFocusable(false);
        jPanel4.add(jcbbTimtheo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 48, 232, -1));
        jPanel4.add(jtxtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 86, 350, -1));

        jLabel8.setText("Từ tìm kiếm :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 89, -1, -1));

        jPnTimKiem.setBackground(new java.awt.Color(0, 204, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tìm kiếm :");

        javax.swing.GroupLayout jPnTimKiemLayout = new javax.swing.GroupLayout(jPnTimKiem);
        jPnTimKiem.setLayout(jPnTimKiemLayout);
        jPnTimKiemLayout.setHorizontalGroup(
            jPnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(439, Short.MAX_VALUE))
        );
        jPnTimKiemLayout.setVerticalGroup(
            jPnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel4.add(jPnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 510, 190));

        jTbDSDH.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jTbDSDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "ĐVT", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbDSDH.setFocusable(false);
        jTbDSDH.setRowHeight(25);
        jTbDSDH.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTbDSDH.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrDSDH.setViewportView(jTbDSDH);
        if (jTbDSDH.getColumnModel().getColumnCount() > 0) {
            jTbDSDH.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTbDSDH.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTbDSDH.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTbDSDH.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        getContentPane().add(jScrDSDH, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 295, 690, 350));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnDSDH.setBackground(new java.awt.Color(0, 204, 204));
        jPnDSDH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Danh sách đặt hàng :");
        jPnDSDH.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel7.add(jPnDSDH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 700, 390));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("Tên sản phẩm :");

        jtxtTenSP.setEditable(false);

        jLabel6.setText("Số lượng :");

        jPnThongTinCTNH.setBackground(new java.awt.Color(0, 204, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Thông tin chi tiết nhập hàng :");

        javax.swing.GroupLayout jPnThongTinCTNHLayout = new javax.swing.GroupLayout(jPnThongTinCTNH);
        jPnThongTinCTNH.setLayout(jPnThongTinCTNHLayout);
        jPnThongTinCTNHLayout.setHorizontalGroup(
            jPnThongTinCTNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnThongTinCTNHLayout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPnThongTinCTNHLayout.setVerticalGroup(
            jPnThongTinCTNHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel17.setText("Loại sản phẩm :");

        jtxtLoaiSP.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnThongTinCTNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPnThongTinCTNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtxtLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 510, 130));

        jtbDSSP.setAutoCreateRowSorter(true);
        jtbDSSP.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jtbDSSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "ĐVT", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDSSP.setFocusable(false);
        jtbDSSP.setRowHeight(25);
        jtbDSSP.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jtbDSSP.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbDSSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDSSPMouseClicked(evt);
            }
        });
        jScrDSSP.setViewportView(jtbDSSP);
        if (jtbDSSP.getColumnModel().getColumnCount() > 0) {
            jtbDSSP.getColumnModel().getColumn(0).setPreferredWidth(60);
            jtbDSSP.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtbDSSP.getColumnModel().getColumn(2).setPreferredWidth(50);
            jtbDSSP.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        getContentPane().add(jScrDSSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 295, 500, 210));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnDSSP.setBackground(new java.awt.Color(0, 204, 204));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Danh sách sản phẩm của nhà cung cấp :");

        javax.swing.GroupLayout jPnDSSPLayout = new javax.swing.GroupLayout(jPnDSSP);
        jPnDSSP.setLayout(jPnDSSPLayout);
        jPnDSSPLayout.setHorizontalGroup(
            jPnDSSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPnDSSPLayout.setVerticalGroup(
            jPnDSSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel6.add(jPnDSSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 510, 250));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Mã đơn đặt hàng :");

        jLabel2.setText("Nhà cung cấp :");

        jLabel3.setText("Ngày đặt hàng");

        jcbbNhaCungCap.setFocusable(false);
        jcbbNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbNhaCungCapActionPerformed(evt);
            }
        });

        jtxtMaDDH.setEditable(false);

        jDateNgayDat.setDateFormatString("dd/MM/yyyy");

        jPnThongtinDDH.setBackground(new java.awt.Color(0, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Thông tin đơn đặt hàng :");

        javax.swing.GroupLayout jPnThongtinDDHLayout = new javax.swing.GroupLayout(jPnThongtinDDH);
        jPnThongtinDDH.setLayout(jPnThongtinDDHLayout);
        jPnThongtinDDHLayout.setHorizontalGroup(
            jPnThongtinDDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongtinDDHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnThongtinDDHLayout.setVerticalGroup(
            jPnThongtinDDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel16.setText("Mã nhà cung cấp :");

        jtxtMaNCC.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnThongtinDDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(jtxtMaDDH, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(jcbbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateNgayDat, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jtxtMaNCC))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPnThongtinDDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtMaDDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtxtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateNgayDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 700, 190));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 728));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo-530024.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 728));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void LoadComboboxNhaCungCap(){
        listComboboxNCC.clear();
        jcbbNhaCungCap.removeAllItems();
        jcbbNhaCungCap.addItem("---Chọn nhà cung cấp cần đặt hàng---");
        listComboboxNCC.add("");
        ResultSet rs=CtrlLapDDH.LayDanhSachNhaCungCap();
        try{
            if(rs!=null){
            while(rs.next()){
                jcbbNhaCungCap.addItem(rs.getString("TenNCC"));
                listComboboxNCC.add(rs.getString("MaNCC"));
            }
            }
        }
        catch(SQLException ex){
            System.out.println("Ngoại lệ tại FormLapDonDatHang.LoadComboboxNhaCungCap "+ex.getMessage());
        }
        finally{
           CtrlLapDDH.CloseConnection();
        }
    }
    
    public void HienThiDanhSachSanPhamNCC(ResultSet rs){
        try{
            listSanPhamNCC.clear();
             DefaultTableModel model = (DefaultTableModel) jtbDSSP.getModel();
             model.getDataVector().removeAllElements();
             model.fireTableDataChanged();
             while(rs.next()){
                 ObjSanPham itemSP = new ObjSanPham(rs.getString("MaSP"), rs.getString("TenSP"),rs.getString("TenLoaiSP"),rs.getString("DVT"),(int) Double.parseDouble(rs.getString("SoLuong")));
                 listSanPhamNCC.add(itemSP);
                 Vector v = new Vector();
                 v.add(itemSP.getMaSP());
                 v.add(itemSP.getTenSP());
                 v.add(itemSP.getDVT());
                 v.add(itemSP.getSoLuong());
                 model.addRow(v);
             }
             jtbDSSP.changeSelection(0, 0, false, false);
             Binding();
        } catch (SQLException ex) {
            System.out.println("Ngoại lệ tại FormLapDonDatHang: "+ex.getMessage());
        }
    }
    
    public void Binding(){
        try {
            DefaultTableModel Model = (DefaultTableModel) jtbDSSP.getModel();
            int viewRow = jtbDSSP.getSelectedRow();
            int modelRow = jtbDSSP.convertRowIndexToModel(viewRow);
            jtxtTenSP.setText(listSanPhamNCC.get(modelRow).getTenSP());
            jtxtLoaiSP.setText(listSanPhamNCC.get(modelRow).getTenLoaiSP());
        }
        catch(Exception ex){
            System.out.println("Ngoại lệ tại FormLapDonDatHang.Binding:"+ex.getMessage());
        }
    }
    
    public void LoadForm(){
        jDateNgayDat.setDate(new Date());
        jSpSoLuong.setValue(1);
        jtxtMaDDH.setText(CtrlLapDDH.LayMaDDH());
        LoadComboboxNhaCungCap();
        jBtnIn.setVisible(false);
    }
    
    public void ReloadForm(){
        jDateNgayDat.setDate(new Date());
        LoadComboboxNhaCungCap();  
        listCTDDH.clear();
        listSanPhamNCC.clear();
        jtxtMaNCC.setText("");
        jtxtMaDDH.setText(CtrlLapDDH.LayMaDDH());
        DefaultTableModel model;
        HienThiDanhSachSanPhamNCC(CtrlLapDDH.LayDanhSachSanPhamNCC(listComboboxNCC.get(jcbbNhaCungCap.getSelectedIndex())));
        model=(DefaultTableModel) jTbDSDH.getModel();
        model.getDataVector().removeAllElements(); 
        model.fireTableDataChanged();
    }
    
    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        // TODO add your handling code here:
        new FormQuanLiDonDatHang().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseEntered

    private void jBtnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseExited

    private void jBtnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMousePressed

    private void jBtnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseReleased

    private void jBtnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseClicked
        // TODO add your handling code here:
        if(jcbbTimtheo.getSelectedIndex()==0)
        HienThiDanhSachSanPhamNCC(CtrlLapDDH.SearchSanPhamByName(jtxtTimkiem.getText(),jtxtMaNCC.getText()));
        else
        HienThiDanhSachSanPhamNCC(CtrlLapDDH.SearchSanPhamByName(jtxtTimkiem.getText(),jtxtMaNCC.getText()));
        Binding();
    }//GEN-LAST:event_jBtnTimKiemMouseClicked

    private void jBtnTimKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMouseEntered

    private void jBtnTimKiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMouseExited

    private void jBtnTimKiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMousePressed

    private void jBtnTimKiemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTimKiem);
    }//GEN-LAST:event_jBtnTimKiemMouseReleased

    private void jBtnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseClicked
        // TODO add your handling code here:
        HienThiDanhSachSanPhamNCC(CtrlLapDDH.LayDanhSachSanPhamNCC(jtxtMaNCC.getText()));
        jcbbTimtheo.setSelectedIndex(0);
        jtxtTimkiem.setText("");
    }//GEN-LAST:event_jBtnLamMoiMouseClicked

    private void jBtnLamMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMouseEntered

    private void jBtnLamMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMouseExited

    private void jBtnLamMoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMousePressed

    private void jBtnLamMoiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoiMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLamMoi);
    }//GEN-LAST:event_jBtnLamMoiMouseReleased

    private void jBtnDathangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDathangMouseClicked
        // TODO add your handling code here:
        boolean exist = false;
        try{
            DefaultTableModel Model;
            int viewRow = jtbDSSP.getSelectedRow();
            int modelRow = jtbDSSP.convertRowIndexToModel(viewRow);
            Model = (DefaultTableModel) jTbDSDH.getModel();
            ObjChiTietDDH itemCTDDH = new ObjChiTietDDH(jtxtMaDDH.getText(),listSanPhamNCC.get(modelRow).getMaSP(), listSanPhamNCC.get(modelRow).getTenSP(), Integer.parseInt(jSpSoLuong.getValue() + ""), listSanPhamNCC.get(modelRow).getDVT());
            for (int i = 0; i < jTbDSDH.getRowCount(); i++) {
                if (Model.getValueAt(i, 0).equals(itemCTDDH.getMaSP())) {
                    exist = true;
                    int SL = itemCTDDH.getSoLuong() + Integer.parseInt(Model.getValueAt(i, 3).toString());
                    Model.setValueAt(SL, i, 3);
                    listCTDDH.get(i).setSoLuong(SL);
                    break;
                }
            }
            if (!exist) {
                listCTDDH.add(itemCTDDH);
                Vector v = new Vector();
                v.add(itemCTDDH.getMaSP());
                v.add(itemCTDDH.getTenSP());
                v.add(itemCTDDH.getDVT());
                v.add(itemCTDDH.getSoLuong());
                Model.addRow(v);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Không có sản phẩm được chọn.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnDathangMouseClicked

    private void jBtnDathangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDathangMouseEntered
        // TODO add your handling code here:
        setColor(jBtnDathang);
    }//GEN-LAST:event_jBtnDathangMouseEntered

    private void jBtnDathangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDathangMouseExited
        // TODO add your handling code here:
        resetColor(jBtnDathang);
    }//GEN-LAST:event_jBtnDathangMouseExited

    private void jBtnDathangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDathangMousePressed
        // TODO add your handling code here:
        resetColor(jBtnDathang);
    }//GEN-LAST:event_jBtnDathangMousePressed

    private void jBtnDathangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDathangMouseReleased
        // TODO add your handling code here:
        setColor(jBtnDathang);
    }//GEN-LAST:event_jBtnDathangMouseReleased

    private void jBtnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseClicked
        // TODO add your handling code here
        DefaultTableModel Model=(DefaultTableModel) jTbDSDH.getModel() ;
        try{
        int viewRow = jTbDSDH.getSelectedRow();
        int modelRow= jTbDSDH.convertRowIndexToModel(viewRow);
        listCTDDH.remove(modelRow);
        Model.removeRow(modelRow);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Không có sản phẩm được chọn.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_jBtnXoaMouseClicked

    private void jBtnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseEntered

    private void jBtnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseExited

    private void jBtnXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMousePressed

    private void jBtnXoaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXoa);
    }//GEN-LAST:event_jBtnXoaMouseReleased

    private void jbtnDuyetDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDuyetDonHangMouseClicked
        // TODO add your handling code here:
        
        if (!jtxtMaNCC.getText().equals("")) {
            if (listCTDDH.size() > 0) {
                ObjDonDatHang objDDH = new ObjDonDatHang(jtxtMaDDH.getText(), jtxtMaNCC.getText(), jDateNgayDat.getDate(), "Chưa nhận");
                if (!ChinhSua) {
                    try {
                        if (modDDH.Insert(objDDH)) {
                            for (int i = 0; i < listCTDDH.size(); i++) {
                                if (!modCTDDH.Insert(listCTDDH.get(i))) {
                                    JOptionPane.showMessageDialog(this, "Sản phẩm có mã " + listCTDDH.get(i).getMaSP() + " lưu không thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                }
                            }
//                    EnableComponent(false);
                            JOptionPane.showMessageDialog(this, "Đơn đặt hàng " + objDDH.getMaDDH() + " lưu thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                            jbtnDuyetDonHang.setVisible(false);
                            jBtnIn.setVisible(true);
                            jBtnHuy.setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(this, "Đơn đặt hàng " + objDDH.getMaDDH() + " lưu không thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (Exception ex) {
                        System.out.println("Ngoại lệ tại FormLapDonDatHang.jbtnDuyetDonHangMouseClicked:" + ex.getMessage());
                    }
                }
                else{
                       try {
                        if (modDDH.Update(objDDH)&&modCTDDH.Delete(objDDH.getMaDDH())) {
                            for (int i = 0; i < listCTDDH.size(); i++) {
                                if (!modCTDDH.Insert(listCTDDH.get(i))) {
                                    JOptionPane.showMessageDialog(this, "Sản phẩm có mã " + listCTDDH.get(i).getMaSP() + " cập nhật không thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                                }
                            }
//                    EnableComponent(false);
                            JOptionPane.showMessageDialog(this, "Đơn đặt hàng " + objDDH.getMaDDH() + " cập nhật thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                            jbtnDuyetDonHang.setVisible(false);
                            jBtnIn.setVisible(true);
                            jBtnHuy.setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(this, "Đơn đặt hàng " + objDDH.getMaDDH() + " cập nhật không thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (Exception ex) {
                        System.out.println("Ngoại lệ tại FormLapDonDatHang.jbtnDuyetDonHangMouseClicked:" + ex.getMessage());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Danh sách đặt hàng trống.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp để đặt hàng.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtnDuyetDonHangMouseClicked

    private void jbtnDuyetDonHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDuyetDonHangMouseEntered
        // TODO add your handling code here:
        setColor(jbtnDuyetDonHang);
    }//GEN-LAST:event_jbtnDuyetDonHangMouseEntered

    private void jbtnDuyetDonHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDuyetDonHangMouseExited
        // TODO add your handling code here:
        resetColor(jbtnDuyetDonHang);
    }//GEN-LAST:event_jbtnDuyetDonHangMouseExited

    private void jbtnDuyetDonHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDuyetDonHangMousePressed
        // TODO add your handling code here:
        resetColor(jbtnDuyetDonHang);
    }//GEN-LAST:event_jbtnDuyetDonHangMousePressed

    private void jbtnDuyetDonHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDuyetDonHangMouseReleased
        // TODO add your handling code here:
        setColor(jbtnDuyetDonHang);
    }//GEN-LAST:event_jbtnDuyetDonHangMouseReleased

    private void jBtnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseClicked
        // TODO add your handling code here:
        ReloadForm();
    }//GEN-LAST:event_jBtnHuyMouseClicked

    private void jBtnHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseEntered
        // TODO add your handling code here:
        setColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseEntered

    private void jBtnHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseExited
        // TODO add your handling code here:
        resetColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseExited

    private void jBtnHuyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMousePressed
        // TODO add your handling code here:
        resetColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMousePressed

    private void jBtnHuyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuyMouseReleased
        // TODO add your handling code here:
        setColor(jBtnHuy);
    }//GEN-LAST:event_jBtnHuyMouseReleased

    private void jcbbNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbNhaCungCapActionPerformed
        // TODO add your handling code here:
        
        try{
            DefaultTableModel model = (DefaultTableModel) jTbDSDH.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            listCTDDH.clear();
            if(jcbbNhaCungCap.getSelectedIndex()>0){
                jtxtMaNCC.setText(listComboboxNCC.get(jcbbNhaCungCap.getSelectedIndex()));
                HienThiDanhSachSanPhamNCC(CtrlLapDDH.LayDanhSachSanPhamNCC(listComboboxNCC.get(jcbbNhaCungCap.getSelectedIndex())));
            }
            else jtxtMaNCC.setText("");
        }
        catch(Exception ex){
            System.out.println("Ngoại lệ tại FormLapDonDatHang.jcbbNhaCungCapActionPerformed:"+ex.getMessage());
        }
    }//GEN-LAST:event_jcbbNhaCungCapActionPerformed

    private void jtbDSSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDSSPMouseClicked
        // TODO add your handling code here:
        if(jtbDSSP.getSelectedRow()>=0){
            Binding();
        }
    }//GEN-LAST:event_jtbDSSPMouseClicked

    private void jBtnChinhSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnChinhSuaMouseClicked
        // TODO add your handling code here:
        if (jTbDSDH.getSelectedRow() >= 0) {
            DefaultTableModel Model = (DefaultTableModel) jTbDSDH.getModel();
            int viewRow = jTbDSDH.getSelectedRow();
            int modelRow = jTbDSDH.convertRowIndexToModel(viewRow);
            String inputdialog = JOptionPane.showInputDialog(this, "Nhập số lượng:", "");
            if (inputdialog != null) {
                try {
                    int SL = Integer.parseInt(inputdialog);
                    if (!inputdialog.equals("0")) {
                        Model.setValueAt(SL, modelRow, 3);
                        listCTDDH.get(modelRow).setSoLuong(SL);
                    } else {
                        jBtnXoaMouseClicked(null);
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Số lượng nhập không hợp lệ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jBtnChinhSuaMouseClicked

    private void jBtnChinhSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnChinhSuaMouseEntered
        // TODO add your handling code here:
        setColor(jBtnChinhSua);
    }//GEN-LAST:event_jBtnChinhSuaMouseEntered

    private void jBtnChinhSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnChinhSuaMouseExited
        // TODO add your handling code here:
        resetColor(jBtnChinhSua);
    }//GEN-LAST:event_jBtnChinhSuaMouseExited

    private void jBtnChinhSuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnChinhSuaMousePressed
        // TODO add your handling code here:
        resetColor(jBtnChinhSua);
    }//GEN-LAST:event_jBtnChinhSuaMousePressed

    private void jBtnChinhSuaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnChinhSuaMouseReleased
        // TODO add your handling code here:
        setColor(jBtnChinhSua);
    }//GEN-LAST:event_jBtnChinhSuaMouseReleased

    private void jBtnHuy1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseClicked

    private void jBtnHuy1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseEntered

    private void jBtnHuy1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseExited

    private void jBtnHuy1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MousePressed

    private void jBtnHuy1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnHuy1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHuy1MouseReleased

    private void jBtnInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnInMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnInMouseClicked

    private void jBtnInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnInMouseEntered
        // TODO add your handling code here:
        setColor(jBtnIn);
    }//GEN-LAST:event_jBtnInMouseEntered

    private void jBtnInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnInMouseExited
        // TODO add your handling code here:
        resetColor(jBtnIn);
    }//GEN-LAST:event_jBtnInMouseExited

    private void jBtnInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnInMousePressed
        // TODO add your handling code here:
        resetColor(jBtnIn);
    }//GEN-LAST:event_jBtnInMousePressed

    private void jBtnInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnInMouseReleased
        // TODO add your handling code here:
        setColor(jBtnIn);
    }//GEN-LAST:event_jBtnInMouseReleased

    public void setColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()+1, pn.getHeight()+1);
        pn.setBackground(new Color(60,209,127,50));
        }
    }
    public void resetColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()-1, pn.getHeight()-1);
        pn.setBackground(new Color(153,153,153,180));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLapDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLapDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLapDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLapDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLapDonDatHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack;
    private javax.swing.JPanel jBtnChinhSua;
    private javax.swing.JPanel jBtnDathang;
    private javax.swing.JPanel jBtnHuy;
    private javax.swing.JPanel jBtnHuy1;
    private javax.swing.JPanel jBtnIn;
    private javax.swing.JPanel jBtnLamMoi;
    private javax.swing.JPanel jBtnTimKiem;
    private javax.swing.JPanel jBtnXoa;
    private com.toedter.calendar.JDateChooser jDateNgayDat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPnDSDH;
    private javax.swing.JPanel jPnDSSP;
    private javax.swing.JPanel jPnThongTinCTNH;
    private javax.swing.JPanel jPnThongtinDDH;
    private javax.swing.JPanel jPnTimKiem;
    private javax.swing.JScrollPane jScrDSDH;
    private javax.swing.JScrollPane jScrDSSP;
    private javax.swing.JSpinner jSpSoLuong;
    private javax.swing.JTable jTbDSDH;
    private javax.swing.JPanel jbtnDuyetDonHang;
    private javax.swing.JComboBox<String> jcbbNhaCungCap;
    private javax.swing.JComboBox<String> jcbbTimtheo;
    private javax.swing.JLabel jlbHuyDDH;
    private javax.swing.JLabel jlbHuyDDH1;
    private javax.swing.JTable jtbDSSP;
    private javax.swing.JTextField jtxtLoaiSP;
    private javax.swing.JTextField jtxtMaDDH;
    private javax.swing.JTextField jtxtMaNCC;
    private javax.swing.JTextField jtxtTenSP;
    private javax.swing.JTextField jtxtTimkiem;
    // End of variables declaration//GEN-END:variables
}
