/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connect.Connect;
import Control.CtrlThongKeCongNo;
import Edit.Edit;
import Model.ModCongNo;
import Model.ModKyCongNo;
import Object.ObjCongNo;
import Object.ObjHoaDonLe;
import Object.ObjKyCongNo;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ThaiNguyen
 */
public class FormThongKeCongNo extends javax.swing.JFrame {

    Edit editFrm = new Edit();
    int xx, yy;
    CtrlThongKeCongNo ctrlTKCN = new CtrlThongKeCongNo();
    ModKyCongNo modKCN = new ModKyCongNo();
    ModCongNo modCN = new ModCongNo();
    ArrayList<ObjCongNo> ListCongNo = new ArrayList<>();
    ObjKyCongNo objKCN = new ObjKyCongNo();
    ArrayList<ObjKyCongNo>ListKCN =new ArrayList<>();
    SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
    int flag = 0;
    /**
     * Creates new form FormThongKeTonKho
     */
    public FormThongKeCongNo() {
        initComponents();
        setLocationRelativeTo(null);
        JPanel ListPanel[]=new JPanel[]{jPanel2,jPanel3};
        editFrm.MakeTransparentPanel(ListPanel);
        JPanel ListTitle[]=new JPanel[]{jPnDSTonKho,jPnThongketonkho};
        editFrm.MakeTransparentTitle(ListTitle);
        JPanel ListButton[]=new JPanel[]{jBtnBack1,jBtnLuuKiCongNo,jBtnXemBaoCao,jBtnXoaKiCongNo,jBtnThongKe};
        editFrm.MakeTransparentButton(ListButton);
        editFrm.MakeTransparentTable(jScrDSTK, jTbDSCN);
        LoadForm();
    }
    
    public void LoadForm(){
        jDateTuNgay.setDate(new Date());
        jDateDenNgay.setDate(new Date());
        LoadComboboxKiCongNo();
        Enable(true);
    }
    
    public void HienThiDanhSachCongNo(ResultSet rs){
        ListCongNo.clear();
        DefaultTableModel model = (DefaultTableModel) jTbDSCN.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            while (rs.next()) {
                ObjCongNo itemCN = new ObjCongNo(rs.getString("MaKCN"),rs.getString("MaKH"),rs.getString("TenKH"), rs.getInt("SoDuNoDauKi"), rs.getInt("SoNoPhatSinhTrongKi"),rs.getInt("SoTienThuTrongKi"),rs.getInt("SoDuNoCuoiKi"));
                ListCongNo.add(itemCN);
                model.addRow(new Object[]{itemCN.getMaKH().toUpperCase(),itemCN.getTenKH().toUpperCase(),itemCN.getSoDuNoDauKi(),itemCN.getSoNoPhatSinhTrongKi(),itemCN.getSoTienThuTrongKi(),itemCN.getSoDuNoCuoiKi(),itemCN.getSoDuNoCuoiKi()});
            }
        } catch (Exception ex) {
            LoadComboboxKiCongNo();
        }
    }
    
    public void LoadComboboxKiCongNo(){
        ListKCN.clear();
        jcbbKiCongNo.removeAllItems();
        jcbbKiCongNo.addItem("---Chọn kì công nợ---");
        ListKCN.add(new ObjKyCongNo());
        ResultSet rs=ctrlTKCN.LayDanhSachKCN();
        try{
            while(rs.next()){
                ObjKyCongNo itemKCN=new ObjKyCongNo(rs.getString("MaKCN"), rs.getDate("TuNgay"), rs.getDate("DenNgay"));
                jcbbKiCongNo.addItem(rs.getString("MaKCN")+" : "+dt.format(rs.getDate("TuNgay"))+" - "+dt.format(rs.getDate("DenNgay")));
                ListKCN.add(itemKCN);
            }
        }
        catch(SQLException ex){
            System.out.println("Ngoại lệ tại FormThongKeCongNo.LoadComboboxKiCongNo: "+ex.getMessage());
        }
    }
    
    public void Enable(boolean check){
        jBtnLuuKiCongNo.setVisible(check);
        jBtnLuuKiCongNo1.setVisible(!check);
        jBtnXoaKiCongNo.setVisible(!check);
        jBtnXoaKiCongNo1.setVisible(check);
        jBtnXemBaoCao.setVisible(!check);
        jBtnXemBaoCao1.setVisible(check);
    }
    
    public void filters(String querry){
        DefaultTableModel model = (DefaultTableModel) jTbDSCN.getModel();
        TableRowSorter<DefaultTableModel>  tr=new TableRowSorter<DefaultTableModel>(model);
        jTbDSCN.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(querry));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnBack1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jBtnLuuKiCongNo = new javax.swing.JPanel();
        jlbLuu = new javax.swing.JLabel();
        jBtnLuuKiCongNo1 = new javax.swing.JPanel();
        jlbLuu1 = new javax.swing.JLabel();
        jBtnXoaKiCongNo = new javax.swing.JPanel();
        jlbIn1 = new javax.swing.JLabel();
        jBtnXoaKiCongNo1 = new javax.swing.JPanel();
        jlbIn3 = new javax.swing.JLabel();
        jBtnXemBaoCao = new javax.swing.JPanel();
        jlbIn2 = new javax.swing.JLabel();
        jBtnXemBaoCao1 = new javax.swing.JPanel();
        jlbIn4 = new javax.swing.JLabel();
        jScrDSTK = new javax.swing.JScrollPane();
        jTbDSCN = new javax.swing.JTable();
        jBtnThongKe = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPnThongketonkho = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbbKiCongNo = new javax.swing.JComboBox<>();
        jDateTuNgay = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateDenNgay = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jtxtTimKiem = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPnDSTonKho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBack1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBack1MouseReleased(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBack1Layout = new javax.swing.GroupLayout(jBtnBack1);
        jBtnBack1.setLayout(jBtnBack1Layout);
        jBtnBack1Layout.setHorizontalGroup(
            jBtnBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBack1Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBtnBack1Layout.setVerticalGroup(
            jBtnBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBack1Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jBtnLuuKiCongNo.setBackground(new java.awt.Color(102, 102, 102));
        jBtnLuuKiCongNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLuuKiCongNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLuuKiCongNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLuuKiCongNoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLuuKiCongNoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLuuKiCongNoMouseReleased(evt);
            }
        });
        jBtnLuuKiCongNo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbLuu.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbLuu.setForeground(new java.awt.Color(255, 255, 255));
        jlbLuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Save_30px_1.png"))); // NOI18N
        jlbLuu.setText("  Lưu kì công nợ");
        jBtnLuuKiCongNo.add(jlbLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        getContentPane().add(jBtnLuuKiCongNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 98, 165, 60));

        jBtnLuuKiCongNo1.setBackground(new java.awt.Color(102, 102, 102));
        jBtnLuuKiCongNo1.setOpaque(false);
        jBtnLuuKiCongNo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLuuKiCongNo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLuuKiCongNo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLuuKiCongNo1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLuuKiCongNo1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLuuKiCongNo1MouseReleased(evt);
            }
        });
        jBtnLuuKiCongNo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbLuu1.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbLuu1.setForeground(new java.awt.Color(255, 255, 255));
        jlbLuu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Save_30px_1.png"))); // NOI18N
        jlbLuu1.setText("  Lưu kì công nợ");
        jlbLuu1.setEnabled(false);
        jBtnLuuKiCongNo1.add(jlbLuu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        getContentPane().add(jBtnLuuKiCongNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 98, 165, 60));

        jBtnXoaKiCongNo.setBackground(new java.awt.Color(102, 102, 102));
        jBtnXoaKiCongNo.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXoaKiCongNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXoaKiCongNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXoaKiCongNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXoaKiCongNoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXoaKiCongNoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXoaKiCongNoMouseReleased(evt);
            }
        });
        jBtnXoaKiCongNo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIn1.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbIn1.setForeground(new java.awt.Color(255, 255, 255));
        jlbIn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Trash_40px_1.png"))); // NOI18N
        jlbIn1.setText("Xóa kì công nợ");
        jBtnXoaKiCongNo.add(jlbIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        getContentPane().add(jBtnXoaKiCongNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 98, 165, 60));

        jBtnXoaKiCongNo1.setBackground(new java.awt.Color(102, 102, 102));
        jBtnXoaKiCongNo1.setOpaque(false);
        jBtnXoaKiCongNo1.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXoaKiCongNo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXoaKiCongNo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXoaKiCongNo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXoaKiCongNo1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXoaKiCongNo1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXoaKiCongNo1MouseReleased(evt);
            }
        });
        jBtnXoaKiCongNo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIn3.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbIn3.setForeground(new java.awt.Color(255, 255, 255));
        jlbIn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Trash_40px_1.png"))); // NOI18N
        jlbIn3.setText("Xóa kì công nợ");
        jlbIn3.setEnabled(false);
        jBtnXoaKiCongNo1.add(jlbIn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        getContentPane().add(jBtnXoaKiCongNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 98, 165, 60));

        jBtnXemBaoCao.setBackground(new java.awt.Color(102, 102, 102));
        jBtnXemBaoCao.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXemBaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCaoMouseReleased(evt);
            }
        });
        jBtnXemBaoCao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIn2.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbIn2.setForeground(new java.awt.Color(255, 255, 255));
        jlbIn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Print_45px.png"))); // NOI18N
        jlbIn2.setText("Xem báo cáo");
        jBtnXemBaoCao.add(jlbIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        getContentPane().add(jBtnXemBaoCao, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 98, 165, 60));

        jBtnXemBaoCao1.setBackground(new java.awt.Color(102, 102, 102));
        jBtnXemBaoCao1.setOpaque(false);
        jBtnXemBaoCao1.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXemBaoCao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCao1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCao1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCao1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCao1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXemBaoCao1MouseReleased(evt);
            }
        });
        jBtnXemBaoCao1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIn4.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbIn4.setForeground(new java.awt.Color(255, 255, 255));
        jlbIn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Print_45px.png"))); // NOI18N
        jlbIn4.setText("Xem báo cáo");
        jlbIn4.setEnabled(false);
        jBtnXemBaoCao1.add(jlbIn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        getContentPane().add(jBtnXemBaoCao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 98, 165, 60));

        jTbDSCN.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jTbDSCN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số dư nợ đầu kì", "Số nợ phát sinh trong kì", "Số tiền thu trong kì", "Số dư nợ cuối kì"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbDSCN.setFocusable(false);
        jTbDSCN.setRowHeight(25);
        jTbDSCN.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTbDSCN.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrDSTK.setViewportView(jTbDSCN);
        if (jTbDSCN.getColumnModel().getColumnCount() > 0) {
            jTbDSCN.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTbDSCN.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTbDSCN.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTbDSCN.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTbDSCN.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTbDSCN.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        getContentPane().add(jScrDSTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 255, 1100, 380));

        jBtnThongKe.setBackground(new java.awt.Color(153, 153, 153));
        jBtnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongKeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongKeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongKeMouseReleased(evt);
            }
        });
        jBtnThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thống kê");
        jBtnThongKe.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 3, 60, -1));

        getContentPane().add(jBtnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 110, 20));

        jPanel1.setOpaque(false);
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnThongketonkho.setBackground(new java.awt.Color(0, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Thống kê công nợ :");

        javax.swing.GroupLayout jPnThongketonkhoLayout = new javax.swing.GroupLayout(jPnThongketonkho);
        jPnThongketonkho.setLayout(jPnThongketonkhoLayout);
        jPnThongketonkhoLayout.setHorizontalGroup(
            jPnThongketonkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongketonkhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(981, Short.MAX_VALUE))
        );
        jPnThongketonkhoLayout.setVerticalGroup(
            jPnThongketonkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPnThongketonkho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        jLabel2.setText("Đến ngày :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 20));

        jLabel3.setText("Chọn kì thống kê :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 90, -1, -1));

        jcbbKiCongNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbKiCongNo.setFocusable(false);
        jcbbKiCongNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbKiCongNoActionPerformed(evt);
            }
        });
        jPanel2.add(jcbbKiCongNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 87, 283, -1));

        jDateTuNgay.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDateTuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, -1));

        jLabel6.setText("Từ ngày :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 51, -1, 20));

        jDateDenNgay.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDateDenNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 120, -1));

        jLabel7.setText("Tra cứu : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 124, -1, -1));

        jtxtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTimKiemKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 120, 283, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1110, 160));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnDSTonKho.setBackground(new java.awt.Color(0, 204, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Danh sách công nợ :");

        javax.swing.GroupLayout jPnDSTonKhoLayout = new javax.swing.GroupLayout(jPnDSTonKho);
        jPnDSTonKho.setLayout(jPnDSTonKhoLayout);
        jPnDSTonKhoLayout.setHorizontalGroup(
            jPnDSTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSTonKhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(975, Short.MAX_VALUE))
        );
        jPnDSTonKhoLayout.setVerticalGroup(
            jPnDSTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPnDSTonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 1110, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 650));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo-530024.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnBack1MouseClicked

    private void jBtnBack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MouseEntered

    private void jBtnBack1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MouseExited

    private void jBtnBack1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MousePressed

    private void jBtnBack1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBack1MouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack1);
    }//GEN-LAST:event_jBtnBack1MouseReleased

    private void jBtnLuuKiCongNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuKiCongNoMouseClicked
        // TODO add your handling code here:
        try{
            if(modKCN.Insert(objKCN))
                for(int i=0;i<ListCongNo.size();i++){
                    ListCongNo.get(i).setMaKCN(objKCN.getMaKCN());
                    if(!modCN.Insert(ListCongNo.get(i)))
                        JOptionPane.showMessageDialog(this, "Công nợ khách hàng" + ListCongNo.get(i).getTenKH()+ " lưu không thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            JOptionPane.showMessageDialog(this, "Kỳ công nợ " + objKCN.getMaKCN()+ " lưu thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            LoadComboboxKiCongNo();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Kỳ công nợ " + objKCN.getMaKCN()+ " lưu không thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnLuuKiCongNoMouseClicked

    private void jBtnLuuKiCongNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuKiCongNoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLuuKiCongNo);
    }//GEN-LAST:event_jBtnLuuKiCongNoMouseEntered

    private void jBtnLuuKiCongNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuKiCongNoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLuuKiCongNo);
    }//GEN-LAST:event_jBtnLuuKiCongNoMouseExited

    private void jBtnLuuKiCongNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuKiCongNoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLuuKiCongNo);
    }//GEN-LAST:event_jBtnLuuKiCongNoMousePressed

    private void jBtnLuuKiCongNoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuKiCongNoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLuuKiCongNo);
    }//GEN-LAST:event_jBtnLuuKiCongNoMouseReleased

    private void jBtnXemBaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCaoMouseClicked
        // TODO add your handling code here:
        try {
            Connect con = new Connect();
            con.Connected();
            Hashtable hash = new Hashtable();
            InputStream is = null;
            is = new FileInputStream("src/Report/ReportTongHopCongNo.jasper");
            hash.put("MaKCN", objKCN.getMaKCN());
            JasperPrint print = JasperFillManager.fillReport(is, hash, con.getConDB());
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            System.out.println("Ngoại lệ tại FormThongKeCongNo.jBtnXemBaoCaoMouseClicked:" + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBtnXemBaoCaoMouseClicked

    private void jBtnXemBaoCaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXemBaoCao);
    }//GEN-LAST:event_jBtnXemBaoCaoMouseEntered

    private void jBtnXemBaoCaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXemBaoCao);
    }//GEN-LAST:event_jBtnXemBaoCaoMouseExited

    private void jBtnXemBaoCaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXemBaoCao);
        //        System.out.println("IN");
        //        EnableComponent(true);
    }//GEN-LAST:event_jBtnXemBaoCaoMousePressed

    private void jBtnXemBaoCaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXemBaoCao);
    }//GEN-LAST:event_jBtnXemBaoCaoMouseReleased

    private void jBtnXoaKiCongNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaKiCongNoMouseClicked
        // TODO add your handling code here:
        int dialogButton = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            if(modCN.Delete(objKCN.getMaKCN())&&modKCN.Delete(objKCN.getMaKCN())){
                JOptionPane.showMessageDialog(this, "Xóa thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                HienThiDanhSachCongNo(null);
                LoadComboboxKiCongNo();
                Enable(true);
            }
            else
                JOptionPane.showMessageDialog(this, "Xóa thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnXoaKiCongNoMouseClicked

    private void jBtnXoaKiCongNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaKiCongNoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXoaKiCongNo);
    }//GEN-LAST:event_jBtnXoaKiCongNoMouseEntered

    private void jBtnXoaKiCongNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaKiCongNoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXoaKiCongNo);
    }//GEN-LAST:event_jBtnXoaKiCongNoMouseExited

    private void jBtnXoaKiCongNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaKiCongNoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXoaKiCongNo);
    }//GEN-LAST:event_jBtnXoaKiCongNoMousePressed

    private void jBtnXoaKiCongNoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaKiCongNoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXoaKiCongNo);
    }//GEN-LAST:event_jBtnXoaKiCongNoMouseReleased

    private void jBtnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongKe);
    }//GEN-LAST:event_jBtnThongKeMouseEntered

    private void jBtnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongKe);
    }//GEN-LAST:event_jBtnThongKeMouseExited

    private void jBtnThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongKe);
    }//GEN-LAST:event_jBtnThongKeMousePressed

    private void jBtnThongKeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThongKe);
    }//GEN-LAST:event_jBtnThongKeMouseReleased

    private void jBtnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeMouseClicked
        // TODO add your handling code here:
       objKCN=new ObjKyCongNo(ctrlTKCN.LayMaKCN(),jDateTuNgay.getDate(),jDateDenNgay.getDate());
       HienThiDanhSachCongNo(ctrlTKCN.LayDSCongNo(jDateTuNgay.getDate(),jDateDenNgay.getDate()));
       Enable(true);
       LoadComboboxKiCongNo();
    }//GEN-LAST:event_jBtnThongKeMouseClicked

    private void jBtnLuuKiCongNo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuKiCongNo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuuKiCongNo1MouseClicked

    private void jBtnLuuKiCongNo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuKiCongNo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuuKiCongNo1MouseEntered

    private void jBtnLuuKiCongNo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuKiCongNo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuuKiCongNo1MouseExited

    private void jBtnLuuKiCongNo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuKiCongNo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuuKiCongNo1MousePressed

    private void jBtnLuuKiCongNo1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuKiCongNo1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLuuKiCongNo1MouseReleased

    private void jBtnXoaKiCongNo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaKiCongNo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoaKiCongNo1MouseClicked

    private void jBtnXoaKiCongNo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaKiCongNo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoaKiCongNo1MouseEntered

    private void jBtnXoaKiCongNo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaKiCongNo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoaKiCongNo1MouseExited

    private void jBtnXoaKiCongNo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaKiCongNo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoaKiCongNo1MousePressed

    private void jBtnXoaKiCongNo1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXoaKiCongNo1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXoaKiCongNo1MouseReleased

    private void jBtnXemBaoCao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCao1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemBaoCao1MouseClicked

    private void jBtnXemBaoCao1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCao1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemBaoCao1MouseEntered

    private void jBtnXemBaoCao1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCao1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemBaoCao1MouseExited

    private void jBtnXemBaoCao1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCao1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemBaoCao1MousePressed

    private void jBtnXemBaoCao1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemBaoCao1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnXemBaoCao1MouseReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jcbbKiCongNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbKiCongNoActionPerformed
        // TODO add your handling code here:
        if (jcbbKiCongNo.getSelectedIndex() > 0) {
            HienThiDanhSachCongNo(ctrlTKCN.LayDSCongNo(ListKCN.get(jcbbKiCongNo.getSelectedIndex()).getMaKCN()));
            Enable(false);
            objKCN=new ObjKyCongNo(ListKCN.get(jcbbKiCongNo.getSelectedIndex()).getMaKCN());
        }
    }//GEN-LAST:event_jcbbKiCongNoActionPerformed

    private void jtxtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTimKiemKeyReleased
        // TODO add your handling code here:
        String text=jtxtTimKiem.getText().toUpperCase();
        filters(text);
    }//GEN-LAST:event_jtxtTimKiemKeyReleased

    /**
     * @param args the command line arguments
     */
    
    public void setColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()+1, pn.getHeight()+1);
        pn.setBackground(new Color(60,209,127,50));
        }
    }
    public void resetColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()-1, pn.getHeight()-1);
        pn.setBackground(new Color(153,153,153,180));
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThongKeCongNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThongKeCongNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThongKeCongNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThongKeCongNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThongKeCongNo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack1;
    private javax.swing.JPanel jBtnLuuKiCongNo;
    private javax.swing.JPanel jBtnLuuKiCongNo1;
    private javax.swing.JPanel jBtnThongKe;
    private javax.swing.JPanel jBtnXemBaoCao;
    private javax.swing.JPanel jBtnXemBaoCao1;
    private javax.swing.JPanel jBtnXoaKiCongNo;
    private javax.swing.JPanel jBtnXoaKiCongNo1;
    private com.toedter.calendar.JDateChooser jDateDenNgay;
    private com.toedter.calendar.JDateChooser jDateTuNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnDSTonKho;
    private javax.swing.JPanel jPnThongketonkho;
    private javax.swing.JScrollPane jScrDSTK;
    private javax.swing.JTable jTbDSCN;
    private javax.swing.JComboBox<String> jcbbKiCongNo;
    private javax.swing.JLabel jlbIn1;
    private javax.swing.JLabel jlbIn2;
    private javax.swing.JLabel jlbIn3;
    private javax.swing.JLabel jlbIn4;
    private javax.swing.JLabel jlbLuu;
    private javax.swing.JLabel jlbLuu1;
    private javax.swing.JTextField jtxtTimKiem;
    // End of variables declaration//GEN-END:variables
}
