/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Object.ObjTaiKhoan;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ThaiNguyen
 */
public class FormQuanLiThongKe extends javax.swing.JFrame {
    
    int xx,yy;
    ObjTaiKhoan objTK = new ObjTaiKhoan();
    /**
     * Creates new form MainForm
     */
    public FormQuanLiThongKe() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0,0,0,80));    
        jBtnThongKeHangMuaNhieu.setBackground(new Color(236,236,236,50));  
        jBtnThongKeTonKho.setBackground(new Color(236,236,236,50));  
        jBtnThongKeCongNo.setBackground(new Color(236,236,236,50));  
        jBtnThongKeDoanhThu.setBackground(new Color(236,236,236,50));         
        jBtn7.setBackground(new Color(236,236,236,50));
    }
    
    public FormQuanLiThongKe(String PhanQuyen) {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0,0,0,80));    
        jBtnThongKeHangMuaNhieu.setBackground(new Color(236,236,236,50));  
        jBtnThongKeTonKho.setBackground(new Color(236,236,236,50));  
        jBtnThongKeCongNo.setBackground(new Color(236,236,236,50));  
        jBtnThongKeDoanhThu.setBackground(new Color(236,236,236,50));         
        jBtn7.setBackground(new Color(236,236,236,50));
        objTK.setPhanLoai(PhanQuyen);
        PhanQuyenUSER();
    }
    
    public void setColor(JPanel pn){
        pn.setSize(pn.getWidth()+1, pn.getHeight()+1);
        pn.setBackground(new Color(60,209,127,50));
    }
    public void resetColor(JPanel pn){   
        pn.setSize(pn.getWidth()-1, pn.getHeight()-1);
        pn.setBackground(new Color(236,236,236,50));
    }
    
    public void PhanQuyenUSER(){
        if (objTK.getPhanLoai().equals("Quản lý kho")) {
            jBtnThongKeTonKho.setEnabled(true);
            jlbIconThongKeTonKho.setEnabled(true);
            jlbThongKeTonKho.setEnabled(true);
            jBtnThongKeHangMuaNhieu.setEnabled(true);
            jlbIconThongKeHangMuaNhieu.setEnabled(true);
            jlbThongKeHangMuaNhieu.setEnabled(rootPaneCheckingEnabled);
        } else if(objTK.getPhanLoai().equals("Quản lý kế toán")) {
            jBtnThongKeDoanhThu.setEnabled(true);
            jlbIconThongKeDoanhThu.setEnabled(true);
            jlbThongKeDoanhThu.setEnabled(true);
            jBtnThongKeCongNo.setEnabled(true);
            jlbIconThongKeCongNo.setEnabled(true);
            jlbThongKeCongNo.setEnabled(true);
        }
        else if(objTK.getPhanLoai().equals("Quản lý")) {
            jBtnThongKeTonKho.setEnabled(true);
            jlbIconThongKeTonKho.setEnabled(true);
            jlbThongKeTonKho.setEnabled(true);
            jBtnThongKeHangMuaNhieu.setEnabled(true);
            jlbIconThongKeHangMuaNhieu.setEnabled(true);
            jBtnThongKeDoanhThu.setEnabled(true);
            jlbIconThongKeDoanhThu.setEnabled(true);
            jlbThongKeDoanhThu.setEnabled(true);
            jBtnThongKeCongNo.setEnabled(true);
            jlbIconThongKeCongNo.setEnabled(true);
            jlbThongKeCongNo.setEnabled(true);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnClose = new javax.swing.JLabel();
        jBtnThongKeCongNo = new javax.swing.JPanel();
        jlbIconThongKeCongNo = new javax.swing.JLabel();
        jlbThongKeCongNo = new javax.swing.JLabel();
        jBtnThongKeDoanhThu = new javax.swing.JPanel();
        jlbIconThongKeDoanhThu = new javax.swing.JLabel();
        jlbThongKeDoanhThu = new javax.swing.JLabel();
        jBtnThongKeTonKho = new javax.swing.JPanel();
        jlbIconThongKeTonKho = new javax.swing.JLabel();
        jlbThongKeTonKho = new javax.swing.JLabel();
        jBtnThongKeHangMuaNhieu = new javax.swing.JPanel();
        jlbIconThongKeHangMuaNhieu = new javax.swing.JLabel();
        jlbThongKeHangMuaNhieu = new javax.swing.JLabel();
        jBtn7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnClose.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jBtnClose.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClose.setText("X");
        jBtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 20, 30));

        jBtnThongKeCongNo.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThongKeCongNo.setEnabled(false);
        jBtnThongKeCongNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThongKeCongNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongKeCongNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongKeCongNoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongKeCongNoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongKeCongNoMouseReleased(evt);
            }
        });
        jBtnThongKeCongNo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIconThongKeCongNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconThongKeCongNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Bank_60px_1.png"))); // NOI18N
        jlbIconThongKeCongNo.setEnabled(false);
        jBtnThongKeCongNo.add(jlbIconThongKeCongNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 60));

        jlbThongKeCongNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbThongKeCongNo.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongKeCongNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongKeCongNo.setText("Thống kê công nợ");
        jlbThongKeCongNo.setEnabled(false);
        jBtnThongKeCongNo.add(jlbThongKeCongNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnThongKeCongNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 180, 120));

        jBtnThongKeDoanhThu.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThongKeDoanhThu.setEnabled(false);
        jBtnThongKeDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThongKeDoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongKeDoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongKeDoanhThuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongKeDoanhThuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongKeDoanhThuMouseReleased(evt);
            }
        });

        jlbIconThongKeDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconThongKeDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Profit_70px_1.png"))); // NOI18N
        jlbIconThongKeDoanhThu.setEnabled(false);

        jlbThongKeDoanhThu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbThongKeDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongKeDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongKeDoanhThu.setText("Thống kê doanh thu");
        jlbThongKeDoanhThu.setEnabled(false);

        javax.swing.GroupLayout jBtnThongKeDoanhThuLayout = new javax.swing.GroupLayout(jBtnThongKeDoanhThu);
        jBtnThongKeDoanhThu.setLayout(jBtnThongKeDoanhThuLayout);
        jBtnThongKeDoanhThuLayout.setHorizontalGroup(
            jBtnThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongKeDoanhThuLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jlbIconThongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnThongKeDoanhThuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbThongKeDoanhThu)
                .addGap(27, 27, 27))
        );
        jBtnThongKeDoanhThuLayout.setVerticalGroup(
            jBtnThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongKeDoanhThuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbIconThongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbThongKeDoanhThu)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnThongKeDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        jBtnThongKeTonKho.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThongKeTonKho.setEnabled(false);
        jBtnThongKeTonKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThongKeTonKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongKeTonKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongKeTonKhoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongKeTonKhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongKeTonKhoMouseReleased(evt);
            }
        });

        jlbIconThongKeTonKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconThongKeTonKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Open_Box_70px_6.png"))); // NOI18N
        jlbIconThongKeTonKho.setEnabled(false);

        jlbThongKeTonKho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbThongKeTonKho.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongKeTonKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongKeTonKho.setText("Thống kê tồn kho");
        jlbThongKeTonKho.setEnabled(false);

        javax.swing.GroupLayout jBtnThongKeTonKhoLayout = new javax.swing.GroupLayout(jBtnThongKeTonKho);
        jBtnThongKeTonKho.setLayout(jBtnThongKeTonKhoLayout);
        jBtnThongKeTonKhoLayout.setHorizontalGroup(
            jBtnThongKeTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongKeTonKhoLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jBtnThongKeTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnThongKeTonKhoLayout.createSequentialGroup()
                        .addComponent(jlbThongKeTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnThongKeTonKhoLayout.createSequentialGroup()
                        .addComponent(jlbIconThongKeTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jBtnThongKeTonKhoLayout.setVerticalGroup(
            jBtnThongKeTonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongKeTonKhoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlbIconThongKeTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbThongKeTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jBtnThongKeTonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jBtnThongKeHangMuaNhieu.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThongKeHangMuaNhieu.setEnabled(false);
        jBtnThongKeHangMuaNhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThongKeHangMuaNhieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongKeHangMuaNhieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongKeHangMuaNhieuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongKeHangMuaNhieuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongKeHangMuaNhieuMouseReleased(evt);
            }
        });

        jlbIconThongKeHangMuaNhieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconThongKeHangMuaNhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Poll_80px_1.png"))); // NOI18N
        jlbIconThongKeHangMuaNhieu.setEnabled(false);

        jlbThongKeHangMuaNhieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbThongKeHangMuaNhieu.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongKeHangMuaNhieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongKeHangMuaNhieu.setText("Hàng được mua nhiều");
        jlbThongKeHangMuaNhieu.setEnabled(false);

        javax.swing.GroupLayout jBtnThongKeHangMuaNhieuLayout = new javax.swing.GroupLayout(jBtnThongKeHangMuaNhieu);
        jBtnThongKeHangMuaNhieu.setLayout(jBtnThongKeHangMuaNhieuLayout);
        jBtnThongKeHangMuaNhieuLayout.setHorizontalGroup(
            jBtnThongKeHangMuaNhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongKeHangMuaNhieuLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jBtnThongKeHangMuaNhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnThongKeHangMuaNhieuLayout.createSequentialGroup()
                        .addComponent(jlbIconThongKeHangMuaNhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnThongKeHangMuaNhieuLayout.createSequentialGroup()
                        .addComponent(jlbThongKeHangMuaNhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jBtnThongKeHangMuaNhieuLayout.setVerticalGroup(
            jBtnThongKeHangMuaNhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongKeHangMuaNhieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbIconThongKeHangMuaNhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbThongKeHangMuaNhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jBtnThongKeHangMuaNhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, 120));

        jBtn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtn7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtn7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtn7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtn7MouseReleased(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtn7Layout = new javax.swing.GroupLayout(jBtn7);
        jBtn7.setLayout(jBtn7Layout);
        jBtn7Layout.setHorizontalGroup(
            jBtn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jBtn7Layout.setVerticalGroup(
            jBtn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/navigation.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 80));

        jLabel14.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Get Managed");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Support Management");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Quản lí thống kê, báo biểu");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 300, 40));

        jLabel20.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Design, Create By Closer Group");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 290, 10));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnThongKeCongNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeCongNoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongKeCongNo);
    }//GEN-LAST:event_jBtnThongKeCongNoMouseEntered

    private void jBtnThongKeCongNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeCongNoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongKeCongNo);
    }//GEN-LAST:event_jBtnThongKeCongNoMouseExited

    private void jBtnThongKeDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeDoanhThuMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongKeDoanhThu);
    }//GEN-LAST:event_jBtnThongKeDoanhThuMouseEntered

    private void jBtnThongKeDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeDoanhThuMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongKeDoanhThu);
        
    }//GEN-LAST:event_jBtnThongKeDoanhThuMouseExited

    private void jBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtnCloseMouseClicked

    private void jBtn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseEntered
        // TODO add your handling code here:
        setColor(jBtn7);
    }//GEN-LAST:event_jBtn7MouseEntered

    private void jBtn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseExited
        // TODO add your handling code here:
        resetColor(jBtn7);
    }//GEN-LAST:event_jBtn7MouseExited

    private void jBtnThongKeCongNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeCongNoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongKeCongNo);
    }//GEN-LAST:event_jBtnThongKeCongNoMousePressed

    private void jBtnThongKeCongNoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeCongNoMouseReleased
        // TODO add your handling code here:
        if(jBtnThongKeCongNo.getBackground().equals(new Color(236,236,236,50))){
        setColor(jBtnThongKeCongNo);
        }
    }//GEN-LAST:event_jBtnThongKeCongNoMouseReleased

    private void jBtnThongKeDoanhThuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeDoanhThuMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongKeDoanhThu);
    }//GEN-LAST:event_jBtnThongKeDoanhThuMousePressed

    private void jBtnThongKeDoanhThuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeDoanhThuMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThongKeDoanhThu);
    }//GEN-LAST:event_jBtnThongKeDoanhThuMouseReleased

    private void jBtn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MousePressed
        // TODO add your handling code here:
        resetColor(jBtn7);
    }//GEN-LAST:event_jBtn7MousePressed

    private void jBtn7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseReleased
        // TODO add your handling code here:
        setColor(jBtn7);
    }//GEN-LAST:event_jBtn7MouseReleased

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jBtnThongKeTonKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeTonKhoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongKeTonKho);
    }//GEN-LAST:event_jBtnThongKeTonKhoMouseEntered

    private void jBtnThongKeTonKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeTonKhoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongKeTonKho);
    }//GEN-LAST:event_jBtnThongKeTonKhoMouseExited

    private void jBtnThongKeTonKhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeTonKhoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongKeTonKho);
    }//GEN-LAST:event_jBtnThongKeTonKhoMousePressed

    private void jBtnThongKeTonKhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeTonKhoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThongKeTonKho);
    }//GEN-LAST:event_jBtnThongKeTonKhoMouseReleased

    private void jBtnThongKeHangMuaNhieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeHangMuaNhieuMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongKeHangMuaNhieu);
    }//GEN-LAST:event_jBtnThongKeHangMuaNhieuMouseEntered

    private void jBtnThongKeHangMuaNhieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeHangMuaNhieuMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongKeHangMuaNhieu);
    }//GEN-LAST:event_jBtnThongKeHangMuaNhieuMouseExited

    private void jBtnThongKeHangMuaNhieuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeHangMuaNhieuMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongKeHangMuaNhieu);
    }//GEN-LAST:event_jBtnThongKeHangMuaNhieuMousePressed

    private void jBtnThongKeHangMuaNhieuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeHangMuaNhieuMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThongKeHangMuaNhieu);
    }//GEN-LAST:event_jBtnThongKeHangMuaNhieuMouseReleased

    private void jBtn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn7MouseClicked

    private void jBtnThongKeTonKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeTonKhoMouseClicked
        // TODO add your handling code here:
        new FormThongKeTonKho().setVisible(true);
    }//GEN-LAST:event_jBtnThongKeTonKhoMouseClicked

    private void jBtnThongKeHangMuaNhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeHangMuaNhieuMouseClicked
        // TODO add your handling code here:
        FormTKSanPhamBanNhieu frmTKSPBN = new FormTKSanPhamBanNhieu();
        frmTKSPBN.setVisible(true);
    }//GEN-LAST:event_jBtnThongKeHangMuaNhieuMouseClicked

    private void jBtnThongKeCongNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeCongNoMouseClicked
        // TODO add your handling code here:
        new FormThongKeCongNo().setVisible(true);
    }//GEN-LAST:event_jBtnThongKeCongNoMouseClicked

    private void jBtnThongKeDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeDoanhThuMouseClicked
        // TODO add your handling code here:
        FormThongKeDoanhThu frmTKDT = new FormThongKeDoanhThu();
        frmTKDT.setVisible(true);
    }//GEN-LAST:event_jBtnThongKeDoanhThuMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLiThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtn7;
    private javax.swing.JLabel jBtnClose;
    private javax.swing.JPanel jBtnThongKeCongNo;
    private javax.swing.JPanel jBtnThongKeDoanhThu;
    private javax.swing.JPanel jBtnThongKeHangMuaNhieu;
    private javax.swing.JPanel jBtnThongKeTonKho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlbIconThongKeCongNo;
    private javax.swing.JLabel jlbIconThongKeDoanhThu;
    private javax.swing.JLabel jlbIconThongKeHangMuaNhieu;
    private javax.swing.JLabel jlbIconThongKeTonKho;
    private javax.swing.JLabel jlbThongKeCongNo;
    private javax.swing.JLabel jlbThongKeDoanhThu;
    private javax.swing.JLabel jlbThongKeHangMuaNhieu;
    private javax.swing.JLabel jlbThongKeTonKho;
    // End of variables declaration//GEN-END:variables
}
