/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Object.ObjTaiKhoan;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ThaiNguyen
 */
public class FormQuanLiBanHang extends javax.swing.JFrame {
    
    int xx,yy;
    private ObjTaiKhoan User = new ObjTaiKhoan("15520783","123456");
    /**
     * Creates new form MainForm
     */
    public FormQuanLiBanHang(ObjTaiKhoan objTK) {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0,0,0,80));
        
        jPnHome.setVisible(false);
        
        jPnHome.setBackground(new Color(236,236,236,50));
        
        jBtnLapHDL.setBackground(new Color(236,236,236,50));
        jBtnLapHDS.setBackground(new Color(236,236,236,50));
        
        jBtnLapHD.setBackground(new Color(236,236,236,50));  
        jBtnDSHD.setBackground(new Color(236,236,236,50));  
        jBtnDSKH.setBackground(new Color(236,236,236,50));  
        jBtnBack.setBackground(new Color(236,236,236,50));
        
        User=new ObjTaiKhoan(objTK.getTenDangNhap(), objTK.getMatKhau(), objTK.getTen(), objTK.getPhanLoai());
    }

    private FormQuanLiBanHang() {
          initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0,0,0,80));
        
        jPnHome.setVisible(false);
        
        jPnHome.setBackground(new Color(236,236,236,50));
        
        jBtnLapHDL.setBackground(new Color(236,236,236,50));
        jBtnLapHDS.setBackground(new Color(236,236,236,50));
        
        jBtnLapHD.setBackground(new Color(236,236,236,50));  
        jBtnDSHD.setBackground(new Color(236,236,236,50));  
        jBtnDSKH.setBackground(new Color(236,236,236,50));  
        jBtnBack.setBackground(new Color(236,236,236,50));
        
        
    }
    
    
    public void setColor(JPanel pn){
        pn.setSize(pn.getWidth()+1, pn.getHeight()+1);
        pn.setBackground(new Color(60,209,127,50));
    }
    public void resetColor(JPanel pn){   
        pn.setSize(pn.getWidth()-1, pn.getHeight()-1);
        pn.setBackground(new Color(236,236,236,50));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnClose = new javax.swing.JLabel();
        jBtnLapHD = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBtnDSHD = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jBtnDSKH = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jBtnBack = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPnHome = new javax.swing.JPanel();
        jBtnLapHDL = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jBtnLapHDS = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnClose.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jBtnClose.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClose.setText("X");
        jBtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 20, 30));

        jBtnLapHD.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLapHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLapHDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLapHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLapHDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLapHDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLapHDMouseReleased(evt);
            }
        });
        jBtnLapHD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Invoice_64px_1.png"))); // NOI18N
        jBtnLapHD.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 10, -1, 80));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Lập hóa đơn");
        jBtnLapHD.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, -1));

        getContentPane().add(jBtnLapHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 180, 120));

        jBtnDSHD.setBackground(new java.awt.Color(153, 153, 153));
        jBtnDSHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDSHDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDSHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDSHDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnDSHDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnDSHDMouseReleased(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Content_64px.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Danh sách hóa đơn");

        javax.swing.GroupLayout jBtnDSHDLayout = new javax.swing.GroupLayout(jBtnDSHD);
        jBtnDSHD.setLayout(jBtnDSHDLayout);
        jBtnDSHDLayout.setHorizontalGroup(
            jBtnDSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDSHDLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnDSHDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jBtnDSHDLayout.setVerticalGroup(
            jBtnDSHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDSHDLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jBtnDSHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, 120));

        jBtnDSKH.setBackground(new java.awt.Color(153, 153, 153));
        jBtnDSKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDSKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDSKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDSKHMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnDSKHMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnDSKHMouseReleased(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Business_Building_68px.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Danh sách khách hàng");

        javax.swing.GroupLayout jBtnDSKHLayout = new javax.swing.GroupLayout(jBtnDSKH);
        jBtnDSKH.setLayout(jBtnDSKHLayout);
        jBtnDSKHLayout.setHorizontalGroup(
            jBtnDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDSKHLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jBtnDSKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jBtnDSKHLayout.setVerticalGroup(
            jBtnDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDSKHLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jBtnDSKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, 120));

        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBackMouseReleased(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBackLayout = new javax.swing.GroupLayout(jBtnBack);
        jBtnBack.setLayout(jBtnBackLayout);
        jBtnBackLayout.setHorizontalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jBtnBackLayout.setVerticalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/navigation.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 80));

        jLabel14.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Get Managed");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Support Management");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Quản lí bán hàng");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 190, 40));

        jLabel20.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Design, Create By Closer Group");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 200, 10));

        jPnHome.setBackground(new java.awt.Color(204, 204, 204));
        jPnHome.setOpaque(false);
        jPnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnLapHDL.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLapHDL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLapHDLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLapHDLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLapHDLMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLapHDLMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLapHDLMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lập hóa đơn lẻ");

        javax.swing.GroupLayout jBtnLapHDLLayout = new javax.swing.GroupLayout(jBtnLapHDL);
        jBtnLapHDL.setLayout(jBtnLapHDLLayout);
        jBtnLapHDLLayout.setHorizontalGroup(
            jBtnLapHDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLapHDLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jBtnLapHDLLayout.setVerticalGroup(
            jBtnLapHDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnLapHDLLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(11, 11, 11))
        );

        jPnHome.add(jBtnLapHDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 38));

        jBtnLapHDS.setBackground(new java.awt.Color(102, 102, 102));
        jBtnLapHDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLapHDSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLapHDSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLapHDSMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLapHDSMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLapHDSMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lập hóa đơn sỉ");

        javax.swing.GroupLayout jBtnLapHDSLayout = new javax.swing.GroupLayout(jBtnLapHDS);
        jBtnLapHDS.setLayout(jBtnLapHDSLayout);
        jBtnLapHDSLayout.setHorizontalGroup(
            jBtnLapHDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLapHDSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jBtnLapHDSLayout.setVerticalGroup(
            jBtnLapHDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnLapHDSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPnHome.add(jBtnLapHDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 190, 38));

        getContentPane().add(jPnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 439, 190, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLapHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLapHD);
    }//GEN-LAST:event_jBtnLapHDMouseEntered

    private void jBtnLapHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLapHD);
    }//GEN-LAST:event_jBtnLapHDMouseExited

    private void jBtnDSHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDSHDMouseEntered
        // TODO add your handling code here:
        setColor(jBtnDSHD);
    }//GEN-LAST:event_jBtnDSHDMouseEntered

    private void jBtnDSHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDSHDMouseExited
        // TODO add your handling code here:
        resetColor(jBtnDSHD);
        
    }//GEN-LAST:event_jBtnDSHDMouseExited

    private void jBtnDSKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDSKHMouseEntered
        // TODO add your handling code here:
        setColor(jBtnDSKH);
    }//GEN-LAST:event_jBtnDSKHMouseEntered

    private void jBtnDSKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDSKHMouseExited
        // TODO add your handling code here:
        resetColor(jBtnDSKH);
    }//GEN-LAST:event_jBtnDSKHMouseExited

    private void jBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtnCloseMouseClicked

    private void jBtnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseEntered

    private void jBtnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseExited

    private void jBtnLapHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLapHD);
    }//GEN-LAST:event_jBtnLapHDMousePressed

    private void jBtnLapHDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDMouseReleased
        // TODO add your handling code here:
        if(jBtnLapHD.getBackground().equals(new Color(236,236,236,50))){
        setColor(jBtnLapHD);
        }
    }//GEN-LAST:event_jBtnLapHDMouseReleased

    private void jBtnDSHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDSHDMousePressed
        // TODO add your handling code here:
        resetColor(jBtnDSHD);
    }//GEN-LAST:event_jBtnDSHDMousePressed

    private void jBtnDSHDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDSHDMouseReleased
        // TODO add your handling code here:
        setColor(jBtnDSHD);
    }//GEN-LAST:event_jBtnDSHDMouseReleased

    private void jBtnDSKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDSKHMousePressed
        // TODO add your handling code here:
        resetColor(jBtnDSKH);
    }//GEN-LAST:event_jBtnDSKHMousePressed

    private void jBtnDSKHMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDSKHMouseReleased
        // TODO add your handling code here:
        setColor(jBtnDSKH);
    }//GEN-LAST:event_jBtnDSKHMouseReleased

    private void jBtnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMousePressed

    private void jBtnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseReleased

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        this.setVisible(false);
        this.dispose();
        new MainForm((User)).setVisible(true);
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnDSHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDSHDMouseClicked
        FormDanhSachHoaDon frmDSHD = new FormDanhSachHoaDon();
        frmDSHD.setVisible(true);
    }//GEN-LAST:event_jBtnDSHDMouseClicked

    private void jBtnDSKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDSKHMouseClicked
        FormQuanLiKhachHang frmQLKH = new FormQuanLiKhachHang();
        frmQLKH.setVisible(true);
    }//GEN-LAST:event_jBtnDSKHMouseClicked

    private void jBtnLapHDSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDSMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLapHDS);
    }//GEN-LAST:event_jBtnLapHDSMouseExited

    private void jBtnLapHDSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDSMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLapHDS);
    }//GEN-LAST:event_jBtnLapHDSMouseEntered

    private void jBtnLapHDLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDLMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLapHDL);
    }//GEN-LAST:event_jBtnLapHDLMouseExited

    private void jBtnLapHDLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDLMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLapHDL);
    }//GEN-LAST:event_jBtnLapHDLMouseEntered

    private void jBtnLapHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDMouseClicked
        // TODO add your handling code here:
        if(jPnHome.isVisible())
            jPnHome.setVisible(false);
        else jPnHome.setVisible(true);
    }//GEN-LAST:event_jBtnLapHDMouseClicked

    private void jBtnLapHDLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDLMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLapHDL);
    }//GEN-LAST:event_jBtnLapHDLMousePressed

    private void jBtnLapHDLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDLMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLapHDL);
    }//GEN-LAST:event_jBtnLapHDLMouseReleased

    private void jBtnLapHDSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDSMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLapHDS);
    }//GEN-LAST:event_jBtnLapHDSMousePressed

    private void jBtnLapHDSMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDSMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLapHDS);
    }//GEN-LAST:event_jBtnLapHDSMouseReleased

    private void jBtnLapHDLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDLMouseClicked
        // TODO add your handling code here:
        FormLapHoaDonLe frmLHDL = new FormLapHoaDonLe();
        frmLHDL.setVisible(true);
    }//GEN-LAST:event_jBtnLapHDLMouseClicked

    private void jBtnLapHDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLapHDSMouseClicked
        // TODO add your handling code here:
        FormLapHoaDonSi frmLHDS = new FormLapHoaDonSi();
        frmLHDS.setVisible(true);
    }//GEN-LAST:event_jBtnLapHDSMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLiBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLiBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack;
    private javax.swing.JLabel jBtnClose;
    private javax.swing.JPanel jBtnDSHD;
    private javax.swing.JPanel jBtnDSKH;
    private javax.swing.JPanel jBtnLapHD;
    private javax.swing.JPanel jBtnLapHDL;
    private javax.swing.JPanel jBtnLapHDS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnHome;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
