/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Control.CtrlXacNhanTinhTrangGiaoHang;
import Edit.Edit;
import Model.ModHoaDonSi;
import Object.ObjHoaDonSi;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DucQuang
 */
public class FormXacNhanTinhTrangGiaoHang extends javax.swing.JFrame {

    Edit editFrm=new Edit();
    ArrayList<ObjHoaDonSi> listDSHDCG = new ArrayList<>();
    ArrayList<ObjHoaDonSi> listDSHDDG = new ArrayList<>();
    ObjHoaDonSi ObjHDS = new ObjHoaDonSi();
    ModHoaDonSi ModHDS = new ModHoaDonSi();
    CtrlXacNhanTinhTrangGiaoHang CtrlXNTTGH = new CtrlXacNhanTinhTrangGiaoHang();
    /**
     * Creates new form FormXacNhanTinhTrangGiaoHang
     */
    public FormXacNhanTinhTrangGiaoHang() {
        initComponents();
        setLocationRelativeTo(null);
        
        jPanel10.setBackground((new Color(0,0,0,0)));
        
        JPanel ListTitle[]=new JPanel[]{jPnDSHDchuagiao,jPnDSHDdagiao,jPnThongtinHD,jPnTracuuHDchuagiao,jPnTracuuHDdagiao};
        editFrm.MakeTransparentTitle(ListTitle);
        
        JPanel ListPanel[]=new JPanel[]{jPanel1,jPanel2,jPanel4,jPanel9,jPanel3};
        editFrm.MakeTransparentPanel(ListPanel);
        
        JPanel ListButton[]=new JPanel[]{jBtnBack,jBtnLamMoichuagiao,jBtnLamMoidagiao,jBtnTimKiemHDchuagiao,jBtnTimKiemHDdagiao,jBtnXacNhanDaGiao,jBtnXacNhanChuaGiao,jBtnXemchitiet};
        editFrm.MakeTransparentButton(ListButton);   
        
        editFrm.MakeTransparentTable(jScrDSHDchuagiao, jTbDSHDchuagiao);
        editFrm.MakeTransparentTable(jScrDSHDdagiao, jTbDSHDdagiao);
        FormLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jBtnBack = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jBtnLamMoichuagiao = new javax.swing.JPanel();
        jlblLamMoiCG = new javax.swing.JLabel();
        jBtnTimKiemHDchuagiao = new javax.swing.JPanel();
        jlblTimKiemCG = new javax.swing.JLabel();
        jBtnLamMoidagiao = new javax.swing.JPanel();
        jlblLamMoiDG = new javax.swing.JLabel();
        jBtnTimKiemHDdagiao = new javax.swing.JPanel();
        jlblTimKiemDG = new javax.swing.JLabel();
        jBtnXemchitiet = new javax.swing.JPanel();
        jlblXemChiTiet = new javax.swing.JLabel();
        jBtnXacNhanChuaGiao = new javax.swing.JPanel();
        jlblXacNhanChuaGiao = new javax.swing.JLabel();
        jBtnXacNhanDaGiao = new javax.swing.JPanel();
        jlblXacNhanDaGiao = new javax.swing.JLabel();
        jScrDSHDchuagiao = new javax.swing.JScrollPane();
        jTbDSHDchuagiao = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPnDSHDchuagiao = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrDSHDdagiao = new javax.swing.JScrollPane();
        jTbDSHDdagiao = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPnDSHDdagiao = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtSoHD = new javax.swing.JTextField();
        jtxtTenKH = new javax.swing.JTextField();
        jtxtMaKH = new javax.swing.JTextField();
        jtxtSDT = new javax.swing.JTextField();
        jdtcNgayDat = new com.toedter.calendar.JDateChooser();
        jdtcNgayGiao = new com.toedter.calendar.JDateChooser();
        jtxtTinhTrangGiaoHang = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtDiaChi = new javax.swing.JTextArea();
        jPnThongtinHD = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtxtTongTien = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPnTracuuHDdagiao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxtTimKiemDG = new javax.swing.JTextField();
        jcbbTimTheoDG = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPnTracuuHDchuagiao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtTimKiemCG = new javax.swing.JTextField();
        jcbbTimTheoCG = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đơn chưa giao"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đã giao"));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBackMouseReleased(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnBackLayout = new javax.swing.GroupLayout(jBtnBack);
        jBtnBack.setLayout(jBtnBackLayout);
        jBtnBackLayout.setHorizontalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnBackLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBtnBackLayout.setVerticalGroup(
            jBtnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jBtnLamMoichuagiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLamMoichuagiao.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnLamMoichuagiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLamMoichuagiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLamMoichuagiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLamMoichuagiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLamMoichuagiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLamMoichuagiaoMouseReleased(evt);
            }
        });

        jlblLamMoiCG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblLamMoiCG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Refresh_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLamMoichuagiaoLayout = new javax.swing.GroupLayout(jBtnLamMoichuagiao);
        jBtnLamMoichuagiao.setLayout(jBtnLamMoichuagiaoLayout);
        jBtnLamMoichuagiaoLayout.setHorizontalGroup(
            jBtnLamMoichuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnLamMoichuagiaoLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jlblLamMoiCG)
                .addGap(37, 37, 37))
        );
        jBtnLamMoichuagiaoLayout.setVerticalGroup(
            jBtnLamMoichuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblLamMoiCG, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnLamMoichuagiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 190, 120, 65));

        jBtnTimKiemHDchuagiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTimKiemHDchuagiao.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnTimKiemHDchuagiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDchuagiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDchuagiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDchuagiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDchuagiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDchuagiaoMouseReleased(evt);
            }
        });

        jlblTimKiemCG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTimKiemCG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnTimKiemHDchuagiaoLayout = new javax.swing.GroupLayout(jBtnTimKiemHDchuagiao);
        jBtnTimKiemHDchuagiao.setLayout(jBtnTimKiemHDchuagiaoLayout);
        jBtnTimKiemHDchuagiaoLayout.setHorizontalGroup(
            jBtnTimKiemHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTimKiemHDchuagiaoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlblTimKiemCG, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jBtnTimKiemHDchuagiaoLayout.setVerticalGroup(
            jBtnTimKiemHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblTimKiemCG, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnTimKiemHDchuagiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 190, 120, 65));

        jBtnLamMoidagiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnLamMoidagiao.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnLamMoidagiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLamMoidagiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLamMoidagiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLamMoidagiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnLamMoidagiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLamMoidagiaoMouseReleased(evt);
            }
        });

        jlblLamMoiDG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblLamMoiDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Refresh_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnLamMoidagiaoLayout = new javax.swing.GroupLayout(jBtnLamMoidagiao);
        jBtnLamMoidagiao.setLayout(jBtnLamMoidagiaoLayout);
        jBtnLamMoidagiaoLayout.setHorizontalGroup(
            jBtnLamMoidagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnLamMoidagiaoLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jlblLamMoiDG)
                .addGap(37, 37, 37))
        );
        jBtnLamMoidagiaoLayout.setVerticalGroup(
            jBtnLamMoidagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblLamMoiDG, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnLamMoidagiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 190, 120, 65));

        jBtnTimKiemHDdagiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTimKiemHDdagiao.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnTimKiemHDdagiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDdagiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDdagiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDdagiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDdagiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTimKiemHDdagiaoMouseReleased(evt);
            }
        });

        jlblTimKiemDG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTimKiemDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_45px.png"))); // NOI18N

        javax.swing.GroupLayout jBtnTimKiemHDdagiaoLayout = new javax.swing.GroupLayout(jBtnTimKiemHDdagiao);
        jBtnTimKiemHDdagiao.setLayout(jBtnTimKiemHDdagiaoLayout);
        jBtnTimKiemHDdagiaoLayout.setHorizontalGroup(
            jBtnTimKiemHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTimKiemHDdagiaoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlblTimKiemDG, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jBtnTimKiemHDdagiaoLayout.setVerticalGroup(
            jBtnTimKiemHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblTimKiemDG, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jBtnTimKiemHDdagiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 190, 120, 65));

        jBtnXemchitiet.setBackground(new java.awt.Color(153, 153, 153));
        jBtnXemchitiet.setPreferredSize(new java.awt.Dimension(102, 50));
        jBtnXemchitiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXemchitietMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXemchitietMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXemchitietMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXemchitietMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXemchitietMouseReleased(evt);
            }
        });

        jlblXemChiTiet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblXemChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        jlblXemChiTiet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblXemChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_View_Details_55px_1.png"))); // NOI18N
        jlblXemChiTiet.setText("Xem chi tiết");

        javax.swing.GroupLayout jBtnXemchitietLayout = new javax.swing.GroupLayout(jBtnXemchitiet);
        jBtnXemchitiet.setLayout(jBtnXemchitietLayout);
        jBtnXemchitietLayout.setHorizontalGroup(
            jBtnXemchitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblXemChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jBtnXemchitietLayout.setVerticalGroup(
            jBtnXemchitietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnXemchitietLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblXemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jBtnXemchitiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 642, 190, 65));

        jBtnXacNhanChuaGiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnXacNhanChuaGiao.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnXacNhanChuaGiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXacNhanChuaGiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXacNhanChuaGiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXacNhanChuaGiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXacNhanChuaGiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXacNhanChuaGiaoMouseReleased(evt);
            }
        });

        jlblXacNhanChuaGiao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblXacNhanChuaGiao.setForeground(new java.awt.Color(255, 255, 255));
        jlblXacNhanChuaGiao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblXacNhanChuaGiao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Tick_Box_40px.png"))); // NOI18N
        jlblXacNhanChuaGiao.setText("Xác nhận chưa giao");

        javax.swing.GroupLayout jBtnXacNhanChuaGiaoLayout = new javax.swing.GroupLayout(jBtnXacNhanChuaGiao);
        jBtnXacNhanChuaGiao.setLayout(jBtnXacNhanChuaGiaoLayout);
        jBtnXacNhanChuaGiaoLayout.setHorizontalGroup(
            jBtnXacNhanChuaGiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblXacNhanChuaGiao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jBtnXacNhanChuaGiaoLayout.setVerticalGroup(
            jBtnXacNhanChuaGiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnXacNhanChuaGiaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblXacNhanChuaGiao)
                .addContainerGap())
        );

        jlblXacNhanChuaGiao.getAccessibleContext().setAccessibleName("Xác nhận chưa giao");

        getContentPane().add(jBtnXacNhanChuaGiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 642, 190, 65));

        jBtnXacNhanDaGiao.setBackground(new java.awt.Color(153, 153, 153));
        jBtnXacNhanDaGiao.setPreferredSize(new java.awt.Dimension(105, 50));
        jBtnXacNhanDaGiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXacNhanDaGiaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnXacNhanDaGiaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnXacNhanDaGiaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnXacNhanDaGiaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnXacNhanDaGiaoMouseReleased(evt);
            }
        });

        jlblXacNhanDaGiao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblXacNhanDaGiao.setForeground(new java.awt.Color(255, 255, 255));
        jlblXacNhanDaGiao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblXacNhanDaGiao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Tick_Box_40px.png"))); // NOI18N
        jlblXacNhanDaGiao.setText("Xác nhận đã giao");

        javax.swing.GroupLayout jBtnXacNhanDaGiaoLayout = new javax.swing.GroupLayout(jBtnXacNhanDaGiao);
        jBtnXacNhanDaGiao.setLayout(jBtnXacNhanDaGiaoLayout);
        jBtnXacNhanDaGiaoLayout.setHorizontalGroup(
            jBtnXacNhanDaGiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblXacNhanDaGiao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jBtnXacNhanDaGiaoLayout.setVerticalGroup(
            jBtnXacNhanDaGiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnXacNhanDaGiaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblXacNhanDaGiao)
                .addContainerGap())
        );

        getContentPane().add(jBtnXacNhanDaGiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 642, 190, 65));

        jScrDSHDchuagiao.setWheelScrollingEnabled(false);

        jTbDSHDchuagiao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số hóa đơn", "Ngày đặt", "Ngày giao dự kiến", "Tình trạng"
            }
        ));
        jTbDSHDchuagiao.setSelectionBackground(new java.awt.Color(218, 223, 225));
        jTbDSHDchuagiao.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTbDSHDchuagiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbDSHDchuagiaoMouseClicked(evt);
            }
        });
        jScrDSHDchuagiao.setViewportView(jTbDSHDchuagiao);

        getContentPane().add(jScrDSHDchuagiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 313, 420, 388));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPnDSHDchuagiao.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Danh sách hóa đơn chưa giao:");

        javax.swing.GroupLayout jPnDSHDchuagiaoLayout = new javax.swing.GroupLayout(jPnDSHDchuagiao);
        jPnDSHDchuagiao.setLayout(jPnDSHDchuagiaoLayout);
        jPnDSHDchuagiaoLayout.setHorizontalGroup(
            jPnDSHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSHDchuagiaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPnDSHDchuagiaoLayout.setVerticalGroup(
            jPnDSHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPnDSHDchuagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPnDSHDchuagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 280, 430, 427));

        jTbDSHDdagiao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số hóa đơn", "Ngày đặt", "Ngày giao dự kiến", "Tình trạng"
            }
        ));
        jTbDSHDdagiao.setSelectionBackground(new java.awt.Color(218, 223, 225));
        jTbDSHDdagiao.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTbDSHDdagiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbDSHDdagiaoMouseClicked(evt);
            }
        });
        jScrDSHDdagiao.setViewportView(jTbDSHDdagiao);

        getContentPane().add(jScrDSHDdagiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 313, 420, 389));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPnDSHDdagiao.setBackground(new java.awt.Color(0, 204, 204));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Danh sách hóa đơn đã giao:");

        javax.swing.GroupLayout jPnDSHDdagiaoLayout = new javax.swing.GroupLayout(jPnDSHDdagiao);
        jPnDSHDdagiao.setLayout(jPnDSHDdagiaoLayout);
        jPnDSHDdagiaoLayout.setHorizontalGroup(
            jPnDSHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDSHDdagiaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPnDSHDdagiaoLayout.setVerticalGroup(
            jPnDSHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jLabel17.getAccessibleContext().setAccessibleName("Danh sách hóa đơn đã giao:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPnDSHDdagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPnDSHDdagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 280, 430, 427));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Số hóa đơn:");

        jLabel7.setText("Tên khách hàng:");

        jLabel8.setText("Mã khách hàng:");

        jLabel9.setText("Địa chỉ:");

        jLabel10.setText("Số điện thoại:");

        jLabel11.setText("Ngày đặt:");

        jLabel12.setText("Tình trạng giao hàng:");

        jLabel13.setText("Ngày giao dự kiến:");

        jtxtDiaChi.setColumns(20);
        jtxtDiaChi.setRows(5);
        jScrollPane3.setViewportView(jtxtDiaChi);

        jPnThongtinHD.setBackground(new java.awt.Color(0, 204, 204));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Thông tin hóa đơn:");

        javax.swing.GroupLayout jPnThongtinHDLayout = new javax.swing.GroupLayout(jPnThongtinHD);
        jPnThongtinHD.setLayout(jPnThongtinHDLayout);
        jPnThongtinHDLayout.setHorizontalGroup(
            jPnThongtinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnThongtinHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPnThongtinHDLayout.setVerticalGroup(
            jPnThongtinHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel19.setText("Tổng Tiền:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdtcNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(46, 46, 46)
                                    .addComponent(jtxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtTenKH)
                                        .addComponent(jtxtSoHD)
                                        .addComponent(jtxtMaKH)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jdtcNgayGiao, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(jtxtTinhTrangGiaoHang, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(jtxtTongTien)))))
                    .addComponent(jPnThongtinHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPnThongtinHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdtcNgayDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtTinhTrangGiaoHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdtcNgayGiao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtxtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 400, 580));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPnTracuuHDdagiao.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tra cứu hóa đơn đã giao:");

        javax.swing.GroupLayout jPnTracuuHDdagiaoLayout = new javax.swing.GroupLayout(jPnTracuuHDdagiao);
        jPnTracuuHDdagiao.setLayout(jPnTracuuHDdagiaoLayout);
        jPnTracuuHDdagiaoLayout.setHorizontalGroup(
            jPnTracuuHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTracuuHDdagiaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPnTracuuHDdagiaoLayout.setVerticalGroup(
            jPnTracuuHDdagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jLabel15.setText("Từ tìm kiếm:");

        jLabel16.setText("Tìm theo:");

        jtxtTimKiemDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTimKiemDGActionPerformed(evt);
            }
        });

        jcbbTimTheoDG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Số hóa đơn", "Tên khách hàng" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTimKiemDG, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jcbbTimTheoDG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPnTracuuHDdagiao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPnTracuuHDdagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jcbbTimTheoDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtxtTimKiemDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 50, 430, 220));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Tìm theo:");

        jPnTracuuHDchuagiao.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tra cứu hóa đơn chưa giao :");

        javax.swing.GroupLayout jPnTracuuHDchuagiaoLayout = new javax.swing.GroupLayout(jPnTracuuHDchuagiao);
        jPnTracuuHDchuagiao.setLayout(jPnTracuuHDchuagiaoLayout);
        jPnTracuuHDchuagiaoLayout.setHorizontalGroup(
            jPnTracuuHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTracuuHDchuagiaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPnTracuuHDchuagiaoLayout.setVerticalGroup(
            jPnTracuuHDchuagiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel5.setText("Từ tìm kiếm:");

        jtxtTimKiemCG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTimKiemCGActionPerformed(evt);
            }
        });

        jcbbTimTheoCG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Số hóa đơn", "Tên khách hàng" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtTimKiemCG, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbbTimTheoCG, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPnTracuuHDchuagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPnTracuuHDchuagiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbbTimTheoCG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtTimKiemCG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 50, 430, 220));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 720));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo-530024.jpeg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setPreferredSize(new java.awt.Dimension(1320, 720));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnBackMouseClicked

    private void jBtnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseEntered

    private void jBtnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseExited

    private void jBtnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMousePressed

    private void jBtnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBackMouseReleased
        // TODO add your handling code here:
        setColor(jBtnBack);
    }//GEN-LAST:event_jBtnBackMouseReleased

    private void jtxtTimKiemCGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTimKiemCGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTimKiemCGActionPerformed

    private void jtxtTimKiemDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTimKiemDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTimKiemDGActionPerformed

    private void jBtnTimKiemHDchuagiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDchuagiaoMouseClicked
        if(!jtxtTimKiemCG.equals("")){
            if(jcbbTimTheoCG.getSelectedItem().toString().equals("Số hóa đơn"))
        {
            HienThiDSHoaDonChuaGiao(CtrlXNTTGH.SearchHDSCGByID(jtxtTimKiemCG.getText()));
        }else {
            HienThiDSHoaDonChuaGiao(CtrlXNTTGH.SearchHDSCGByName(jtxtTimKiemCG.getText()));
        }
        }else{
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá trị bạn muốn tìm kiếm", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnTimKiemHDchuagiaoMouseClicked

    private void jBtnTimKiemHDchuagiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDchuagiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTimKiemHDchuagiao);
    }//GEN-LAST:event_jBtnTimKiemHDchuagiaoMouseEntered

    private void jBtnTimKiemHDchuagiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDchuagiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTimKiemHDchuagiao);
    }//GEN-LAST:event_jBtnTimKiemHDchuagiaoMouseExited

    private void jBtnTimKiemHDchuagiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDchuagiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTimKiemHDchuagiao);
    }//GEN-LAST:event_jBtnTimKiemHDchuagiaoMousePressed

    private void jBtnTimKiemHDchuagiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDchuagiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTimKiemHDchuagiao);
    }//GEN-LAST:event_jBtnTimKiemHDchuagiaoMouseReleased

    private void jBtnLamMoichuagiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoichuagiaoMouseClicked
        jtxtTimKiemCG.setText("");
        jcbbTimTheoCG.setSelectedIndex(0);
        HienThiDSHoaDonChuaGiao(CtrlXNTTGH.LayDSHoaDonChuaGiao());
    }//GEN-LAST:event_jBtnLamMoichuagiaoMouseClicked

    private void jBtnLamMoichuagiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoichuagiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLamMoichuagiao);
    }//GEN-LAST:event_jBtnLamMoichuagiaoMouseEntered

    private void jBtnLamMoichuagiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoichuagiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLamMoichuagiao);
    }//GEN-LAST:event_jBtnLamMoichuagiaoMouseExited

    private void jBtnLamMoichuagiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoichuagiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLamMoichuagiao);
    }//GEN-LAST:event_jBtnLamMoichuagiaoMousePressed

    private void jBtnLamMoichuagiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoichuagiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLamMoichuagiao);
    }//GEN-LAST:event_jBtnLamMoichuagiaoMouseReleased

    private void jBtnTimKiemHDdagiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDdagiaoMouseClicked
        // TODO add your handling code here:
        if(!jtxtTimKiemDG.equals("")){
            if(jcbbTimTheoDG.getSelectedItem().toString().equals("Số hóa đơn"))
        {
            HienThiDSHoaDonChuaGiao(CtrlXNTTGH.SearchHDSDGByID(jtxtTimKiemDG.getText()));
        }else {
            HienThiDSHoaDonChuaGiao(CtrlXNTTGH.SearchHDSDGByName(jtxtTimKiemDG.getText()));
        }
        }else{
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá trị bạn muốn tìm kiếm", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnTimKiemHDdagiaoMouseClicked

    private void jBtnTimKiemHDdagiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDdagiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTimKiemHDdagiao);
    }//GEN-LAST:event_jBtnTimKiemHDdagiaoMouseEntered

    private void jBtnTimKiemHDdagiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDdagiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTimKiemHDdagiao);
    }//GEN-LAST:event_jBtnTimKiemHDdagiaoMouseExited

    private void jBtnTimKiemHDdagiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDdagiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTimKiemHDdagiao);
    }//GEN-LAST:event_jBtnTimKiemHDdagiaoMousePressed

    private void jBtnTimKiemHDdagiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemHDdagiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTimKiemHDdagiao);
    }//GEN-LAST:event_jBtnTimKiemHDdagiaoMouseReleased

    private void jBtnLamMoidagiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoidagiaoMouseClicked
        jtxtTimKiemDG.setText("");
        jcbbTimTheoDG.setSelectedIndex(0);
        HienThiDSHoaDonDaGiao(CtrlXNTTGH.LayDSHoaDonDaGiao());
    }//GEN-LAST:event_jBtnLamMoidagiaoMouseClicked

    private void jBtnLamMoidagiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoidagiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnLamMoidagiao);
    }//GEN-LAST:event_jBtnLamMoidagiaoMouseEntered

    private void jBtnLamMoidagiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoidagiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnLamMoidagiao);
    }//GEN-LAST:event_jBtnLamMoidagiaoMouseExited

    private void jBtnLamMoidagiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoidagiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnLamMoidagiao);
    }//GEN-LAST:event_jBtnLamMoidagiaoMousePressed

    private void jBtnLamMoidagiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLamMoidagiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnLamMoidagiao);
    }//GEN-LAST:event_jBtnLamMoidagiaoMouseReleased

    private void jBtnXemchitietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemchitietMouseClicked
        // TODO add your handling code here:
        FormChiTietHoaDonSi frmCTHDS = new FormChiTietHoaDonSi();
        frmCTHDS.SoHDS=jtxtSoHD.getText();
        frmCTHDS.setVisible(true);
    }//GEN-LAST:event_jBtnXemchitietMouseClicked

    private void jBtnXemchitietMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemchitietMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXemchitiet);
    }//GEN-LAST:event_jBtnXemchitietMouseEntered

    private void jBtnXemchitietMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemchitietMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXemchitiet);
    }//GEN-LAST:event_jBtnXemchitietMouseExited

    private void jBtnXemchitietMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemchitietMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXemchitiet);
    }//GEN-LAST:event_jBtnXemchitietMousePressed

    private void jBtnXemchitietMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemchitietMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXemchitiet);
    }//GEN-LAST:event_jBtnXemchitietMouseReleased

    private void jBtnXacNhanDaGiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacNhanDaGiaoMouseClicked
        // TODO add your handling code here:
        String s = jtxtSoHD.getText();
        try{
            if(ModHDS.UpdateTTGHDG(s))
        {
            FormLoad();
            JOptionPane.showMessageDialog(this, "Xác nhận đã giao hàng cho hóa đơn có mã \""+ s +"\" thành công.", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Xác nhận đã giao hàng cho hóa đơn có mã \""+ s +"\" thất bại. Mã lỗi: " + e.getMessage(), "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jBtnXacNhanDaGiaoMouseClicked

    private void jBtnXacNhanDaGiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacNhanDaGiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXacNhanDaGiao);
    }//GEN-LAST:event_jBtnXacNhanDaGiaoMouseEntered

    private void jBtnXacNhanDaGiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacNhanDaGiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXacNhanDaGiao);
    }//GEN-LAST:event_jBtnXacNhanDaGiaoMouseExited

    private void jBtnXacNhanDaGiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacNhanDaGiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXacNhanDaGiao);
    }//GEN-LAST:event_jBtnXacNhanDaGiaoMousePressed

    private void jBtnXacNhanDaGiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacNhanDaGiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXacNhanDaGiao);
    }//GEN-LAST:event_jBtnXacNhanDaGiaoMouseReleased

    private void jTbDSHDchuagiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbDSHDchuagiaoMouseClicked
        // TODO add your handling code here:
        BindingCG();
        EnableComponent(true);
    }//GEN-LAST:event_jTbDSHDchuagiaoMouseClicked

    private void jTbDSHDdagiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbDSHDdagiaoMouseClicked
        // TODO add your handling code here:
        BindingDG();
        EnableComponent(false);
    }//GEN-LAST:event_jTbDSHDdagiaoMouseClicked

    private void jBtnXacNhanChuaGiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacNhanChuaGiaoMouseClicked
        // TODO add your handling code here:
        String s = jtxtSoHD.getText();
        try{
            if(ModHDS.UpdateTTGHCG(s))
                {
                    FormLoad();
                    JOptionPane.showMessageDialog(this, "Xác nhận chưa giao hàng cho hóa đơn có mã \""+ s +"\" thành công.", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Xác nhận chưa giao hàng cho hóa đơn có mã \""+ s +"\" thất bại. Mã lỗi: "+e.getMessage(), "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jBtnXacNhanChuaGiaoMouseClicked

    private void jBtnXacNhanChuaGiaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacNhanChuaGiaoMouseEntered
        // TODO add your handling code here:
        setColor(jBtnXacNhanChuaGiao);
    }//GEN-LAST:event_jBtnXacNhanChuaGiaoMouseEntered

    private void jBtnXacNhanChuaGiaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacNhanChuaGiaoMouseExited
        // TODO add your handling code here:
        resetColor(jBtnXacNhanChuaGiao);
    }//GEN-LAST:event_jBtnXacNhanChuaGiaoMouseExited

    private void jBtnXacNhanChuaGiaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacNhanChuaGiaoMousePressed
        // TODO add your handling code here:
        resetColor(jBtnXacNhanChuaGiao);
    }//GEN-LAST:event_jBtnXacNhanChuaGiaoMousePressed

    private void jBtnXacNhanChuaGiaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXacNhanChuaGiaoMouseReleased
        // TODO add your handling code here:
        setColor(jBtnXacNhanChuaGiao);
    }//GEN-LAST:event_jBtnXacNhanChuaGiaoMouseReleased

    public void setColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()+1, pn.getHeight()+1);
        pn.setBackground(new Color(60,209,127,50));
        }
    }
    public void resetColor(JPanel pn){
        if(pn.isEnabled()){
        pn.setSize(pn.getWidth()-1, pn.getHeight()-1);
        pn.setBackground(new Color(153,153,153,180));
        }
    }
    public void HienThiDSHoaDonChuaGiao(ResultSet rs){
        listDSHDCG.clear();
        DefaultTableModel model = (DefaultTableModel) jTbDSHDchuagiao.getModel();
        model.getDataVector().removeAllElements();
        try{
            while(rs.next()){
                ObjHoaDonSi itemHDS;
                itemHDS=new ObjHoaDonSi(rs.getString("SoHDS"),rs.getString("MaKH"),rs.getString("TenKH"),rs.getString("DiaChi"),rs.getString("SDT"),rs.getDate("NgayLap"),rs.getDate("NgayGiaoDuKien"),rs.getInt("TongTien"),rs.getString("TinhTrangGiaoHang"));
                listDSHDCG.add(itemHDS);
                Vector v = new Vector();
                v.add(itemHDS.getSoHDS());
                v.add(itemHDS.getNgayLap());
                v.add(itemHDS.getNgayGiaoDuKien());
                v.add(itemHDS.getTinhTrangGiaoHang());
                model.addRow(v);
            }
        } catch (SQLException ex) {
            System.out.println("Ngoại lệ tại FormXacNhanTinhTrangGiaoHang.HienThiDSHoaDonChuaGiao: "+ex.getMessage());
        }
        finally{
            CtrlXNTTGH.CloseConnection();
        }
        jTbDSHDchuagiao.changeSelection(0,0,false,false);
    }
    
    public void HienThiDSHoaDonDaGiao(ResultSet rs){
        listDSHDDG.clear();
        DefaultTableModel model = (DefaultTableModel) jTbDSHDdagiao.getModel();
        model.getDataVector().removeAllElements();
        try{
            while(rs.next()){
                ObjHoaDonSi itemHDS;
                itemHDS=new ObjHoaDonSi(rs.getString("SoHDS"),rs.getString("MaKH"),rs.getString("TenKH"),rs.getString("DiaChi"),rs.getString("SDT"),rs.getDate("NgayLap"),rs.getDate("NgayGiaoDuKien"),rs.getInt("TongTien"),rs.getString("TinhTrangGiaoHang"));
                listDSHDDG.add(itemHDS);
                Vector v = new Vector();
                v.add(itemHDS.getSoHDS());
                v.add(itemHDS.getNgayLap());
                v.add(itemHDS.getNgayGiaoDuKien());
                v.add(itemHDS.getTinhTrangGiaoHang());
                model.addRow(v);
            }
        } catch (SQLException ex) {
            System.out.println("Ngoại lệ tại FormXacNhanTinhTrangGiaoHang.HienThiDSHoaDonDaGiao: "+ex.getMessage());
        }
        finally{
            CtrlXNTTGH.CloseConnection();
        }
        jTbDSHDdagiao.changeSelection(0,0,false,false);
    }
    
    public void BindingCG(){
        jTbDSHDdagiao.clearSelection();
        try{
            int viewRow = jTbDSHDchuagiao.getSelectedRow();
            int modelRow= jTbDSHDchuagiao.convertRowIndexToModel(viewRow);
             if(viewRow>-1){
                  jtxtSoHD.setText(listDSHDCG.get(modelRow).getSoHDS());
                  jtxtMaKH.setText(listDSHDCG.get(modelRow).getMaKH());
                  jtxtTenKH.setText(listDSHDCG.get(modelRow).getTenKH());
                  jtxtDiaChi.setText(listDSHDCG.get(modelRow).getDiaChi());
                  jtxtSDT.setText(listDSHDCG.get(modelRow).getSDT());
                  jdtcNgayDat.setDate(listDSHDCG.get(modelRow).getNgayLap());
                  jtxtTinhTrangGiaoHang.setText(listDSHDCG.get(modelRow).getTinhTrangGiaoHang());
                  jdtcNgayGiao.setDate(listDSHDCG.get(modelRow).getNgayGiaoDuKien());
                  jtxtTongTien.setText(String.valueOf(listDSHDCG.get(modelRow).getTongTien()));
             }
        }
        catch(Exception ex){
            System.out.println("Ngoại lệ tại FormXacNhanTinhTrangGiaoHang.BindingCG: "+ex.getMessage());
        }
    }
    
    
    public void BindingDG(){
        jTbDSHDchuagiao.clearSelection();
        try{
            int viewRow = jTbDSHDdagiao.getSelectedRow();
            int modelRow= jTbDSHDdagiao.convertRowIndexToModel(viewRow);
             if(viewRow>-1){
                  jtxtSoHD.setText(listDSHDDG.get(modelRow).getSoHDS());
                  jtxtMaKH.setText(listDSHDDG.get(modelRow).getMaKH());
                  jtxtTenKH.setText(listDSHDDG.get(modelRow).getTenKH());
                  jtxtDiaChi.setText(listDSHDDG.get(modelRow).getDiaChi());
                  jtxtSDT.setText(listDSHDDG.get(modelRow).getSDT());
                  jdtcNgayDat.setDate(listDSHDDG.get(modelRow).getNgayLap());
                  jtxtTinhTrangGiaoHang.setText(listDSHDDG.get(modelRow).getTinhTrangGiaoHang());
                  jdtcNgayGiao.setDate(listDSHDDG.get(modelRow).getNgayGiaoDuKien());
                  jtxtTongTien.setText(String.valueOf(listDSHDDG.get(modelRow).getTongTien()));
             }
        }
        catch(Exception ex){
            System.out.println("Ngoại lệ tại FormXacNhanTinhTrangGiaoHang.BindingDG: "+ex.getMessage());
        }
    }
    
    public void EnableComponent(boolean Active){
        jBtnXacNhanChuaGiao.setVisible(!Active);
        jlblXacNhanChuaGiao.setVisible(!Active);
        jBtnXacNhanDaGiao.setVisible(Active);
        jlblXacNhanDaGiao.setVisible(Active);
    }
    
    public void FormLoad(){
        HienThiDSHoaDonChuaGiao(CtrlXNTTGH.LayDSHoaDonChuaGiao());
        HienThiDSHoaDonDaGiao(CtrlXNTTGH.LayDSHoaDonDaGiao());
        BindingCG();
        EnableComponent(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormXacNhanTinhTrangGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormXacNhanTinhTrangGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormXacNhanTinhTrangGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormXacNhanTinhTrangGiaoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormXacNhanTinhTrangGiaoHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnBack;
    private javax.swing.JPanel jBtnLamMoichuagiao;
    private javax.swing.JPanel jBtnLamMoidagiao;
    private javax.swing.JPanel jBtnTimKiemHDchuagiao;
    private javax.swing.JPanel jBtnTimKiemHDdagiao;
    private javax.swing.JPanel jBtnXacNhanChuaGiao;
    private javax.swing.JPanel jBtnXacNhanDaGiao;
    private javax.swing.JPanel jBtnXemchitiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPnDSHDchuagiao;
    private javax.swing.JPanel jPnDSHDdagiao;
    private javax.swing.JPanel jPnThongtinHD;
    private javax.swing.JPanel jPnTracuuHDchuagiao;
    private javax.swing.JPanel jPnTracuuHDdagiao;
    private javax.swing.JScrollPane jScrDSHDchuagiao;
    private javax.swing.JScrollPane jScrDSHDdagiao;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTbDSHDchuagiao;
    private javax.swing.JTable jTbDSHDdagiao;
    private javax.swing.JComboBox<String> jcbbTimTheoCG;
    private javax.swing.JComboBox<String> jcbbTimTheoDG;
    private com.toedter.calendar.JDateChooser jdtcNgayDat;
    private com.toedter.calendar.JDateChooser jdtcNgayGiao;
    private javax.swing.JLabel jlblLamMoiCG;
    private javax.swing.JLabel jlblLamMoiDG;
    private javax.swing.JLabel jlblTimKiemCG;
    private javax.swing.JLabel jlblTimKiemDG;
    private javax.swing.JLabel jlblXacNhanChuaGiao;
    private javax.swing.JLabel jlblXacNhanDaGiao;
    private javax.swing.JLabel jlblXemChiTiet;
    private javax.swing.JTextArea jtxtDiaChi;
    private javax.swing.JTextField jtxtMaKH;
    private javax.swing.JTextField jtxtSDT;
    private javax.swing.JTextField jtxtSoHD;
    private javax.swing.JTextField jtxtTenKH;
    private javax.swing.JTextField jtxtTimKiemCG;
    private javax.swing.JTextField jtxtTimKiemDG;
    private javax.swing.JTextField jtxtTinhTrangGiaoHang;
    private javax.swing.JTextField jtxtTongTien;
    // End of variables declaration//GEN-END:variables
}
