/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ThaiNguyen
 */
public class MainForm extends javax.swing.JFrame {
    
    int xx,yy;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        
        jPanel1.setBackground(new Color(0,0,0,80));
        
        jPnHome.setVisible(false);
        
        jPnHome.setBackground(new Color(236,236,236,50));
        
        jBtnTaoTK.setBackground(new Color(236,236,236,50));
        jBtnDangxuat.setBackground(new Color(236,236,236,50));
        jBtnDoiMK.setBackground(new Color(236,236,236,50));
        jBtnThongtin.setBackground(new Color(236,236,236,50));
        
        jBtnThietlap.setBackground(new Color(236,236,236,50));
        jBtnNguoidung.setBackground(new Color(236,236,236,50));  
        jBtnThongke.setBackground(new Color(236,236,236,50));  
        jBtnBanhang.setBackground(new Color(236,236,236,50));  
        jBtnKhohang.setBackground(new Color(236,236,236,50));  
        jBtnKetoan.setBackground(new Color(236,236,236,50));  
        jBtn7.setBackground(new Color(236,236,236,50));
    }
    
    public void setColor(JPanel pn){
        pn.setSize(pn.getWidth()+1, pn.getHeight()+1);
        pn.setBackground(new Color(60,209,127,50));
    }
    public void resetColor(JPanel pn){   
        pn.setSize(pn.getWidth()-1, pn.getHeight()-1);
        pn.setBackground(new Color(236,236,236,50));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnClose = new javax.swing.JLabel();
        jBtnBanhang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jBtnThongke = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jBtnKhohang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jBtnNguoidung = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jBtnKetoan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jBtnThietlap = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jBtn7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPnHome = new javax.swing.JPanel();
        jBtnTaoTK = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jBtnDangxuat = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jBtnDoiMK = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jBtnThongtin = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnClose.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jBtnClose.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClose.setText("X");
        jBtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 20, 30));

        jBtnBanhang.setBackground(new java.awt.Color(153, 153, 153));
        jBtnBanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBanhangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseReleased(evt);
            }
        });
        jBtnBanhang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Shopping_Cart_64px_3.png"))); // NOI18N
        jBtnBanhang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 60, 60));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Bán hàng");
        jBtnBanhang.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnBanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 180, 120));

        jBtnThongke.setBackground(new java.awt.Color(153, 153, 153));
        jBtnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongkeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseReleased(evt);
            }
        });
        jBtnThongke.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Statistics_64px.png"))); // NOI18N
        jBtnThongke.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 60, 60));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Thống kê");
        jBtnThongke.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 180, 120));

        jBtnKhohang.setBackground(new java.awt.Color(153, 153, 153));
        jBtnKhohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnKhohangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseReleased(evt);
            }
        });
        jBtnKhohang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Warehouse_64px.png"))); // NOI18N
        jBtnKhohang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 21, 70, 60));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Kho hàng");
        jBtnKhohang.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnKhohang, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 180, 120));

        jBtnNguoidung.setBackground(new java.awt.Color(153, 153, 153));
        jBtnNguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMouseReleased(evt);
            }
        });
        jBtnNguoidung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_User_64px.png"))); // NOI18N
        jBtnNguoidung.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 56));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Người dùng");
        jBtnNguoidung.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnNguoidung, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 180, 120));

        jBtnKetoan.setBackground(new java.awt.Color(153, 153, 153));
        jBtnKetoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnKetoanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseReleased(evt);
            }
        });
        jBtnKetoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Coins_64px.png"))); // NOI18N
        jBtnKetoan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 60));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Kế toán");
        jBtnKetoan.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnKetoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 180, 120));

        jBtnThietlap.setBackground(new java.awt.Color(153, 153, 153));
        jBtnThietlap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThietlapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThietlapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThietlapMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThietlapMouseReleased(evt);
            }
        });
        jBtnThietlap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Settings_64px.png"))); // NOI18N
        jBtnThietlap.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 20, -1, 60));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Thiết lập");
        jBtnThietlap.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnThietlap, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 180, 120));

        jBtn7.setBackground(new java.awt.Color(204, 204, 204));
        jBtn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtn7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtn7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtn7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtn7MouseReleased(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Menu_40px.png"))); // NOI18N

        javax.swing.GroupLayout jBtn7Layout = new javax.swing.GroupLayout(jBtn7);
        jBtn7.setLayout(jBtn7Layout);
        jBtn7Layout.setHorizontalGroup(
            jBtn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jBtn7Layout.setVerticalGroup(
            jBtn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/navigation.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 80));

        jLabel14.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Get Managed");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Design, Create By Closer Group");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, -1));

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Support Management");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jPnHome.setBackground(new java.awt.Color(204, 204, 204));
        jPnHome.setOpaque(false);
        jPnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnTaoTK.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTaoTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tạo tài khoản");

        javax.swing.GroupLayout jBtnTaoTKLayout = new javax.swing.GroupLayout(jBtnTaoTK);
        jBtnTaoTK.setLayout(jBtnTaoTKLayout);
        jBtnTaoTKLayout.setHorizontalGroup(
            jBtnTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTaoTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jBtnTaoTKLayout.setVerticalGroup(
            jBtnTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnTaoTKLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(11, 11, 11))
        );

        jPnHome.add(jBtnTaoTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 38));

        jBtnDangxuat.setBackground(new java.awt.Color(0, 0, 0));
        jBtnDangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDangxuatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnDangxuatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnDangxuatMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Đăng xuất");

        javax.swing.GroupLayout jBtnDangxuatLayout = new javax.swing.GroupLayout(jBtnDangxuat);
        jBtnDangxuat.setLayout(jBtnDangxuatLayout);
        jBtnDangxuatLayout.setHorizontalGroup(
            jBtnDangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDangxuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jBtnDangxuatLayout.setVerticalGroup(
            jBtnDangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDangxuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPnHome.add(jBtnDangxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 180, 38));

        jBtnDoiMK.setBackground(new java.awt.Color(102, 102, 102));
        jBtnDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Đổi mật khẩu");

        javax.swing.GroupLayout jBtnDoiMKLayout = new javax.swing.GroupLayout(jBtnDoiMK);
        jBtnDoiMK.setLayout(jBtnDoiMKLayout);
        jBtnDoiMKLayout.setHorizontalGroup(
            jBtnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jBtnDoiMKLayout.setVerticalGroup(
            jBtnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPnHome.add(jBtnDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 180, 38));

        jBtnThongtin.setBackground(new java.awt.Color(51, 51, 51));
        jBtnThongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongtinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongtinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongtinMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongtinMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Thông tin");

        javax.swing.GroupLayout jBtnThongtinLayout = new javax.swing.GroupLayout(jBtnThongtin);
        jBtnThongtin.setLayout(jBtnThongtinLayout);
        jBtnThongtinLayout.setHorizontalGroup(
            jBtnThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongtinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jBtnThongtinLayout.setVerticalGroup(
            jBtnThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongtinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPnHome.add(jBtnThongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 180, 38));

        getContentPane().add(jPnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, 180, 160));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBanhang);
    }//GEN-LAST:event_jBtnBanhangMouseEntered

    private void jBtnBanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBanhang);
    }//GEN-LAST:event_jBtnBanhangMouseExited

    private void jBtnKhohangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseEntered
        // TODO add your handling code here:
        setColor(jBtnKhohang);
    }//GEN-LAST:event_jBtnKhohangMouseEntered

    private void jBtnKhohangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseExited
        // TODO add your handling code here:
        resetColor(jBtnKhohang);
        
    }//GEN-LAST:event_jBtnKhohangMouseExited

    private void jBtnKetoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseEntered
        // TODO add your handling code here:
        setColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMouseEntered

    private void jBtnKetoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseExited
        // TODO add your handling code here:
        resetColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMouseExited

    private void jBtnThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMouseEntered

    private void jBtnThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMouseExited

    private void jBtnNguoidungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMouseEntered
        // TODO add your handling code here:
        setColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMouseEntered

    private void jBtnNguoidungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMouseExited
        // TODO add your handling code here:
        resetColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMouseExited

    private void jBtnThietlapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMouseEntered

    private void jBtnThietlapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jBtnCloseMouseClicked

    private void jBtn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseEntered
        // TODO add your handling code here:
        setColor(jBtn7);
    }//GEN-LAST:event_jBtn7MouseEntered

    private void jBtn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseExited
        // TODO add your handling code here:
        resetColor(jBtn7);

    }//GEN-LAST:event_jBtn7MouseExited

    private void jBtnBanhangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBanhang);
    }//GEN-LAST:event_jBtnBanhangMousePressed

    private void jBtnBanhangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseReleased
        // TODO add your handling code here:
        if(jBtnBanhang.getBackground().equals(new Color(236,236,236,50))){
        setColor(jBtnBanhang);
        }
    }//GEN-LAST:event_jBtnBanhangMouseReleased

    private void jBtnKhohangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMousePressed
        // TODO add your handling code here:
        resetColor(jBtnKhohang);
    }//GEN-LAST:event_jBtnKhohangMousePressed

    private void jBtnKhohangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseReleased
        // TODO add your handling code here:
        setColor(jBtnKhohang);
    }//GEN-LAST:event_jBtnKhohangMouseReleased

    private void jBtnKetoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMousePressed
        // TODO add your handling code here:
        resetColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMousePressed

    private void jBtnKetoanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseReleased
        // TODO add your handling code here:
        setColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMouseReleased

    private void jBtnThongkeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMousePressed

    private void jBtnThongkeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMouseReleased

    private void jBtnNguoidungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMousePressed
        // TODO add your handling code here:
        resetColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMousePressed

    private void jBtnNguoidungMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMouseReleased
        // TODO add your handling code here:
        setColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMouseReleased

    private void jBtnThietlapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMousePressed

    private void jBtnThietlapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMouseReleased

    private void jBtn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MousePressed
        // TODO add your handling code here:
        resetColor(jBtn7);
    }//GEN-LAST:event_jBtn7MousePressed

    private void jBtn7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseReleased
        // TODO add your handling code here:
        setColor(jBtn7);
    }//GEN-LAST:event_jBtn7MouseReleased

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jBtnBanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseClicked
        // TODO add your handling code here:
        FormQuanLiBanHang frmQLBH= new FormQuanLiBanHang();
        frmQLBH.setVisible(true);
    }//GEN-LAST:event_jBtnBanhangMouseClicked

    private void jBtnKhohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseClicked
        // TODO add your handling code here:
        FormQuanLiKho frmQLK = new FormQuanLiKho();
        frmQLK.setVisible(true);
    }//GEN-LAST:event_jBtnKhohangMouseClicked

    private void jBtnKetoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseClicked
        // TODO add your handling code here:
        FormQuanLiKeToan frmQLKT = new FormQuanLiKeToan();
        frmQLKT.setVisible(true);
    }//GEN-LAST:event_jBtnKetoanMouseClicked

    private void jBtnThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseClicked
        // TODO add your handling code here:
        FormQuanLiThongKe frmQLTK  = new FormQuanLiThongKe();
        frmQLTK.setVisible(true);
    }//GEN-LAST:event_jBtnThongkeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jPnHome.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jBtnTaoTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMouseEntered

    private void jBtnTaoTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMouseExited

    private void jBtnDoiMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMouseEntered
        // TODO add your handling code here:
        setColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMouseEntered

    private void jBtnDoiMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMouseExited
        // TODO add your handling code here:
        resetColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMouseExited

    private void jBtnDangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDangxuatMouseEntered
        // TODO add your handling code here:
        setColor(jBtnDangxuat);
    }//GEN-LAST:event_jBtnDangxuatMouseEntered

    private void jBtnDangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDangxuatMouseExited
        // TODO add your handling code here:
        resetColor(jBtnDangxuat);
    }//GEN-LAST:event_jBtnDangxuatMouseExited

    private void jBtnThongtinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMouseEntered

    private void jBtnThongtinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMouseExited

    private void jBtn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseClicked
        // TODO add your handling code here:
        if(jPnHome.isVisible())
            jPnHome.setVisible(false);
        else
            jPnHome.setVisible(true);
    }//GEN-LAST:event_jBtn7MouseClicked

    private void jBtnTaoTKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMousePressed

    private void jBtnTaoTKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMouseReleased

    private void jBtnDoiMKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMousePressed
        // TODO add your handling code here:
        resetColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMousePressed

    private void jBtnDoiMKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMouseReleased
        // TODO add your handling code here:
        setColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMouseReleased

    private void jBtnThongtinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMousePressed

    private void jBtnThongtinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMouseReleased

    private void jBtnDangxuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDangxuatMousePressed
        // TODO add your handling code here:
        resetColor(jBtnDangxuat);
    }//GEN-LAST:event_jBtnDangxuatMousePressed

    private void jBtnDangxuatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDangxuatMouseReleased
        // TODO add your handling code here:
        setColor(jBtnDangxuat);
    }//GEN-LAST:event_jBtnDangxuatMouseReleased

    private void jBtnTaoTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseClicked
        // TODO add your handling code here:
        FormDangKi frmDangKi = new FormDangKi();
        frmDangKi.setVisible(true);
    }//GEN-LAST:event_jBtnTaoTKMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtn7;
    private javax.swing.JPanel jBtnBanhang;
    private javax.swing.JLabel jBtnClose;
    private javax.swing.JPanel jBtnDangxuat;
    private javax.swing.JPanel jBtnDoiMK;
    private javax.swing.JPanel jBtnKetoan;
    private javax.swing.JPanel jBtnKhohang;
    private javax.swing.JPanel jBtnNguoidung;
    private javax.swing.JPanel jBtnTaoTK;
    private javax.swing.JPanel jBtnThietlap;
    private javax.swing.JPanel jBtnThongke;
    private javax.swing.JPanel jBtnThongtin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnHome;
    // End of variables declaration//GEN-END:variables
}
