/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.CtrlDangNhap;
import Control.CtrlMainForm;
import Object.ObjTaiKhoan;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;


/**
 *
 * @author ThaiNguyen
 */
public class MainForm extends javax.swing.JFrame {

    int xx, yy;
    /**
     * Creates new form MainForm
     */

    public ObjTaiKhoan User = new ObjTaiKhoan("15520783","123456");
    CtrlMainForm ctrlMainFrm = new CtrlMainForm();

    public MainForm(ObjTaiKhoan objTK) {
        initComponents();
        setLocationRelativeTo(null);

        jPanel1.setBackground(new Color(0, 0, 0, 80));

        jPnHome.setVisible(false);

        jPnHome.setBackground(new Color(236, 236, 236, 50));

        jBtnTaoTK.setBackground(new Color(236, 236, 236, 50));
        jbtnDangXuat.setBackground(new Color(236, 236, 236, 50));
        jBtnDoiMK.setBackground(new Color(236, 236, 236, 50));
        jBtnThongtin.setBackground(new Color(236, 236, 236, 50));

        jBtnThietlap.setBackground(new Color(236, 236, 236, 50));
        jBtnNguoidung.setBackground(new Color(236, 236, 236, 50));
        jBtnThongke.setBackground(new Color(236, 236, 236, 50));
        jBtnBanhang.setBackground(new Color(236, 236, 236, 50));
        jBtnKhohang.setBackground(new Color(236, 236, 236, 50));
        jBtnKetoan.setBackground(new Color(236, 236, 236, 50));
        jBtn7.setBackground(new Color(236, 236, 236, 50));

        jlbUp.setVisible(false);
        
        User.setTenDangNhap(objTK.getTenDangNhap());
        User.setMatKhau(objTK.getMatKhau());
        PhanQuyenUser();
    }

    private MainForm() {
        initComponents();
        setLocationRelativeTo(null);

        jPanel1.setBackground(new Color(0, 0, 0, 80));

        jPnHome.setVisible(false);

        jPnHome.setBackground(new Color(236, 236, 236, 50));

        jBtnTaoTK.setBackground(new Color(236, 236, 236, 50));
        jbtnDangXuat.setBackground(new Color(236, 236, 236, 50));
        jBtnDoiMK.setBackground(new Color(236, 236, 236, 50));
        jBtnThongtin.setBackground(new Color(236, 236, 236, 50));

        jBtnThietlap.setBackground(new Color(236, 236, 236, 50));
        jBtnNguoidung.setBackground(new Color(236, 236, 236, 50));
        jBtnThongke.setBackground(new Color(236, 236, 236, 50));
        jBtnBanhang.setBackground(new Color(236, 236, 236, 50));
        jBtnKhohang.setBackground(new Color(236, 236, 236, 50));
        jBtnKetoan.setBackground(new Color(236, 236, 236, 50));
        jBtn7.setBackground(new Color(236, 236, 236, 50));
        
        jlbUp.setVisible(false);
        
        PhanQuyenUser();
    }

    public void setColor(JPanel pn) {
        if (pn.isEnabled()) {
            pn.setSize(pn.getWidth() + 1, pn.getHeight() + 1);
            pn.setBackground(new Color(60, 209, 127, 50));
        }
    }

    public void resetColor(JPanel pn) {
        if (pn.isEnabled()) {
            pn.setSize(pn.getWidth() - 1, pn.getHeight() - 1);
            pn.setBackground(new Color(236, 236, 236, 50));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnClose = new javax.swing.JLabel();
        jBtnBanhang = new javax.swing.JPanel();
        jlbIconBanHang = new javax.swing.JLabel();
        jlbBanHang = new javax.swing.JLabel();
        jBtnThongke = new javax.swing.JPanel();
        jlbIconThongKe = new javax.swing.JLabel();
        jlbThongKe = new javax.swing.JLabel();
        jBtnKhohang = new javax.swing.JPanel();
        jlbIconKhoHang = new javax.swing.JLabel();
        jlbKhoHang = new javax.swing.JLabel();
        jBtnNguoidung = new javax.swing.JPanel();
        jlbIconNguoiDung = new javax.swing.JLabel();
        jlbNguoiDung = new javax.swing.JLabel();
        jBtnKetoan = new javax.swing.JPanel();
        jlbIconKeToan = new javax.swing.JLabel();
        jlbKeToan = new javax.swing.JLabel();
        jBtnThietlap = new javax.swing.JPanel();
        jlbIconThietLap = new javax.swing.JLabel();
        jlbThietLap = new javax.swing.JLabel();
        jBtn7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jlbDown = new javax.swing.JLabel();
        jlbUp = new javax.swing.JLabel();
        jlbThonTinChucVu = new javax.swing.JLabel();
        jlbThonTinUser = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPnHome = new javax.swing.JPanel();
        jBtnTaoTK = new javax.swing.JPanel();
        jlbTaoTK = new javax.swing.JLabel();
        jbtnDangXuat = new javax.swing.JPanel();
        jlbDangXuat = new javax.swing.JLabel();
        jBtnDoiMK = new javax.swing.JPanel();
        jlbDoiMK = new javax.swing.JLabel();
        jBtnThongtin = new javax.swing.JPanel();
        jlbThongTin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnClose.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jBtnClose.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClose.setText("X");
        jBtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 20, 30));

        jBtnBanhang.setBackground(new java.awt.Color(153, 153, 153));
        jBtnBanhang.setEnabled(false);
        jBtnBanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBanhangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnBanhangMouseReleased(evt);
            }
        });
        jBtnBanhang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIconBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Shopping_Cart_64px_3.png"))); // NOI18N
        jlbIconBanHang.setEnabled(false);
        jBtnBanhang.add(jlbIconBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 60, 60));

        jlbBanHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbBanHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBanHang.setText("Bán hàng");
        jlbBanHang.setEnabled(false);
        jBtnBanhang.add(jlbBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnBanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 180, 120));

        jBtnThongke.setBackground(new java.awt.Color(153, 153, 153));
        jBtnThongke.setEnabled(false);
        jBtnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongkeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongkeMouseReleased(evt);
            }
        });
        jBtnThongke.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIconThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Statistics_64px.png"))); // NOI18N
        jlbIconThongKe.setEnabled(false);
        jBtnThongke.add(jlbIconThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 60, 60));

        jlbThongKe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongKe.setText("Thống kê");
        jlbThongKe.setEnabled(false);
        jBtnThongke.add(jlbThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 180, 120));

        jBtnKhohang.setBackground(new java.awt.Color(153, 153, 153));
        jBtnKhohang.setEnabled(false);
        jBtnKhohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnKhohangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnKhohangMouseReleased(evt);
            }
        });
        jBtnKhohang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIconKhoHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconKhoHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Warehouse_64px.png"))); // NOI18N
        jlbIconKhoHang.setEnabled(false);
        jBtnKhohang.add(jlbIconKhoHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 21, 70, 60));

        jlbKhoHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbKhoHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbKhoHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbKhoHang.setText("Kho hàng");
        jlbKhoHang.setEnabled(false);
        jBtnKhohang.add(jlbKhoHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnKhohang, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 180, 120));

        jBtnNguoidung.setBackground(new java.awt.Color(153, 153, 153));
        jBtnNguoidung.setEnabled(false);
        jBtnNguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnNguoidungMouseReleased(evt);
            }
        });
        jBtnNguoidung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIconNguoiDung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_User_64px.png"))); // NOI18N
        jlbIconNguoiDung.setEnabled(false);
        jBtnNguoidung.add(jlbIconNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 56));

        jlbNguoiDung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbNguoiDung.setForeground(new java.awt.Color(255, 255, 255));
        jlbNguoiDung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNguoiDung.setText("Người dùng");
        jlbNguoiDung.setEnabled(false);
        jBtnNguoidung.add(jlbNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnNguoidung, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 180, 120));

        jBtnKetoan.setBackground(new java.awt.Color(153, 153, 153));
        jBtnKetoan.setEnabled(false);
        jBtnKetoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnKetoanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnKetoanMouseReleased(evt);
            }
        });
        jBtnKetoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIconKeToan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconKeToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Coins_64px.png"))); // NOI18N
        jlbIconKeToan.setEnabled(false);
        jBtnKetoan.add(jlbIconKeToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 60));

        jlbKeToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbKeToan.setForeground(new java.awt.Color(255, 255, 255));
        jlbKeToan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbKeToan.setText("Kế toán");
        jlbKeToan.setEnabled(false);
        jBtnKetoan.add(jlbKeToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnKetoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 180, 120));

        jBtnThietlap.setBackground(new java.awt.Color(153, 153, 153));
        jBtnThietlap.setEnabled(false);
        jBtnThietlap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThietlapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThietlapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThietlapMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThietlapMouseReleased(evt);
            }
        });
        jBtnThietlap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIconThietLap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIconThietLap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Settings_64px.png"))); // NOI18N
        jlbIconThietLap.setEnabled(false);
        jBtnThietlap.add(jlbIconThietLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 20, -1, 60));

        jlbThietLap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbThietLap.setForeground(new java.awt.Color(255, 255, 255));
        jlbThietLap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThietLap.setText("Thiết lập");
        jlbThietLap.setEnabled(false);
        jBtnThietlap.add(jlbThietLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, -1));

        getContentPane().add(jBtnThietlap, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 180, 120));

        jBtn7.setBackground(new java.awt.Color(204, 204, 204));
        jBtn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtn7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtn7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtn7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtn7MouseReleased(evt);
            }
        });
        jBtn7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Male_User_45px_1.png"))); // NOI18N
        jBtn7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 60, 40));

        jlbDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Chevron_Down_20px_2.png"))); // NOI18N
        jBtn7.add(jlbDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 11, 23, 38));

        jlbUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Chevron_Up_20px_1.png"))); // NOI18N
        jBtn7.add(jlbUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 11, 23, 38));

        jlbThonTinChucVu.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbThonTinChucVu.setForeground(new java.awt.Color(255, 255, 255));
        jlbThonTinChucVu.setText("Chức vụ :");
        jBtn7.add(jlbThonTinChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 35, 194, -1));

        jlbThonTinUser.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jlbThonTinUser.setForeground(new java.awt.Color(255, 255, 255));
        jlbThonTinUser.setText("Người dùng :");
        jBtn7.add(jlbThonTinUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 15, 194, -1));

        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 60));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/navigation.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 80));

        jLabel14.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Get Managed");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Design, Create By Closer Group");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, -1));

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Support Management");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jPnHome.setBackground(new java.awt.Color(204, 204, 204));
        jPnHome.setOpaque(false);
        jPnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnTaoTK.setBackground(new java.awt.Color(153, 153, 153));
        jBtnTaoTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnTaoTKMouseReleased(evt);
            }
        });

        jlbTaoTK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbTaoTK.setForeground(new java.awt.Color(255, 255, 255));
        jlbTaoTK.setText("Tạo tài khoản");
        jlbTaoTK.setEnabled(false);

        javax.swing.GroupLayout jBtnTaoTKLayout = new javax.swing.GroupLayout(jBtnTaoTK);
        jBtnTaoTK.setLayout(jBtnTaoTKLayout);
        jBtnTaoTKLayout.setHorizontalGroup(
            jBtnTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTaoTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTaoTK)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jBtnTaoTKLayout.setVerticalGroup(
            jBtnTaoTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnTaoTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTaoTK, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPnHome.add(jBtnTaoTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 299, 38));

        jbtnDangXuat.setBackground(new java.awt.Color(0, 0, 0));
        jbtnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnDangXuatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnDangXuatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbtnDangXuatMouseReleased(evt);
            }
        });

        jlbDangXuat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        jlbDangXuat.setText("Đăng xuất");
        jlbDangXuat.setEnabled(false);

        javax.swing.GroupLayout jbtnDangXuatLayout = new javax.swing.GroupLayout(jbtnDangXuat);
        jbtnDangXuat.setLayout(jbtnDangXuatLayout);
        jbtnDangXuatLayout.setHorizontalGroup(
            jbtnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbtnDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDangXuat)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jbtnDangXuatLayout.setVerticalGroup(
            jbtnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbtnDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPnHome.add(jbtnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 299, 38));

        jBtnDoiMK.setBackground(new java.awt.Color(102, 102, 102));
        jBtnDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnDoiMKMouseReleased(evt);
            }
        });

        jlbDoiMK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbDoiMK.setForeground(new java.awt.Color(255, 255, 255));
        jlbDoiMK.setText("Đổi mật khẩu");
        jlbDoiMK.setEnabled(false);

        javax.swing.GroupLayout jBtnDoiMKLayout = new javax.swing.GroupLayout(jBtnDoiMK);
        jBtnDoiMK.setLayout(jBtnDoiMKLayout);
        jBtnDoiMKLayout.setHorizontalGroup(
            jBtnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDoiMK)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jBtnDoiMKLayout.setVerticalGroup(
            jBtnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBtnDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPnHome.add(jBtnDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 299, 38));

        jBtnThongtin.setBackground(new java.awt.Color(51, 51, 51));
        jBtnThongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnThongtinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnThongtinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThongtinMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnThongtinMouseReleased(evt);
            }
        });

        jlbThongTin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbThongTin.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongTin.setText("Thông tin");
        jlbThongTin.setEnabled(false);

        javax.swing.GroupLayout jBtnThongtinLayout = new javax.swing.GroupLayout(jBtnThongtin);
        jBtnThongtin.setLayout(jBtnThongtinLayout);
        jBtnThongtinLayout.setHorizontalGroup(
            jBtnThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongtinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThongTin)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jBtnThongtinLayout.setVerticalGroup(
            jBtnThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBtnThongtinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPnHome.add(jBtnThongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 299, 38));

        getContentPane().add(jPnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 79, 299, 160));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pexels-photo.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void PhanQuyenUser() {
        try {
            ResultSet rs = ctrlMainFrm.LayThongTinUser(User.getTenDangNhap(), User.getMatKhau());
            if (rs.next()) {
                User.setTen(rs.getString("Ten"));
                User.setPhanLoai(rs.getString("PhanLoai"));
//                jlbThonTinUser.setText("User : "+rs.getString("Ten")+" - "+rs.getString("PhanLoai"));
                jlbThonTinUser.setText("Người dùng : "+User.getTen());
                jlbThonTinChucVu.setText("Chức vụ  : "+User.getPhanLoai());
                if (User.getPhanLoai().equals("Quản lý bán hàng")) {
                    SetQuanLiBanHang();
                }
                else if (User.getPhanLoai().equals("Quản lý kho")){
                    SetQuanLiKho();
                }
                else if (User.getPhanLoai().equals("Quản lý kế toán")){
                    SetQuanLiKeToan();
                }
                else if (User.getPhanLoai().equals("Quản lý")){
                    SetQuanLi();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            ctrlMainFrm.CloseConnection();
        }
    }

    public void SetQuanLi() {
        SetQuanLiBanHang();
        SetQuanLiKeToan();
        SetQuanLiKho();
        jBtnNguoidung.setEnabled(true);
        jlbIconNguoiDung.setEnabled(true);
        jlbNguoiDung.setEnabled(true);
        jBtnThietlap.setEnabled(true);
        jlbIconThietLap.setEnabled(true);
        jlbThietLap.setEnabled(true);
        jBtnTaoTK.setEnabled(true);
        jlbTaoTK.setEnabled(true);
    }

    public void SetQuanLiBanHang() {
        jBtnBanhang.setEnabled(true);
        jlbIconBanHang.setEnabled(true);
        jlbBanHang.setEnabled(true);
        jBtnDoiMK.setEnabled(true);
        jlbDoiMK.setEnabled(true);
        jbtnDangXuat.setEnabled(true);
        jlbDangXuat.setEnabled(true);
        jBtnThongke.setEnabled(true);
        jlbIconThongKe.setEnabled(true);
        jlbThongKe.setEnabled(true);
        jBtnThongtin.setEnabled(true);
        jlbThongTin.setEnabled(true);
    }
    
    public void SetQuanLiKho(){
        jBtnKhohang.setEnabled(true);
        jlbIconKhoHang.setEnabled(true);
        jlbKhoHang.setEnabled(true);
        jBtnDoiMK.setEnabled(true);
        jlbDoiMK.setEnabled(true);
        jbtnDangXuat.setEnabled(true);
        jlbDangXuat.setEnabled(true);
        jBtnThongke.setEnabled(true);
        jlbIconThongKe.setEnabled(true);
        jlbThongKe.setEnabled(true);
        jBtnThongtin.setEnabled(true);
        jlbThongTin.setEnabled(true);
    }
    
    public void SetQuanLiKeToan(){
        jBtnKetoan.setEnabled(true);
        jlbIconKeToan.setEnabled(true);
        jlbKeToan.setEnabled(true);
        jBtnDoiMK.setEnabled(true);
        jlbDoiMK.setEnabled(true);
        jbtnDangXuat.setEnabled(true);
        jlbDangXuat.setEnabled(true);
        jBtnThongke.setEnabled(true);
        jlbIconThongKe.setEnabled(true);
        jlbThongKe.setEnabled(true);
        jBtnThongtin.setEnabled(true);
        jlbThongTin.setEnabled(true);
    }

    private void jBtnBanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseEntered
        // TODO add your handling code here:
        setColor(jBtnBanhang);
    }//GEN-LAST:event_jBtnBanhangMouseEntered

    private void jBtnBanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseExited
        // TODO add your handling code here:
        resetColor(jBtnBanhang);
    }//GEN-LAST:event_jBtnBanhangMouseExited

    private void jBtnKhohangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseEntered
        // TODO add your handling code here:
        setColor(jBtnKhohang);
    }//GEN-LAST:event_jBtnKhohangMouseEntered

    private void jBtnKhohangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseExited
        // TODO add your handling code here:
        resetColor(jBtnKhohang);

    }//GEN-LAST:event_jBtnKhohangMouseExited

    private void jBtnKetoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseEntered
        // TODO add your handling code here:
        setColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMouseEntered

    private void jBtnKetoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseExited
        // TODO add your handling code here:
        resetColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMouseExited

    private void jBtnThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMouseEntered

    private void jBtnThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMouseExited

    private void jBtnNguoidungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMouseEntered
        // TODO add your handling code here:
        setColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMouseEntered

    private void jBtnNguoidungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMouseExited
        // TODO add your handling code here:
        resetColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMouseExited

    private void jBtnThietlapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMouseEntered

    private void jBtnThietlapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMouseExited

    private void jBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jBtnCloseMouseClicked

    private void jBtn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseEntered
        // TODO add your handling code here:
        setColor(jBtn7);
    }//GEN-LAST:event_jBtn7MouseEntered

    private void jBtn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseExited
        // TODO add your handling code here:
        resetColor(jBtn7);

    }//GEN-LAST:event_jBtn7MouseExited

    private void jBtnBanhangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMousePressed
        // TODO add your handling code here:
        resetColor(jBtnBanhang);
    }//GEN-LAST:event_jBtnBanhangMousePressed

    private void jBtnBanhangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseReleased
        // TODO add your handling code here:
        if (jBtnBanhang.getBackground().equals(new Color(236, 236, 236, 50))) {
            setColor(jBtnBanhang);
        }
    }//GEN-LAST:event_jBtnBanhangMouseReleased

    private void jBtnKhohangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMousePressed
        // TODO add your handling code here:
        resetColor(jBtnKhohang);
    }//GEN-LAST:event_jBtnKhohangMousePressed

    private void jBtnKhohangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseReleased
        // TODO add your handling code here:
        setColor(jBtnKhohang);
    }//GEN-LAST:event_jBtnKhohangMouseReleased

    private void jBtnKetoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMousePressed
        // TODO add your handling code here:
        resetColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMousePressed

    private void jBtnKetoanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseReleased
        // TODO add your handling code here:
        setColor(jBtnKetoan);
    }//GEN-LAST:event_jBtnKetoanMouseReleased

    private void jBtnThongkeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMousePressed

    private void jBtnThongkeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThongke);
    }//GEN-LAST:event_jBtnThongkeMouseReleased

    private void jBtnNguoidungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMousePressed
        // TODO add your handling code here:
        resetColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMousePressed

    private void jBtnNguoidungMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNguoidungMouseReleased
        // TODO add your handling code here:
        setColor(jBtnNguoidung);
    }//GEN-LAST:event_jBtnNguoidungMouseReleased

    private void jBtnThietlapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMousePressed

    private void jBtnThietlapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThietlapMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThietlap);
    }//GEN-LAST:event_jBtnThietlapMouseReleased

    private void jBtn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MousePressed
        // TODO add your handling code here:
        resetColor(jBtn7);
    }//GEN-LAST:event_jBtn7MousePressed

    private void jBtn7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseReleased
        // TODO add your handling code here:
        setColor(jBtn7);
    }//GEN-LAST:event_jBtn7MouseReleased

    private void jBtnBanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBanhangMouseClicked
        // TODO add your handling code here:
        if (jBtnBanhang.isEnabled()) {
            FormQuanLiBanHang frmQLBH = new FormQuanLiBanHang(User);
            frmQLBH.setVisible(true);
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_jBtnBanhangMouseClicked

    private void jBtnKhohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKhohangMouseClicked
        // TODO add your handling code here:
        if (jBtnKhohang.isEnabled()) {
            FormQuanLiKho frmQLK = new FormQuanLiKho(User);
            frmQLK.setVisible(true);
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_jBtnKhohangMouseClicked

    private void jBtnKetoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnKetoanMouseClicked
        // TODO add your handling code here:
        if (jBtnKetoan.isEnabled()) {
            FormQuanLiKeToan frmQLKT = new FormQuanLiKeToan(User);
            frmQLKT.setVisible(true);
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_jBtnKetoanMouseClicked

    private void jBtnThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongkeMouseClicked
        // TODO add your handling code here:
        if (jBtnThongke.isEnabled()) {
            FormQuanLiThongKe frmQLTK = new FormQuanLiThongKe();
            frmQLTK.setVisible(true);
        }
    }//GEN-LAST:event_jBtnThongkeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jBtnTaoTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseEntered
        // TODO add your handling code here:
        setColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMouseEntered

    private void jBtnTaoTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseExited
        // TODO add your handling code here:
        resetColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMouseExited

    private void jBtnDoiMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMouseEntered
        // TODO add your handling code here:
        setColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMouseEntered

    private void jBtnDoiMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMouseExited
        // TODO add your handling code here:
        resetColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMouseExited

    private void jbtnDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDangXuatMouseEntered
        // TODO add your handling code here:
        setColor(jbtnDangXuat);
    }//GEN-LAST:event_jbtnDangXuatMouseEntered

    private void jbtnDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDangXuatMouseExited
        // TODO add your handling code here:
        resetColor(jbtnDangXuat);
    }//GEN-LAST:event_jbtnDangXuatMouseExited

    private void jBtnThongtinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMouseEntered
        // TODO add your handling code here:
        setColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMouseEntered

    private void jBtnThongtinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMouseExited
        // TODO add your handling code here:
        resetColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMouseExited

    private void jBtn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseClicked
        // TODO add your handling code here:
        if (jPnHome.isVisible()) {
            jPnHome.setVisible(false);
            jlbDown.setVisible(true);
            jlbUp.setVisible(false);
        } else {
            jPnHome.setVisible(true);
            jlbDown.setVisible(false);
            jlbUp.setVisible(true);
        }
    }//GEN-LAST:event_jBtn7MouseClicked

    private void jBtnTaoTKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMousePressed
        // TODO add your handling code here:
        resetColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMousePressed

    private void jBtnTaoTKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseReleased
        // TODO add your handling code here:
        setColor(jBtnTaoTK);
    }//GEN-LAST:event_jBtnTaoTKMouseReleased

    private void jBtnDoiMKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMousePressed
        // TODO add your handling code here:
        resetColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMousePressed

    private void jBtnDoiMKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDoiMKMouseReleased
        // TODO add your handling code here:
        setColor(jBtnDoiMK);
    }//GEN-LAST:event_jBtnDoiMKMouseReleased

    private void jBtnThongtinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMousePressed
        // TODO add your handling code here:
        resetColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMousePressed

    private void jBtnThongtinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongtinMouseReleased
        // TODO add your handling code here:
        setColor(jBtnThongtin);
    }//GEN-LAST:event_jBtnThongtinMouseReleased

    private void jbtnDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDangXuatMousePressed
        // TODO add your handling code here:
        resetColor(jbtnDangXuat);
    }//GEN-LAST:event_jbtnDangXuatMousePressed

    private void jbtnDangXuatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDangXuatMouseReleased
        // TODO add your handling code here:
        setColor(jbtnDangXuat);
    }//GEN-LAST:event_jbtnDangXuatMouseReleased

    private void jBtnTaoTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTaoTKMouseClicked
        // TODO add your handling code here:
        if (jlbTaoTK.isEnabled()) {
            FormDangKi frmDangKi = new FormDangKi();
            frmDangKi.setVisible(true);
        }
    }//GEN-LAST:event_jBtnTaoTKMouseClicked

    private void jbtnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnDangXuatMouseClicked
        // TODO add your handling code here:
        new FormDangNhap().setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jbtnDangXuatMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jPnHome.setVisible(false);
        jlbDown.setVisible(true);
        jlbUp.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtn7;
    private javax.swing.JPanel jBtnBanhang;
    private javax.swing.JLabel jBtnClose;
    private javax.swing.JPanel jBtnDoiMK;
    private javax.swing.JPanel jBtnKetoan;
    private javax.swing.JPanel jBtnKhohang;
    private javax.swing.JPanel jBtnNguoidung;
    private javax.swing.JPanel jBtnTaoTK;
    private javax.swing.JPanel jBtnThietlap;
    private javax.swing.JPanel jBtnThongke;
    private javax.swing.JPanel jBtnThongtin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnHome;
    private javax.swing.JPanel jbtnDangXuat;
    private javax.swing.JLabel jlbBanHang;
    private javax.swing.JLabel jlbDangXuat;
    private javax.swing.JLabel jlbDoiMK;
    private javax.swing.JLabel jlbDown;
    private javax.swing.JLabel jlbIconBanHang;
    private javax.swing.JLabel jlbIconKeToan;
    private javax.swing.JLabel jlbIconKhoHang;
    private javax.swing.JLabel jlbIconNguoiDung;
    private javax.swing.JLabel jlbIconThietLap;
    private javax.swing.JLabel jlbIconThongKe;
    private javax.swing.JLabel jlbKeToan;
    private javax.swing.JLabel jlbKhoHang;
    private javax.swing.JLabel jlbNguoiDung;
    private javax.swing.JLabel jlbTaoTK;
    private javax.swing.JLabel jlbThietLap;
    private javax.swing.JLabel jlbThonTinChucVu;
    private javax.swing.JLabel jlbThonTinUser;
    private javax.swing.JLabel jlbThongKe;
    private javax.swing.JLabel jlbThongTin;
    private javax.swing.JLabel jlbUp;
    // End of variables declaration//GEN-END:variables
}
